xmonad/xmonad-contrib

XMonad/Hooks/DynamicBars.hs
This is just the patch from https://code.google.com/p/xmonad/issues/detail?id=538, updated so it applies to the latest version of the file.
This fixes that issue for me using both the minimal `xmonad.hs` from the bug report and using my real configuration.
=> Use existing connection in X.H.DynamicBars

XMonad/Hooks/DynamicLog.hs
This is a port of a personal patch I've been meaning to contribute. I haven't tried to compile it outside of my xmonad.hs but it should work.
Consider the old implementation:
> \> xmobarStrip "\<\<fc=#f00>fc=#f00>foo\</\</fc>fc>"
"\<fc=#f00>foo\</fc>"
While the result should be "foo", nothing more.
I don't know dzen markup but dzenStrip might suffer from the same problem.
=> X.H.DynamicLog: make xmobarStrip actually strip xmobar tags

XMonad/Actions/DynamicProjects.hs, xmonad-contrib.cabal
Inspired by `TopicSpace`, `DynamicWorkspaces`, and `WorkspaceDir`,
`DynamicProjects` treats workspaces as projects while maintaining
compatibility with all existing workspace-related functionality in
XMonad.
=> New module: XMonad.Actions.DynamicProjects

XMonad/Prompt.hs
alwaysHighlight option doesn't work with moveHistory currently. We need to reset complIndex and select first element inside moveHistory.
=> Bugfix for moveHistory when alwaysHighlight is enabled.

.mailmap, CHANGES.md, XMonad/Prompt.hs
This patch enables support for key binding like Ctrl + i which was not
previously possible. Technically, this changes the type of completionKey
from KeySym to (KeyMask, KeySym). Note that programs like dmenu support
Ctrl + i by default.
=> Add multiple key support for completion key

XMonad/Actions/FloatSnap.hs, XMonad/Hooks/ManageDocks.hs, XMonad/Hooks/PositionStoreHooks.hs, XMonad/Layout/DecorationAddons.hs
this seems to fix the regression(i've tested with dzen2 and plasmashell) but i'm not sure that this wouldn't cause the [issue](http://www.haskell.org/pipermail/xmonad/2013-April/013670.html) (couldn't reproduce it), fix of which caused the regression
=> fix xmonad/xmonad#21

XMonad/Layout/Groups/Wmii.hs
The current value of `toggleGroupFull` is ⊥, since it's defined as `toggleGroupFull = toggleGroupFull`.
Presumably, this is a typo for `toggleColumnFull` from `XMonad.Layout.Groups.Examples`.
=> Fixed bottom-yielding definition of toggleGroupFull

XMonad/Layout/IfMax.hs
watching for floating windows can cause problems when using with X.L.MouseResizableTile and watching only for tiled is more intuitive.
=> watch only for tiled windows in X.L.IfMax

CHANGES.md, XMonad/Util/Ungrab.hs, xmonad-contrib.cabal
This module provides a better workaround for xmonad holding the keyboard grab through actions, causing spawned commands that also want to do a grab to fail.
=> add X.U.Ungrab

XMonad/Actions/WindowBringer.hs
I love WindowBringer but I sometimes forget the menu items (window titles) are all lowercase. I type a capital letter, e.g. "Makefile" and get no results.
I tested this change and it works, whether the user enters all lowercase (as before) or mixed case.
=> Make WindowBringer case insensitive

CHANGES.md, XMonad/Util/Loggers/NamedScratchpad.hs, XMonad/Util/NoTaskbar.hs, xmonad-contrib.cabal
Adds machinery and several Loggers for NamedScratchPads. Also adds a utility function to hide windows from EWMH taskbars and pagers, since they won't do what you expect with windows in the NSP workspace.
=> XMonad.Util.Loggers for NamedScratchPad-s

XMonad/Prompt/Window.hs
- The set of windows proposed by the prompt can be parametrized. Two
helper functions are currently defined. One for selecting all
available windows and another one for selecting all windows of the
current workspace.
- Add BringToMaster action which brings the selected window to the
current workspace and set it as master.
- windowPromptGoto, windowPromptBring, windowPromptBringCopy are
marked as deprecated since they can be realized by the more generic
windowPrompt function.  For instance, "windowPromptGoto prompt" can
be easily replaced by "windowPrompt prompt Goto allWindows".
=> X.P.Window: add window selector for the prompt and BringToMaster action

XMonad/Util/EZConfig.hs, XMonad/Util/Run.hs
* Fix a minor error in the documentation of the function `seconds`
* Fix type declaration for two EZConfig functions used to configure keybindings. I think they should take a `KeyMask` instead of a `ButtonMask` (both are synonym for `Modifier` which is a `CUInt`).
=> Fix minor things

XMonad/Hooks/DynamicBars.hs
Add functions to allow cleaning up only screens which disappear. This
works better where killing the statusbar for a specific screen is
possible. The old way is still relevant for setups which do not have
such a method (e.g., safeSpawn xmobar/spawnPipe xmonadpropwrite).
=> X.H.DynamicBars: support per-monitor cleanup

XMonad/Doc/Extending.hs
There were quite a few modules missing from the XMonad.Doc.Extending module. This PR updates XMonad.Doc.Extending to include those modules. Discretion might be appropriate for including the Config modules that are personal xmonad configs.
=> Add missing Extending documentation for new modules

XMonad/Layout/Groups.hs
This is a fix I have applied locally to make sure that when I use decorated layouts like tabbed in groups, XMonad does not leave bogus decoration windows lying around.
I think that the issue fixed is that the set of groups to send `Hide` to is determined by subtracting the extant groups from `l`, but `l` has already been put through `readapt` and so some groups may have been removed (if they are empty), so they don't get the Hide message.
The comparison should therefore be between `_l` and the new groups.
It seems to work for me.
=> Determine which groups to Hide correctly

XMonad/Actions/Navigation2D.hs
The documentation in the diffs pretty much covers it, but to summarise, I simply combined the two navigation methods that were already implemented into a 'best of both worlds' version. Line navigation fails to produce the expected motions when the line it's using falls on gaps, so in these cases you want to fall back on the more robust Center navigation, and that's exactly what Hybrid navigation does.
This is my first contribution to xmonad and also my first pull request, so please do provide constructive criticism if I've done something stupid or failed to follow some style guideline.
Edit: An example of a layout where gaps break Line navigation, in case it wasn't clear what the problem was. The layout below is achieved with SplitGrid tiling mode.
Here, if focus is on one of the six …
=> A very simple extension to Navigation2D so it plays better with gaps

XMonad/Actions/TreeSelect.hs, XMonad/Doc/Extending.hs, XMonad/Layout/Groups.hs, XMonad/Util/TreeZipper.hs, xmonad-contrib.cabal
You can select the desired workspace/action with the cursor or hjkl keys
This module is fully configurable and very useful if you have a lot of workspaces.
I tryed to document the entire module. For more info look at that module (XMonad.Actions.TreeSelect)
=> Add TreeSelect action for selecting from many workspaces and X actions

XMonad/Actions/Workscreen.hs
This is fixing for problem that
WorkscreenId was shown in XMonad.Actions.Workscreen document
(ex: viewWorkscreen),
but never shown WorkscreenId definition.
Is this the intension ?
=> Export XMonad.Actions.Workscreen (WorkscreenId)

XMonad/Actions/DynamicWorkspaces.hs
You can add indexes to workspaces and use them to do actions on
workspaces. This allows you to dynamicaly associate a workspace to a
keybinding without depending of the workspace name or the workspace
position.
=> X.A.DynamicWorkspaces: associate indexes to workspaces

XMonad/Prompt/Pass.hs
XMonad.Prompt allows the user to specify a search predicate in XPConfig.
However, previously XMonad.Prompt.Pass did not apply this predicate.
This now applies the predicate in similar manner as XMonad.Prompt.Shell.
=> XMonad.Prompt.Pass: Use searchPredicate from XPConfig

XMonad/Prompt.hs
The docs for `autoComplete` and `showCompletionOnTab` look like they've been jumbled up.
https://hackage.haskell.org/package/xmonad-contrib-0.12/docs/XMonad-Prompt.html#t:XPConfig
=> fix broken XPConfig docs

CHANGES.md, XMonad/Layout/LayoutBuilder.hs, XMonad/Layout/LayoutBuilderP.hs
X.L.LayoutBuilderP is nearly identical to X.L.LayoutBuilder.  Originally
I wanted to add the ability to dynamically resize the layout boxes so it
make a lot of sense to join these two modules together so I wouldn't
have to do it in both.  Even though I never got around to that I still
think it's a good idea to merge these two modules into one.
I believe I was able to merge these without creating any
backward-compatibility issues.  I've been sitting on these changes since
2015 and they work for me without having to change older parts of my
config (relating to X.L.LayoutBuilder).
If anyone wants to work on dynamically resizing layout boxes the issue I
created for it is #36.
=> Refactor all X.L.LayoutBuilderP functionality into X.L.LayoutBuilder

XMonad/Actions/WindowGo.hs
Motivation: I prefer to use a greedier focus function that switches the workspace on the current screen to the focused window.
``` haskell
greedyFocusWindow w ws = W.focusWindow w $ W.greedyView
(fromMaybe (W.currentTag ws) $ W.findTag w ws) ws
```
This pull request exposes a version of raiseNextMaybe to which a custom focus function, such as the one that I prefer, can be provided.
=> X.A.WindowGo: Add arg for custom focus fn to raiseNextMaybe

XMonad/Layout/Groups/Helpers.hs
ImpredicativeTypes is practically unsupported extension
on it's way to be removed from GHC:
https://mail.haskell.org/pipermail/ghc-devs/2016-September/012826.html
GHC-8.0.2-rc1 already fails to build xmonad-contrib as:
XMonad/Layout/Groups/Helpers.hs:181:22: error:
• Couldn't match type ‘G.WithID l0 Window
-> XMonad.Util.Stack.Zipper (G.Group l0 Window)
-> XMonad.Util.Stack.Zipper (G.Group l0 Window)’
with ‘G.ModifySpec’
Expected type: (G.WithID l0 Window
-> XMonad.Util.Stack.Zipper (G.Group l0 Window)
-> XMonad.Util.Stack.Zipper (G.Group l0 Window))
-> G.GroupsMessage
Actual type: G.ModifySpec -> G.GroupsMessage
• In the second argument of ‘(.)’, namely ‘G.Modify’
In the expression: sendMessage . G.Modify
In an equation for ‘wrap’: wrap = sendMessage . G.Modify
The workaround is simple: …
=> XMonad/Layout/Groups/Helpers.hs: drop broken ImpredicativeTypes extension (fixes #123)

XMonad/Util/CustomKeys.hs
Fix code example in documentation. (Wrong implementation of `delkeys`.)
Thanks to Lasse R.H. Nielsen (@lrhn) for reporting the problem!
=> CustomKeys.hs: Fix documentation

CHANGES.md, XMonad/Actions/WindowGo.hs
As discussed in #120, this patch introduces workspaceSorted and allWindowsSorted to provide an ordering of windows which does not change when changing the current workspace.
=> Fix #120 - Make Actions.WindowGo.raiseNextMaybe span over all workspaces

CHANGES.md, XMonad/Actions/Submap.hs
Establish active asynchronous pointer grab before entering infinity cycle.
Because xmonad already has passive synchronous pointer grab, this overwrites
it temporary and avoids freezing X, when button press occurs after submap key
press.
Also, terminate submap at button press the same way, as we do for wrong key
press.
=> X.A.Submap: establish pointer grab to avoid freezing X.

XMonad/Hooks/DynamicProperty.hs
All False short-cuts the default behavior for the event, which leads to a non-functioning window manager. Returning mempty ensures that the default action is still executed,
=> DynamicProperty: execute other hooks

XMonad/Actions/CycleWS.hs
When I have multiscreen I think it's usefull to get the next empty workspace
that is not already displayed.
=> Add HiddenEmptyWS to CycleWS

CHANGES.md
Fix CHANGES.md after "X.A.Submap: establish pointer grab to avoid freezing X."
=> Fix CHANGES.md after b9d8f6c .

CHANGES.md, XMonad/Prompt.hs
Prompt should have been using getXMonadDir this entire time but since
we now have getXMonadCacheDir use that instead.  This brings
xmonad-contrib inline with the changes in xmonad/xmonad#62.
This also fixes xmonad/xmonad-contrib#68
=> Use the new getXMonadCacheDir function from #62

XMonad/Hooks/ManageDocks.hs
=> Manage struts even when _NET_WM_WINDOW_TYPE isn't a dock

XMonad/Hooks/UrgencyHook.hs, XMonad/Layout/WindowNavigation.hs, XMonad/Util/Font.hs, XMonad/Util/XUtils.hs
This brings xmonad-contrib inline with xmonad in this regard.  Should
also be fix for #138
behind them.
=> Use `setWindowBorderWithFallback' to support windows with RGBA color maps

XMonad/Prompt.hs
Describe how to use the 'font' field of 'XPC' record by adding two different examples.
behind them.
=> Better description of 'font' field of 'XPC' record

XMonad/Layout/BinarySpacePartition.hs
I've exported the `BinarySpacePartition` type as it's really hard to write type signatures without it!
I haven't updated the `CHANGES.md` file as it's non-obvious where to put changes for unreleased code. But I'm happy to amend them if needed.
=> export BinarySpacePartition type

CHANGES.md, XMonad/Actions/GridSelect.hs
2 small changes to `XMonad.Actions.GridSelect`:
1. **Allow border colour to be specified**
This required an extra field on `GSConfig` so it is a breaking change.
2. **Improve the vertical centring of text**
(I cut and pasted the code from `XMonad.Utils.Prompt`.)
**Before**:
**After**:
=> GridSelect: border colour and vertically centring text

CHANGES.md, XMonad/Layout/Magnifier.hs
Handle `IncMasterN` in the `Magnify` layout. Because `Magnify` has a concept of not magnifying the master window, I believe it makes sense to treat windows moved into the master pane as masters themselves (w.r.t. not being magnified). This works nicely when magnifying `FixedColumn` layouts.
=> Respect number of master windows in Magnify layout

CHANGES.md, XMonad/Prompt/Window.hs
Like 'windowPrompt', but uses the multiple modes feature of
@Prompt@ (via 'mkXPromptWithModes').
Given a list of actions along with the windows they should work
with, display the appropriate prompt with the ability to switch
between them using the @changeModeKey@.
For example, to have a prompt that first shows you all windows, but
allows you to narrow the list down to just the windows on the
current workspace:
> windowMultiPrompt config [(Goto, allWindows), (Goto, wsWindows)]
=> New function: `X.P.Window.windowMultiPrompt'

CHANGES.md, XMonad/Actions/SpawnOn.hs
See discussion in https://github.com/xmonad/xmonad/issues/27.
Works best with https://github.com/deepfire/ld-preload-xcreatewindow-net-wm-pid.
=> Spawnon child pid tracking

CHANGES.md, XMonad/Actions/Minimize.hs, XMonad/Actions/WindowMenu.hs, XMonad/Config/Bluetile.hs, XMonad/Hooks/Minimize.hs, XMonad/Hooks/RestoreMinimized.hs, XMonad/Layout/DecorationAddons.hs, XMonad/Layout/ImageButtonDecoration.hs, XMonad/Layout/Minimize.hs, XMonad/Util/Minimize.hs, xmonad-contrib.cabal
- Use global state instead of per-layout - so now window is minimized on
all workspaces (EWMH requires that windows with _NET_WM_STATE_HIDDEN
set should be minimized on any workspace but previously they were not)
- Use `windows` instead of `modify`. That should fix bugs related to
actions that should be done by `windows` and not done by
`modify` (fixes #46)
- Deprecated module X.H.RestoreMinimized is removed
~~TODO 515429f should be moved to another PR~~
**UPD** TODO entry in CHANGES.md
=> Rewrite minimization-related modules

CHANGES.md, XMonad/Actions/CycleWorkspaceByScreen.hs, XMonad/Hooks/WorkspaceHistory.hs, xmonad-contrib.cabal
Cycle through previously viewed workspaces in the order they were viewed most
recently on the screen where cycling is taking place.
The extremely long name is needed to differentiate this module from `XMonad.Actions.CycleRecentWS` which does something quite similar, with the main difference being that the history for different screens is not indendent (though it has the advantage of not depending on workspacse history)
I also provided the repeatableAction and update WorkspaceHistory as part of this change.
=> Cycle workspace by screen

CHANGES.md, XMonad/Layout/ComboP.hs
Add message to "re-partition" a ComboP layout
This is especially useful with the `Tagged' window property.
=> Add message to "re-partition" a ComboP layout

XMonad/Actions/CycleWorkspaceByScreen.hs, XMonad/Hooks/WorkspaceHistory.hs
Fixed parse errors when trying to build the documentation with `cabal haddock`.
=> trivial changes to fix haddock documentation

CHANGES.md, XMonad/Layout/LayoutHints.hs, XMonad/Layout/MultiColumns.hs
Before this fix, when using layoutHintsToCenter together with
MultiColumns, in certain situations XMonad would render the border of
the focused window below a border of unfocused windows. This looks odd
and is here fixed by changing MultiColumns to always place the focused
window in front (even though they should not really overlap) and making
LayoutHints preserve the order returned from the underlying layout,
except for the focused window that is placed on top.
This is a good idea since layoutHintsToCenter requires the focused
window to be on top for good rendering, even if that is not really
required when the underlying layout is used on its own. This way
layoutHintsToCenter requires less of the layout that is modified and
MultiColumns is more compatible with future layout modifiers …
=> Fix render order of LayoutHints and MultiColumns

XMonad/Util/Dmenu.hs
MonadIO is compatible with xfork which prevents dmenu prompts from freezing XMonad.
Without xfork, if I try to give focus to another window while dmenu is waiting, XMonad freezes until I kill dmenu in virtual terminal or ssh session.
=> Replace X with MonadIO in XMonad.Util.Dmenu

XMonad/Layout/Gaps.hs, XMonad/Layout/Spacing.hs
These layout have different applications but their names could cause some
confusion since the module names could just as well be swapped. To support this claim,
what we call "spacing" is named "gaps" in i3wm (i3-gaps). Therefore hyperlinks have
been added to inform the reader of the existence of the other module. 
A discussion about this can be found in #199.
=> X.L.Spacing + X.L.Gaps: add mutual hyperlink

XMonad/Actions/Commands.hs
The X.U.Dmenu library has support to run dmenu-like launchers, but X.A.Commands
has the use of dmenu hardcoded. This commit makes it possible to use other
launchers without duplicating existing code.
=> X.A.Commands: Parameterize runCommand to accept dmenu-like launchers.

README.md
The links are updated to point to Hackage rather than xmonad.org since not all redirects work correctly. For example the link to developing documentation went to the main XMonad's Hackage page instead of XMonad.Docs.Extending on Hackage.
Secondly, the links are changed such that their [id]-tag isn't showing.
Lastly, a link to XMonad's contributing.md has been added.
=> README.md: Update links and add contributing info.

CHANGES.md, XMonad/Config/Gnome.hs
The modm+shift+Q key combination in `XMonad.Config.Gnome` is supposed to open the logout dialog, but it tries to run a command that doesn't work with modern GNOME versions.
The `--kill` option was deprecated in [2.23.x (year 2008)](https://github.com/GNOME/gnome-session/blob/c91d138b33a96cf9ccc36893899db9abb8f272bb/NEWS#L1843)
`gnome-session-save` was renamed to `gnome-session-quit` in [2.91.x (year 2011)](https://github.com/GNOME/gnome-session/blob/c91d138b33a96cf9ccc36893899db9abb8f272bb/NEWS#L988)
I didn't test this change with xmonad-testing, but have used the fix in my config for a while with Ubuntu 17.04 (GNOME 3.22.0).
=> Fix Gnome config modm+shift+Q logout command

CHANGES.md, XMonad/Actions/Minimize.hs
I wanted to access the minimizedStack as if it were a queue, something which, despite the name, isn't a restriction to the module. The minimizedStack is just a `[Window]` anyways. This might not be particularly useful to many people, but it is to me.
I've compiled and am using the module with no errors, but have yet to write a minimal configuration for it to test with xmonad-testing. Given the size of the commit, I don't think this is *really* necessary, but let me know that I'm wrong.
=> Added functions to perform actions with the first minimized window.

CHANGES.md, XMonad/Prompt.hs
Background: I am trying to add some shortcuts for XPrompt, for example,
when doing `Ctrl-V`, text in my clipboard will be pasted into prompt. The
best way to do this is to use the function `insertString`, but I surprisingly
find that it is not exported.
The current work around is to use `setInput`, but it loses track of the cursor position.
```haskell
myPromptKeymap = M.union defaultXPKeymap $ M.fromList
[ ((controlMask, xK_v), setInput =<< liftIO getClipboard) 
]
```
As I have seen that `deleteString` is also exported, so I think there is no downside to
export this function.
=> Export XMonad.Prompt.insertString.

CHANGES.md, XMonad/Util/SessionStart.hs, xmonad-contrib.cabal
I added a `XMonad.Util.SessoinStart` module to include a way to check if we are currently starting the session, or restarting xmonad in the startupHook.
This is a more general approach than `spawnOnce` which e.g. allows to use `spawnOn`.
Currently this requires to manually set a flag in the ExtensibleState (at the end of startupHook). If this is moved to the core repository at some point, this can be done automatically when the state file is read.
- [✓] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
- [✓] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)
- [✓] I updated the `CHANGES.md` file
=> Add XMonad.Util.SessionStart

CHANGES.md, XMonad/Actions/Navigation2D.hs
Previously in #77 I wrote a very simple hybrid navigation strategy for Navigation2D, taking advantage of what was already written. It prioritised target windows found by lineNavigation over those found by centerNavigation, and due to relevant functions/constructors not being exposed by the module this wasn't able to be changed on the user end. This became a noticeable problem for me recently when I started using a layout with one window in a narrow vertical master pane and the rest of the screen in a grid, resulting in window configurations like the below:
In these cases lineNavigation—and hence hybridNavigation—move focus between the leftmost and rightmost windows, not able to reach the others. I don't use multiple screens so I can't confirm, but this may also be behind the comment …
=> Generalised hybridNavigation to hybridOf

CHANGES.md, XMonad/Prompt/Pass.hs
Adds a new function to spawn a pass prompt which will use `xdotool` to
type in a password, bypassing the clipboard. Also incorporate some shell
escapes to properly handle pass labels with spaces and special
characters in them.
=> Add facility for automatically typing passwords via XMonad.Prompt.Pass, and handle special characters in pass labels

CHANGES.md, XMonad/Prompt/Unicode.hs
I don't use Debian, and hardcoding the path doesn't seem great anyhow. Open to suggestions as to whether this is the best way to pass the file path around, or the argument order of `unicodePrompt`.
I also took out an `unsafePerformIO`, because it didn't seem necessary.
=> Make UnicodeData.txt path configurable, remove unsafePerformIO

CHANGES.md, XMonad/Layout/Gaps.hs
I added `ModifyGaps (GapSpec -> GapSpec)` to the `GapMessage` type so that arbitrary modifications can be made to gaps at runtime. I utilised that to implement and expose:
- `weakModifyGaps`, taking a simpler function of the form `Direction2D -> Int -> Int`
- `modifyGap`, taking a function of the form `Int -> Int` and a `Direction2D`
- `setGaps`, taking and instituting a `GapSpec`
- `setGap`, taking an `Int` and a `Direction2D`
Ideally I would also like to remove the `IncGap` and `DecGap` constructors and re-implement them as top-level functions `incGap` and `decGap` using `ModifyGaps`, but that would break people's configs.
Previously the closest thing to `sendMessage $ setGap n d` was `sendMessage (DecGap 9999 d) >> sendMessage (IncGap n d)`; an awful hack. Being able to set any or all …
=> Extended the sendMessage interface of X.L.Gaps to allow arbitrary modifications

CHANGES.md, XMonad/Actions/PhysicalScreens.hs, XMonad/Util/WorkspaceCompare.hs
Now when using getSortByXineramaPhysicalRule and all helper given by
Actions.PhysicalScreens the user have to provide a screen comparator that can
compare screen using their id or/and their coordinate.
behind them.
=> 157 allow user to customize screen ordering

CHANGES.md, XMonad/Prompt/AppendFile.hs
This change allows for transforming the string passed by a user before appending to a file.
This is my first Haskell code out into the wild. If there is anything to be improved I will be glad to do so.
I've kept the old example with date output as it hints other uses, but can remove it or change it if both the examples are overlapping too much.
The main question that appeared in my mind was if `String -> String` was enough (I imagine `String -> X String` would give greater flexibility), but my Haskell knowledge is pretty basic and I wanted to keep it simple. Any thoughts?
There are no tests for it (yet?). If this is good enough for merging and deserves testing I will open PR for them too.
=> Add appendFilePrompt' to allow transforming text before appending

CHANGES.md, XMonad/Actions/Navigation2D.hs
This time, a new navigation strategy from the ground up. It's intended to be used in the tiled layer with gapped layouts (those using modifiers from X.L.Spacing), and can be considered the extension of line navigation to the gapped case—which is to say: when unambiguous, `sideNavigation` will choose the same window as `lineNavigation` would have were the layout not gapped. A parameterised variant `sideNavigationWithBias` is also supplied. For precisely what its bias parameter does, I refer you to the comments in the generated documentation or source code.
The incompatibility of `lineNavigation` with gaps can be patched up by hybridising it with `centerNavigation`; and this is remarkably effective for how little additional code it required. However it's not ideal—both versions having some …
=> New sideNavigation strategy for X.A.Navigation2D

CHANGES.md, XMonad/Layout/MultiDishes.hs, xmonad-contrib.cabal
Behaves like Dishes, but allows configurable number windows within each stack.
I find Dishes the most useful layout for my development, but stacks take up a lot of horizontal space given their limited vertical size.  This allows for multiple windows to be placed inside the stacks so that new stacks don't take up more real estate than needed.
Probably a discussion point is whether this should or shouldn't live within the `Dishes` module, and I'm happy to write this anyway.  It seemed like the tendency was towards new module, so that's the path I took.
Using this example config:
```
import XMonad
import XMonad.Layout.MultiDishes
import XMonad.Layout.WindowNavigation
myLayout = windowNavigation
$ MultiDishes 2 4 (1/7)
|||MultiDishes 1 0 (1/4)
||| MultiDishes 1 3 (1/7)
main = xmonad $ def { …
```
=> Add a new layout MultiDishes

XMonad/Layout/Groups.hs
This is as per the work done in
http://lynnard.me/blog/2013/12/30/more-xmonad-goodies/, where the
functionality is explained in detail.
This also fixes #214. The original suggestion in that bug report is
not enough. Even if we export `gen` and `Uniq`, we would still have to
export the `Groups` type constructor. I thought it better to simply
allow the user to create a three-dimensional group instead.
behind them.
=> Add three-dimensional group layout

CHANGES.md, XMonad/Hooks/DynamicLog.hs
This commit adds `dzenWithFlags` function for users who wish to change the
command line arguments passed to the `dzen2` executable. The behaviour of `dzen` function is
kept the same. `dzen` function internally invokes `dzenWithFlags` with a fixed set of arguments.
I needed to increase the width of the dzen status bar to show all the workspaces that have
windows on them. I did not find a way to do this with the existing `dzen` function. This commit 
does minor refactoring to allow a way to pass user supplied flags to the underlying `dzen2` binary.
=> DynamicLog: add dzenWithFlags function

CHANGES.md, XMonad/Layout/Groups.hs
The `group3` addition I made in a previous commit enabled one to go so
far, but then quickly hit some walls due to non-exported symbols from
`XMonad.Layout.Groups`.
This commit removes `group3`, as it would hardly be useful to anybody,
and introduces a new `ModifyX` message that allows the modifying
function to return a `Groups` layout inside the `X` monad. Here's an
example on why this is useful:
Say you have a master layout with tabbed sub-layouts, and you have
terminal windows sprinkled around these sub-layouts. You now want to
gather all of them into a single tabbed sub-layout, effectively
implementing a "tabbed terminal" (or browser, or editor, etc). With
functionality like this, `XMonad` can become a unified multi-window
application manager: one does not need tabbed browsers, …
=> Add a `ModifyX` message to `Groups`

CHANGES.md, XMonad/Prompt/FuzzyMatch.hs, xmonad-contrib.cabal
Provides a predicate 'fuzzyMatch' that is much more lenient in matching
completions in XMonad.Prompt than the default prefix match.  Also provides
a function 'fuzzySort' that allows sorting the fuzzy matches by "how well"
they match.
Not sure why wasn't it accepted.
Discussion: https://markmail.org/thread/kgrybzqarqzqiige
=> + FuzzyMatch by @nzeh

CHANGES.md, XMonad/Util/Dzen.hs
Some fairly common options to `dzen2` are not yet wrapped in `XMonad.Util.Dzen`.
This pull request adds the following functions, meant to be used with `dzenConfig`:
* `fgColor` and `bgColor` to set foreground/background color
* `align` and `slaveAlign` to set text alignment (using the `Align` data type from `XMonad.Util.Font`)
* `lineCount` to enable the slave window and specify the number of lines it should contain
Rather trivial change, please check formatting/style since I don't often contribute Haskell.
=> Implement additional options for Dzen

CHANGES.md, XMonad/Config/Saegesser.hs, XMonad/Util/SpawnOnce.hs
Added `spawnOnOnce`, `spawnNOnOnce` and `spawnAndDoOnce` to `XMonad.Util.SpawnOnce`.
These functions combine the functionality of spawnOnce with spawnOn. That is they allow an application to be spawned and shifted to a particular workspace and also prevents the applications from being launched again by xmonad --restart.
spawnNOnOnce spawns an application n number of times on the given workspace. For example, my startup hook creates four terminal windows on my "xterms" workspace.
spawnAndDoOnce takes a ManageHook that is applied to the application after it starts. This is useful for combing multiple actions, for example, shift to a particular workspace and move the window down in the window stack.
Also, I'm a Haskell noob so if there is a better to accomplish this please me know.
- Sort …
=> Add spawnOnOnce and related functions.

CHANGES.md, XMonad/Hooks/DynamicLog.hs
Simple extensions of the pretty printer to differentiate between empty and non-empty visible workspaces. Analogical to the existing functionality for hidden workspaces. Particularly useful if some displays managed by xmonad are turned off temporarily.
The new 'ppVisibleNoWindows' function was wrapped in a Maybe data type. Its value dafaults to 'Nothing' and 'ppVisible' is used as fallback.
My TV is often turned off. Still I want to know if its workspace contains any windows, without having to switch workspaces.
=> Added pretty printer for empty visible workspaces (wrapped in Maybe)

CHANGES.md, XMonad/Layout/BinaryColumn.hs
This is similar to 'Column' layout with some differences.
- Add/remove windows keeps window bounds.
*(with `Column` all window frames re-size whenever windows are added or removed. I find it quite annoying).*
- Enforce minimum window size.
*(this means you never get a bunch of unrecognizable 1-3 high pixel windows - even if you have many windows open).*
- Scaling the master window down causes an evenly spaced grid.
- Negative scale can be used to increase the size of the last window
instead of the master window.
Using xmonad with monitors in portrait mode is well suited to a column grid.
There are however some constraints.
Not that this is different enough from the Column layout that I don't think it can be a drop in replacement. Scale works differently window size minimum has been added. …
=> Add BinaryColumn layout

XMonad/Prompt/FuzzyMatch.hs
Fix #249. Since the change that caused it is so recent I assume the fix doesn't need an entry in the changelog.
=> X.P.FuzzyMatch: Relocate imports so that haddock generation succeeds.

CHANGES.md, XMonad/Layout/Fullscreen.hs
There's no reason to return a rectangle for any window that is totally
obscured by a full-screen window, and not doing so has the nice property that
when hidden windows' borders overlap with a full-screen window's, the user
will not be confused by overlapping partially-drawn borders. It also makes the
Fullscreen modifiers combine much better with smartBorders.
- xmonad-testing has no configs with a Fullscreen layout; I have tested on my own system and this works as described.
=> Fullscreen.hs: don't lay out windows obscured by fullscreen

CHANGES.md, XMonad/Layout/StateFull.hs, XMonad/Util/Stack.hs, xmonad-contrib.cabal
_TL;DR: added a module providing a version of Full that doesn't misbehave when you focus a float._
Due to the `Stack` data type with which we pass windows to layouts, we're forced to claim that one of the windows being tiled has focus. Layouts like `Full` and `Accordion` depend strongly upon the correctness of this information, and misbehave when lied to (because a float has focus, or because the layout is child to some parent layout that hasn't given it the focus).
This module implements a layout transformer `FocusTracking` that just holds onto the most recent true focus it's seen and passes the information down to the transformed layout. This means the layout remembers where it was when it loses focus, and doesn't suddenly go jumping off to some other window. `StateFull` (the …
=> StateFull: Fixing Full (and other layouts we lie to)

CHANGES.md, XMonad/Hooks/RefocusLast.hs, xmonad-contrib.cabal
Added the X.H.RefocusLast module, which provides hooks and actions enabling automatic refocusing of the previous window upon loss of the current.
Broadly, the motivation is just that this is another valid refocusing strategy which might be considered more intuitive, especially when using directional navigation. More specifically, it also makes tab groups behave more like real windows: under native refocusing if you kill/lose a window and are refocused onto a tab group, then rather than the tab that was active, you find yourself at the head of the group. That doesn't happen with this strategy.
Edit: don't merge this PR yet; I just realised that occasionally the event hook can cause you to jump workspaces unintentionally (when it refocuses a window that's been shifted). I'll correct the …
=> RefocusLast

CHANGES.md, XMonad/Actions/DynamicWorkspaceOrder.hs
Allows it to be used with X.A.DynamicWorkspaces where a user is able to rename and remove workspaces.
=> Added two actions to X.A.DynamicWorkspaceOrder

xmonad-contrib.cabal
Allow build of xmonad-contrib with X11-1.9
=> Allow build with X11-1.9

CHANGES.md, XMonad/Layout/NoBorders.hs
The layout now maintains a list of windows that never have borders, and a list of windows that always have borders. Use `BorderMessage` to manage these lists and the accompanying event hook (`borderEventHook`) to remove destroyed windows from them. Also provides the `hasBorder` manage hook.
Two new conditions have been added to `Ambiguity`: `OnlyLayoutFloat` and `OnlyLayoutFloatBelow`; `OnlyFloat` was renamed to `OnlyScreenFloat`. See the documentation for more information.
=> Border Control

CHANGES.md, XMonad/Actions/SwapPromote.hs, xmonad-contrib.cabal
Module for tracking master window history per workspace, and associated functions for manipulating the stack using such history.
=> Swap Promote

XMonad/Util/Themes.hs
Adds darkTheme to X.U.Themes.
Let me know if CHANGES should be updated for a small patch like this. I didn't see any update notes for any of the existing themes, so I'm assuming it shouldn't be.
=> X.U.Themes: Add darkTheme

CHANGES.md, XMonad/Layout/MultiToggle/TabBarDecoration.hs, xmonad-contrib.cabal
Add the X.L.MultiToggle.TabBarDecoration module
Provides a simple transformer for use with "XMonad.Layout.MultiToggle" to dynamically toggle "XMonad.Layout.TabBarDecoration".
=> Add the X.L.MultiToggle.TabBarDecoration module

CHANGES.md, XMonad/Config/Azerty.hs
Add support for belgian keyboards in XMonad.Config.Azerty
=> add support for belgian keyboards in XMonad.Config.Azerty

CHANGES.md, XMonad/Actions/MessageFeedback.hs
- Follow the naming conventions of `XMonad.Operations`. Functions returning
`X ()` are named regularly (previously these ended in underscore) while
those returning `X Bool` are suffixed with an uppercase 'B'.
- Provide all `X Bool` and `SomeMessage` variations for `sendMessage` and
`sendMessageWithNoRefresh`, not just `sendMessageWithNoRefreshToCurrent`
(renamed from `send`).
- The new `tryInOrderB` and `tryMessageB` functions accept a parameter of
type `SomeMessage -> X Bool`, which means you are no longer constrained
to the behavior of the `sendMessageWithNoRefreshToCurrent` dispatcher.
- The `send*Messages*` family of funtions allows for sequencing arbitrary
sets of messages with minimal refresh. It makes little sense for these
functions to support custom message dispatchers.
- Remain …
=> 'XMonad.Actions.MessageFeedback': standardize

XMonad/Layout/Spacing.hs
See #260 (first version) for a full description. From the commit messages:
* All the backwards-compatibility functions now accept `Int` rather than `Integer`: `spacing`, `spacingWithEdge`, `smartSpacing`, `smartSpacingWithEdge`, `setSpacing`, and `incSpacing`. Work done by @LSLeary.
* Introduce the new functions `setScreenWindowSpacing`, `incScreenWindowSpacing`, `decScreenWindowSpacing`. Unlike their original `setSpacing`, `incSpacing` counterparts, these refresh no more than once. Requires `sendMessages` from PR #261 of `XMonad.Actions.MessageFeedback`. Suggestion by @LSLeary and implemented so any combination of messages can be sent without triggering unnecessary refreshes.
* Reintroduce the original 'ModifySpacing' type and constructor as deprecated; the new 'ModifySpacing' type was …
=> reSpaced: Compatibility v2

.travis.yml, XMonad/Actions/SwapPromote.hs, XMonad/Layout/NoBorders.hs, XMonad/Layout/Spacing.hs, XMonad/Layout/StateFull.hs, XMonad/Util/Stack.hs, xmonad-contrib.cabal
Travis CI has been broken for way too long, so I had a go at it. Fair warning: I don't actually know what I'm doing, or what half the script is doing for that matter.
There's some statefulness in the setup that has contributed to random failures, so it's hard to know whether my changes have actually fixed that issue. It looked like the problem was `cabal configure [...]` failing with missing dependencies when the "cabal build-cache HIT" case of an earlier conditional meant that `cabal install --only-dependencies [...]` did not run, so I've moved that command out of the conditional. Presumably it shouldn't need to be run in that case, but it seems it does. I imagine there is a better fix; yell out if you know.
In the process of troubleshooting that, I saw what changes needed to be made for …
=> Travis CI, and (dropping?) GHC 7.6/7.8 compatability

XMonad/Actions/PhysicalScreens.hs
behind them.
The documentation has a typo so copying and pasting the example does not work.
- [-] I updated the `CHANGES.md` file
=> Typo in PhysicalScreens.hs

XMonad/Layout/Fullscreen.hs
The 'FullscreenFull' layout modifier hides all windows fully covered by the fullscreen area, even when no fullscreen windows are present. Fix this, closing #278. Also switch to 'X.U.Rectangle'.
Note: I haven't tested this.
=> X.L.Fullscreen: 'FullscreenFull' hides all windows

CHANGES.md, XMonad/Util/ExtensibleState.hs, XMonad/Util/PureX.hs, xmonad-contrib.cabal
> Unlike the opaque `IO` actions that `X` actions can wrap, regular reads from
the `XConf` and modifications to the `XState` are fundamentally pure—contrary
to the current treatment of such actions in most xmonad code. Pure
modifications to the `WindowSet` can be readily composed, but due to the
need for those modifications to be properly handled by `windows`, other pure
changes to the `XState` cannot be interleaved with those changes to the
`WindowSet` without superfluous refreshes, hence breaking composability.
This module aims to rectify that situation by drawing attention to it and
providing `PureX`: a pure type with the same monadic interface to state as
`X`. The `XLike` typeclass enables writing actions generic over the two
monads; if pure, existing `X` actions can be generalised …
=> Added the X.U.PureX module and generalised X.U.ExtensibleState type signatures

CHANGES.md, XMonad/Prompt.hs, XMonad/Prompt/FuzzyMatch.hs
Extend `XPConfig` in `XMonad.Prompt` to provide a `sorter` which is useful for example in `XMonad.Prompt.FuzzyMatch` via `fuzzySort`.
=> XMonad.Prompt sorter for FuzzyMatch

CHANGES.md, XMonad/Prompt/Pass.hs
Add new function passEditPrompt to Xmonad.Prompt.Pass
=> Add passEditPrompt to Xmonad.Prompt.Pass

CHANGES.md, XMonad/Prompt.hs
When tabbing through the prompt list of completions, if the list of completions does not fit due to `maxComplRows`, without this fix an exception would be thrown.  I am not certain why, but this exception occurs due to a pattern mismatch at https://github.com/mgsloan/xmonad-contrib/blob/dda242a4597c1ed0fa895a10b9296dcc709f4937/XMonad/Prompt.hs#L919
However, the root cause appears to be in the `nextComplIndex` function.  The problem is that it was assuming that dividing the total item count by the number of rows would yield the number of columns.  This did not hold when the number of rows was being limited.
=> Fix XMonad.Prompt wraparound when maxComplRows not Nothing #217

CHANGES.md, XMonad/Prompt.hs
Also deduplicates some code shared by mkXPromptWithReturn and
mkXPromptWithModes.
See issue #180.  I noticed 3 obvious places where Prompt can benefit from the bracket pattern, and this PR implements that.  This should help avoid failure modes like the keyboard being grabbed forever, or leaving a prompt window open forever.
=> Use bracket pattern in XMonad.Prompt

CHANGES.md, XMonad/Actions/DynamicProjects.hs
This makes the input directory read from the prompt in `DynamicProjects` absolute wrt the current directory.
Without this patch, the directory set by the prompt is treated like a relative directory. This means that when you switch from a project with directory `foo` into a project with directory `bar`, xmonad actually
tries to `cd` into `foo/bar`, instead of `~/bar` as expected.
=> Use absolute paths in DynamicProjects

CHANGES.md, XMonad/Actions/DynamicWorkspaceOrder.hs
I added an action that allows me to invoke `withNthWorkspace` while at the same time modify the list of workspace tags received from the dynamic order. This way I could avoid `M-3`, for example, from taking me to the `NSP` workspace that `X.A.NamedScratchpad` creates.
For lack of a better name, I appended `'`.
=> X.A.DynamicWorkspaceOrder: add transformation-aware withNthWorkspace

XMonad/Hooks/EwmhDesktops.hs
Previously the `EwmhDesktops` was painfully naive, sending property updates every time the log hook was invoked, even if none of the affected properties actually changed in value. This hurts significantly since it can cause a slew of unnecessary wakeups. Here we refactor the EWMH implementation to cache the current property value and only send updates if the value actually changes.
Previously `xmonad` was consistently sitting at 5% CPU usage when I was using my system (and `taffybar` even higher as it redraws its entire window when desktop names change). With this patch it sites at < 1%, exactly where it should be.
Fixes #227.
=> Wakeup reduction in EwmhDesktops

CHANGES.md, XMonad/Actions/GroupNavigation.hs
Adding `isOnAnyVisibleWS` to satisfy #293. The function itself has been tested as part of my `xmonad.hs`.
=> Add isOnAnyVisibleWS function to Actions.GroupNavigation

CHANGES.md, XMonad/Util/ExclusiveScratchpads.hs, XMonad/Util/MutexScratchpads.hs, xmonad-contrib.cabal
This is a new module that extends the idea of NamedScratchpads: For example, a lot of the time I just need a scratchpad for doing a quick calculation (eg. a `ghci` shell) after that I might use another scratchpad (eg. `octave` shell), with this module the workspace doesn't get polluted since I can group related scratchpads that share the same position on the workspace.
I use it a lot and thought it might be worth being shared, note that I'm not sure if this meets all your standards as this is my first (real) contribution. I tested the module for about a week now with my current setup and it works the way it is supposed to, I also I tested it with `xmonad-testing`, so I think it should do fine.
=> add new module X.U.ExclusiveScratchpads

CHANGES.md, XMonad/Util/Themes.hs
Add themes to match Adwaita and Adwaita-dark GTK themes.
=> XMonad.Util.Themes: Add adwaitaTheme and adwaitaDarkTheme

CHANGES.md, XMonad/Prompt/Pass.hs
Support OTP type password in XMonad.Prompt.Pass. This require pass-otp (https://github.com/tadfisher/pass-otp) has been setup in the running machine.
=> Support OTP in XMonad.Prompt.Pass

CHANGES.md, XMonad/Hooks/WallpaperSetter.hs
Preserve the aspect ratio of wallpapers that xmonad sets. When previous versions would distort images to fit the screen size, it will now find a best fit by cropping instead.
I don't understand the imagemagick command invocation very well, so this was put together through trial and error. I've tested it with good results though, in a dual-head setup where each monitor has a different aspect ratio (1920x1080 and 1920x1200).
=> Hooks.WallpaperSetter: Preserve aspect ratio while scaling images

XMonad/Doc/Extending.hs, XMonad/Layout/LayoutCombinators.hs, XMonad/Prompt/FuzzyMatch.hs, XMonad/Util/Image.hs
Fixes a few internal links that incorrectly referred to module paths starting with `Xmonad` (with a lowercase m). For example, the first link from the top here: https://hackage.haskell.org/package/xmonad-contrib-0.15/docs/XMonad-Util-Image.html
=> Fix broken internal Haddock links

CHANGES.md, XMonad/Hooks/RefocusLast.hs, xmonad-contrib.cabal
Rebased (and fixed) version of [!265](https://github.com/xmonad/xmonad-contrib/pull/265)
That PR seems to be stalled and the author seems to be unreachable. I've thoroughly tested this functionnality on nixos.
=> RefocusLast Module

CHANGES.md, XMonad/Prompt/FuzzyMatch.hs
Make fuzzy sort show shorter strings first. For example, `firefox-developer-edition` won't be shown before `firefox` and we will be able to choose the first one typing additional `d` letter.
=> Make fuzzy sort show shorter strings first

CHANGES.md, XMonad/Layout/BinarySpacePartition.hs
This adds a new `SplitShiftDirectional` message to `BinarySpacePartition` layout.
The message allows users to easily move a window around by splitting either its left neighbor (`SplitShift Prev`) or right neighbor (`SplitShift Next`).
This functionality is similar to the existing `SelectNode` / `MoveNode` however, the usage is much easier and efficient for users if they want to quickly move neighboring windows with just a stroke of a key.
The changes introduced here do not interfere with any existing functionality.
=> Add SplitShiftDirectional message into BinarySpacePartition layout.

CHANGES.md, XMonad/Layout/Decoration.hs
Make decoration border width configurable. Forked this so I could use it for my config (high res laptop screen makes >1 pixel decoration borders desirable), thought I'd contribute back upstream (because xmonad is amazing, thanks for all your work!). No modifications to core logic, should be fairly quick to review.
no, but I've tested it with my personal stack-built xmonad config and it works fine. Can post screenshots on request.
=> Add configurable border width fields to XMonad.Layout.Decoration.Theme

CHANGES.md, XMonad/Layout/Tabbed.hs
The leftTabbed and rightTabbed Layouts of XMonad.Layout.Tabbed are stretching their tabs over the whole screen height which makes the tab-text disappear.
This change will make the tabs have a fixed height (according to decoHeight). Similar to the TreeStyleTab Addon of Firefox.
=> Improved tabbedRight and tabbedLeft in XMonad.Layout.Tabbed

XMonad/Actions/Search.hs
Fixing simple spelling mistake in example section of XMonad/Actions/Search.hs
hoohle -> hoogle
=> XMonad/Actions/Search: fix spelling mistake

.gitignore, CHANGES.md, XMonad/Layout/TallMastersCombo.hs, xmonad-contrib.cabal
This is a layout combinator that inherits the similar behaviors of the 'Tall' layout, and can be applied to merge any two sublayouts. Each sublayouts can be a 'Choose' composed layout, and the message FocusedNextLayout can switch to the next layout in the focused pane.
Moreover, it supports two master windows, a main master window, and a sub master window, which is the first window in the second pane. This combinator also works well with the Tabbed layout. Using the SwitchOrientation message, it can mirror the layout structures without affects the tabbed decorations. 
- [ x] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
- [x ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)
- [ x] I updated the `CHANGES.md` …
=> A New Layout Combinator: TallMastersCombo

CHANGES.md, XMonad/Actions/WindowBringer.hs, XMonad/Prompt/Window.hs, XMonad/Util/NamedWindows.hs
This module allows you to associate the application name of windows with them. I have been using this [module](https://github.com/psibi/dotfiles/blob/30364f1b54a1c093b6eca14e2a263a070627d29a/.xmonad/xmonad.hs#L134) for more than a month and haven't see any problems with it.
=> Added 'allApplications' to XMonad.Prompt.Window

CHANGES.md, XMonad/Actions/PerWindowKeys.hs, xmonad-contrib.cabal
Allows one to shortcut actions that are performed based on queries.
Some XMonad users might want keybinds to perform different actions based on which window they are currently focusing. This adds two functions that allow them to perform either all actions for which a `Query Bool` holds true, or the first action for which that applies. One could also sequence the two for more complex behavior.
=> Added module X.A.PerWindowKeys

XMonad/Actions/Launcher.hs, XMonad/Actions/MouseResize.hs, XMonad/Actions/WindowNavigation.hs, XMonad/Actions/WorkspaceNames.hs, XMonad/Hooks/EwmhDesktops.hs, XMonad/Hooks/ManageDocks.hs, XMonad/Hooks/PositionStoreHooks.hs, XMonad/Hooks/UrgencyHook.hs, XMonad/Layout/AutoMaster.hs, XMonad/Layout/Decoration.hs, XMonad/Layout/DragPane.hs, XMonad/Layout/Master.hs, XMonad/Layout/PositionStoreFloat.hs, XMonad/Prompt.hs, XMonad/Util/NamedScratchpad.hs
This pull request is part of an ongoing effort to remove legacy/redundant code from xmonad-contrib. 
1. Removes all redundant `do`'s (places where `do` is followed by just a single line), as per @byorgey's request in #320. 
I did not think this necessary
=> Remove redundant do's

CHANGES.md
These PRs were merged after the 0.16 release but added changelog entries
to the 0.16 release:
- https://github.com/xmonad/xmonad-contrib/pull/310
- https://github.com/xmonad/xmonad-contrib/pull/311
- https://github.com/xmonad/xmonad-contrib/pull/315
Move them to an unreleased version instead.
=> CHANGES: Move stuff merged post-0.16 upwards

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs, XMonad/Hooks/FadeInactive.hs, XMonad/Hooks/SetWMName.hs, XMonad/Hooks/UrgencyHook.hs, XMonad/Layout/Fullscreen.hs, XMonad/Util/RemoteWindows.hs
Provide a way to advertise _NET_WM_STATE_FULLSCREEN in _NET_SUPPORTED.
I had this hardcoded for a while but read the mpv manpage recently:
```
Specifically, yes will force use of NetWM fullscreen support, even
if not advertised by the WM. This can be useful for WMs that are
broken on purpose, like XMonad. (XMonad supposedly doesn't advertise
fullscreen support, because Flash uses it. Apparently, applications
which want to use fullscreen anyway are supposed to either ignore
the NetWM support hints, or provide a workaround. Shame on XMonad
for deliberately breaking X protocols (as if X isn't bad enough
already).
```
I'm not sure Flash is still a good reason these days to not advertise
fullscreen support yet still handle it and look like idiots while doing so.
(And if anyone thinks it is a …
=> X.H.EwmhDesktops: optionally advertise fullscreen support in _NET_SUPPORTED

XMonad/Prompt/Shell.hs
`tail` is a partial function and should be avoided where practical. In this case, it's being used to create a function exactly equivalent to `drop 1`, so just remove that function and use that instead.
=> Use `drop 1` instead of reimplementing it in terms of `tail`

CHANGES.md, XMonad/Actions/DynamicProjects.hs, XMonad/Actions/DynamicWorkspaceGroups.hs, XMonad/Actions/TagWindows.hs, XMonad/Prompt.hs, XMonad/Prompt/ConfirmPrompt.hs, XMonad/Prompt/Email.hs, XMonad/Prompt/Layout.hs, XMonad/Prompt/Man.hs, XMonad/Prompt/Ssh.hs, XMonad/Prompt/Theme.hs, XMonad/Prompt/Workspace.hs, XMonad/Prompt/XMonad.hs
Prompts based on `mkComplFunList` and `mkComplFunList'` were not taking into account the `searchPredicate` funtion from `XPConfig`. This was rather confusing.
We fix it by passing `XPConfig` to these functions; although this is strictly more than they need, it makes the breaking change very easy to fix and is also more future-proof.
I'm using the amended `workspacePrompt` on my own config. The rest of the changes were type-directed.
=> Prompt: Use searchPredicate in more cases

CHANGES.md, XMonad/Layout/BoringWindows.hs
To mark the currently focused window boring on all layouts,
when using XMonad.Actions.CopyWindow.
=> XMonad.Layout.BoringWindows: add markBoringEverywhere

CHANGES.md, XMonad/Layout/MouseResizableTile.hs
When we calculate draggerGeometry, we should use the current width of
the border (if available), rather than the initial borderWidth.
Otherwise, we get the wrong width if the user has changed the borderWidth since XMonad started.
=> X.L.MouseResizableTile borderWidth via focused win

CHANGES.md, XMonad/Actions/Search.hs
Adds a new function, `promptSearchBrowser'`, which behaves almost exactly like `promptSearchBrowser`, the only difference being that the former only suggests previous searches of the selected search engine.
=> X.A.Search: Add promptSearchBrowser'

CHANGES.md, XMonad/Actions/CycleRecentWS.hs
When cycling through recent workspaces, it's nice to able to ignore those that are empty. I added `cycleRecentNonEmptyWS` to support that.
Users may have their own constraints they'd like to filter by, so a `recentWS` function has been exported and can be used to apply a user-provided predicate to the list of workspaces considered.
In addition to cycling, which updates the recency list only after a modifier key is released, it's useful to have a keybinding that toggles between the current and most recent workspace, with repeated key presses toggling back and forth even if no modifier key is released. The `toggleRecentWS` and `toggleRecentNonEmptyWS` functions provide this ability.
For context, I use these in my xmonad.hs as follows:
```haskell
, ((mod1Mask, xK_l     ), …
```
=> CycleRecentWS: add non-empty and toggle functionality

CHANGES.md, XMonad/Prompt/Window.hs
I use it to add windows to the current tab group like so:
```
bringAsTabbed :: WindowPrompt
bringAsTabbed = WithWindow "Bring to tab group: " $ \w -> do
cur <- getFocused
windows $ \ss -> W.shiftWin (W.currentTag ss) w ss
maybe (pure ()) (sendMessage . Migrate w) cur
```
=> Allow WindowPrompt to execute arbitrary actions with the window

CHANGES.md, XMonad/Util/Run.hs
The current handle returned by `spawnPipe` doesn't have any encoding
and it uses the function fdToHandle which returns a Binary
Handle. When spawnPipe is used with a program like xmobar, this can
easily lead to errors:
```
λ> h <- spawnPipe "xmobar"
λ> hPutStrLn h
"\35753Haskell\25110\32773Ghci\33021\27491\30830\26174\31034\27721\23383\24182\19988\35835\21462\27721\23383\21629\21517\30340\25991\26723"
<stdin>: hGetLine: invalid argument (invalid byte sequence)
```
One workaround is to use `hSetEncoding`. But from
reading GHC's source code - the entire Handle and write operations
seems stateful. So doing something like hPutStr and hSetEncoding can
theoretically lead to an undefined state as the first write will use
latin encoding and the second write will use the new encoding. More
details …
=> Add new variants of spawnPipe functions with encoding support

CHANGES.md, XMonad/Hooks/ManageHelpers.hs
Added a new manage hook `doSink`, which does the opposite of `doFloat`.
It seemed like a gap in the available configuration functions that was easy to fill.
=> Add a doSink manage hook

CHANGES.md, XMonad/Layout/Hidden.hs
Some users like to include type signatures in their configuration. (I am one such user.)
The `HiddenWindows` type constructor was not exported, making it impossible to write a type signature when using `hiddenWindows`.
With this change, a user can write an xmonad.hs like:
```haskell
import XMonad
import XMonad.Layout.Hidden (HiddenWindows, hiddenWindows)
import XMonad.Layout.LayoutModifier
myLayout :: ModifiedLayout
HiddenWindows
(Choose Tall (Choose (Mirror Tall) Full))
Window
myLayout = hiddenWindows $ layoutHook def
main :: IO ()
main = xmonad def { layoutHook = myLayout }
```
=> HiddenWindows: export type constructor

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Layout/ResizableThreeColumns.hs, xmonad-contrib.cabal
Adds another layout.
I've added `XMonad.Layout.ResizableThreeColumns`, which is the same layout as `ThreeColumns` but allows the slave window heights to be resized, just as was implemented for the `ResizableTall` layout.
=> Add ResizableThreeColumns layout

CHANGES.md, XMonad/Util/Run.hs
Add a function named spawnPipeWithNoEncoding for people who might want
to use binary handles.
Fixes https://github.com/xmonad/xmonad-contrib/issues/338
=> Make spawnPipe to use system's locale encoding

CHANGES.md, XMonad/Util/DynamicScratchpads.hs, xmonad-contrib.cabal
This is a module I built for myself, and I think it could potentially be interesting for others, too. It allows you to bind a key to make any window a scratchpad that behaves just like `XMonad.Util.NamedScratchpad`. You can then bind another key to spawn or hide that scratchpad.
So, with the following key bindings, you could hit `mod+Shift+A` to declare the focused window as a scratchpad. You can then show or hide the window with `mod+A`.
```haskell
, ((modm .|. shiftMask, xK_a), withFocused $ makeDynamicSP "dyn1")
, ((modm              , xK_a), spawnDynamicSP "dyn1")
```
=> X.U.DynamicScratchpads: Make any window a scratchpad

CHANGES.md, XMonad/Actions/TiledWindowDragging.hs, xmonad-contrib.cabal
This PR adds a new action that allows dragging windows in tiled mode, similar to the way BSPWM does it. It makes use of DraggingVisualizer to display the dragging action.
=> add new XMonad.Actions.TiledWindowDragging module

.github/PULL_REQUEST_TEMPLATE.md
This PR adds a new checkbox to the PR checklist, asking the contributor to document any new modules they added in `XMonad.Doc.Extending`.
=> Add XMonad.Doc.Extending to PR-checklist

XMonad/Layout/Magnifier.hs
It's useful to wrap layouts with `magnifierOff` and use Magnifier in cases when you needed to zoom window, but when you zoom window it makes sense to show it in max size without using `MagnifyMore` which is layout specific. We have `maximizeVertical` which work in a similar way but it uses only vertical space and ignores horizontal
=> Add maxMagnifierOff to Magnifier layout

CHANGES.md, XMonad/Util/NamedScratchpad.hs
This PR adds more customizability to how scratchpads are initially started in `XMonad.Util.NamedScratchpad`, by adding two new exported functions:
- `customRunNamedScratchpadAction`
(provides the option to customize the `X ()` action the scratchpad is launched by) 
- `spawnHereNamedScratchpadAction`
(uses `XMonad.Actions.SpawnOn.spawnHere` to initially start the scratchpad on the workspace it was launched on)
=> Make XMonad.Util.NamedScratchpad more flexible

CHANGES.md, XMonad/Layout/Hidden.hs
This PR adds the `restoreHiddenWindow` function add the `PopSpecificHiddenWindow` message to `XMonad.Layout.Hidden`, allowing the user to request restoring a specific window.
=> Add restoreHiddenWindow function to XMonad.Layout.Hidden

CHANGES.md, XMonad/Prompt/Zsh.hs, xmonad-contrib.cabal
Add a prompt mode similar to `XMonad.Prompt.Shell` that uses zsh completions.
=> Add XMonad.Prompt.Zsh

XMonad/Util/EZConfig.hs
Exports parsers in `XMonad.Util.EZConfig`
See #359 
I also included `readKeySequence`, so you don't have to bother with `ReadP` if you need the top-level.
=> Export EZConfig parsers

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Hooks/WindowSwallowing.hs, xmonad-contrib.cabal
This PR adds a handleEventHook that implements DWM style window swallowing.
It allows you to configure certain applications like terminals, file explorers, etc, to be "swallowed" when opening another window from within them.
Once the child window closes, the parent is restored again.
=> Add XMonad.Hooks.WindowSwallowing

CHANGES.md, XMonad/Util/EZConfig.hs
XF86Bluetooth is the keysym sent by function+F10 on my P1.  xev generates this:
```
state 0x0, keycode 245 (keysym 0x1008ff94, XF86Bluetooth), same_screen YES,
```
Unfortunately XMonad still builds even when the keysyms don't exist, so this was nontrivial to diagnose for an outsider :)
That repo no longer works; see https://github.com/xmonad/xmonad-testing/issues/15
=> EZConfig: Learn about XF86Bluetooth

CHANGES.md, XMonad/Hooks/ManageDocks.hs, XMonad/Hooks/ManageHelpers.hs
Export the constructor for the AvoidStruts layout modifier. I have a newtype wrapper on AvoidStruts in my config file to alter some of the behavior of AvoidStruts, and currently I have no option but to attempt to mirror the internals of AvoidStruts myself.
=> Export AvoidStruts constructor and doSink

xmonad-contrib.cabal
They are not needed on newer GHC.
=> Depend on semigroups only on GHC < 8.0

CHANGES.md, XMonad/Hooks/DynamicLog.hs
My first code contributed (ever) to an open-source project! 
The function wraps the given strings in a box with a configurable border. Practically a one-liner. I needed this utility while playing around with xmobar, and there was very little documentation on how to configure borders and how to use them, so this should provide some help in that regard.
=> Added xmobarBorder utility function to add borders to strings

CHANGES.md, XMonad/Layout/Minimize.hs
Some users like to include type signatures in their configuration. (I am one such user.)
The `Minimize` type constructor was not exported, making it impossible to write a type signature when using `minimize`.
With this change, a user can write an xmonad.hs like:
```haskell
import XMonad
import XMonad.Layout.Minimize (Minimize, minimize)
import XMonad.Layout.LayoutModifier
myLayout :: ModifiedLayout
Minimize
(Choose Tall (Choose (Mirror Tall) Full))
Window
myLayout = minimize $ layoutHook def
main :: IO ()
main = xmonad def { layoutHook = myLayout }
```
=> Minimize: export type constructor

CHANGES.md, XMonad/Actions/Sift.hs, xmonad-contrib.cabal
When `swapUp`/`swapDown` wrap around the top/bottom of the stack, they rotate the entire stack rather than swapping position with their (wrapped) neighbor. Provide an alternative pair of functions, `siftUp`/`siftDown`, that exchange the windows at either end of the stack when wrapping. Non-wrapping cases behave identically to swaps.
For example, with focus on the master (_A_),
```
┌─────┬─────┐           ┌─────┬─────┐
│     │  B  │           │     │  C  │
│ *A* ├─────┤ swapUp -> │  B  ├─────┤
│     │  C  │           │     │ *A* │
└─────┴─────┘           └─────┴─────┘
┌─────┬─────┐           ┌─────┬─────┐
│     │  B  │           │     │  B  │
│ *A* ├─────┤ siftUp -> │  C  ├─────┤
│     │  C  │           │     │ *A* │
└─────┴─────┘           └─────┴─────┘
```
Related: …
=> XMonad.Actions.Sift

CHANGES.md, XMonad/Layout/BoringWindows.hs
Add boring-aware versions of the `siftUp` and `siftDown` functions. Since these actions never affect the position of boring windows, they work well with layouts that decide which windows are visible/hidden based on stack position, such as LimitWindows.
=> BoringWindows: siftUp, siftDown

XMonad/Actions/TreeSelect.hs
The config values `ts_originX` and `ts_originY` were not behaving like documented. They weren't doing anything at all.
This should fix that.
=> TreeSelect: Resolve issue #362 with origin offset being ignored

CHANGES.md, XMonad/Hooks/DynamicLog.hs
The existing `statusBar` function accepts a `PP` (pretty printing options) argument to incorporate in the `logHook` it configures. It's not possible to inject dynamically-modified printing options, like `workspaceNamesPP`, of type `X PP`, into this, so users are forced to recreate their own version of `statusBar`, which is pretty involved.
Add a `statusBar'` function that accepts an argument of type `X PP` to solve this issue.
Example usage:
```haskell
main = xmonad =<< statusBar' "xmobar" (workspaceNamesPP xmobarPP) toggleStrutsKey conf
```
=> Add statusBar' to support dynamic pretty printing modifiers

CHANGES.md, XMonad/Actions/RotateSome.hs, tests/RotateSome.hs, xmonad-contrib.cabal
When using a layout that determines window visibility based on stack position (e.g. `XMonad.Layout.LimitWindows`), it's nice to be able to replace a visible window with one that was hidden, without affecting other visible windows.
Add `surfaceNext` and `surfacePrev`, which treat the focused window and any hidden windows as a ring that can be rotated through the focused position.
More generally, expose a pure function, `rotateSome`, for rotating some elements around a stack while keeping others anchored in place.
=> RotateSome

CHANGES.md, XMonad/Actions/DynamicProjects.hs, XMonad/Layout/WorkspaceDir.hs, XMonad/Prompt.hs, XMonad/Prompt/Directory.hs, XMonad/Prompt/Shell.hs
Directory/file prompt completions are currently case-sensitive. Provide a way to configure case-insensitive completion.
This is achieved by setting the readline `completion-ignore-case` variable prior to generating completions, e.g.
```sh
bind 'set completion-ignore-case on'
compgen -A directory -- foobar
```
=> Allow case-insensitive shell prompt completion

xmonad-contrib.cabal
XMonad.Util.ClickableWorkspaces was added in #364 but never listed as an exposed module in xmonad-contrib.cabal, so any attempt to use it resulted in a compilation error.
Fix this by adding it to the list of exposed modules .
=> Add ClickableWorkspaces to exposed modules

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Prompt/FuzzyMatch.hs, XMonad/Prompt/Unicode.hs
`typeUnicodePrompt` hasn't worked for some time now, and even before it was kind of buggy. I determined this was caused by `runProcessWithInput` blocking on the prompt, so `xdotool` targets that instead of the active window. This is fixed by using `spawnPipe` instead.
It was also doing its own thing for searching for Unicode characters rather than respecting `XPConfig`, so I've fixed that too. I noticed that I was getting crashes when using `fuzzySort` from XMonad.Prompt.FuzzyMatch, and determined that the cause of the issue is:
```
Prelude.minimum: empty list
```
caused by XMonad.Prompt.Unicode generating a list of completions for a given input which contains some strings which are not necessarily supersequences of the input.
For instance, there is a character that is described by `DIGIT …
=> Fixes for XMonad.Prompt.Unicode

CHANGES.md, XMonad/Layout/VoidBorders.hs, xmonad-contrib.cabal
This module contains a modifier that simply sets X11 window border width
to 0 for every window in the layout it modifies. No efforts are made to
bring the border back, which can be annoying if windows are moved to a
different workspace, but it prevents the "border flash" you get with
XMonad.Layout.NoBorders.
=> add XMonad.Layout.VoidBorders

CHANGES.md, XMonad/Config/Desktop.hs, XMonad/Config/Example.hs, XMonad/Hooks/EwmhDesktops.hs, XMonad/Hooks/Focus.hs, XMonad/Hooks/ManageHelpers.hs, XMonad/Hooks/SetWMName.hs, xmonad-contrib.cabal
Resubmit #128 with changes requested in #162 .
@pjones , @geekosaur  Please, test and review.
@SirBoonami , @unclechu Please, try updated version. Now `logHook` (instead of `manageHook`) runs for activated window. Thus, if you use this module for managing focus _only_ for activated windows, you need to add `FocusHook` to your `logHook`. E.g.
logHook = activateLogHook activateSwitchWs
If you use `FocusHook` for managing focus for _both_ new and activated windows, you need to add it to _both_. Either create two different `FocusHook`-s, e.g.:
let newFh :: ManageHook
newFh = manageFocus newFocusHook
acFh :: X ()
acFh = activateLogHook (manageFocus activateFocusHook)
xcf = ewmh $ def
{ manageHook   = newFh <+> manageHook def
, logHook      = acFh  <+> logHook def
}
or (as was before) use the …
=> Resubmit #128 (X.H.Focus)

CHANGES.md, XMonad/Layout/LayoutBuilder.hs, XMonad/Layout/LayoutBuilderP.hs, XMonad/Layout/LayoutModifier.hs, XMonad/Layout/MultiToggle.hs, XMonad/Layout/ZoomRow.hs
This enables adding the Typeable constraint to LayoutClass itself
(https://github.com/xmonad/xmonad/pull/242)
which in turn enables querying the current layout state. That might be
useful to e.g. show the current X.L.WorkspaceDir in xmobar.
Example usage: https://github.com/liskin/dotfiles/commit/6ea6c52aac4d39fa5a788372e005954715cb6d9a
**before merging, I need to finish the above checklist tasks, but I'd like to gather feedback first**
=> Add Typeable constraint to a few LayoutClass instances

XMonad/Hooks/WindowSwallowing.hs
While doing my latest PR i noticed that one of my older PRs does not render the usage-section in the docs, as it is not included in the module export header.
I quickly fixed this here, to make sure that the documentation is properly included. Sorry ^^
=> Fix missing usage-section in XMonad.Hooks.WindowSwallowing

CHANGES.md, XMonad/Actions/GridSelect.hs, XMonad/Actions/Navigation2D.hs, XMonad/Actions/ShowText.hs, XMonad/Actions/TopicSpace.hs, XMonad/Hooks/DynamicLog.hs, XMonad/Hooks/ScreenCorners.hs, XMonad/Layout/Decoration.hs, XMonad/Layout/DecorationMadness.hs, XMonad/Layout/DwmStyle.hs, XMonad/Layout/Groups/Examples.hs, XMonad/Layout/Groups/Wmii.hs, XMonad/Layout/ShowWName.hs, XMonad/Layout/SimpleDecoration.hs, XMonad/Layout/TabBarDecoration.hs, XMonad/Layout/Tabbed.hs, XMonad/Layout/WindowNavigation.hs, XMonad/Prompt.hs, XMonad/Prompt/ConfirmPrompt.hs, XMonad/Prompt/Input.hs, XMonad/Util/SpawnNamedPipe.hs
The commit that marked these things as deprecated (0f1b6fb7726fc54b0ef318143ab2ffc43faed8fa) was merged on May 28, 2013; this seems like plenty of time for people to have removed these from their configs.
=> Remove Data.Default Deprecations

XMonad/Layout/IndependentScreens.hs
Closes #111
Trivial typo fix, therefore no tests or updates to CHANGES.md/XMonad.Doc.Extending
=> Fix typo in X.L.IndependentScreens example code

CHANGES.md, XMonad/Util/Loggers.hs
Some Linux distros, like NixOS, don't put these binaries under /usr/bin. This change makes both `battery` and `loadAvg` work on NixOS.
=> Loggers: don't hardcode /usr/bin

CHANGES.md, XMonad/Actions/Prefix.hs, xmonad-contrib.cabal
This patch adds an Emacs-like prefix argument and a wrapper function you can use to turn any `X` action into one aware of the prefix.  See the Usage notes in the file for more details.
=> Add Emacs-style Prefix handling

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Util/ActionCycle.hs, xmonad-contrib.cabal
This PR adds `XMonad.Util.ActionCycle`, which allows users to create `X` actions that cycle between a set list of actions.
These may be useful for toggle-style keybindings, among other things.
=> Add new module XMonad.Util.ActionCycle

CHANGES.md, XMonad/Util/DebugWindow.hs
The existing code has a flipped boolean logic, and incorrectly interprets UTF8_STRING as COMPOUND_TEXT and vice-versa, producing bottoms in strings when a UTF8_STRING is encountered.
=> Check for text encoding correctly and avoid bottom (#422)

CHANGES.md, XMonad/Hooks/DynamicLog.hs, XMonad/Util/NamedScratchpad.hs, XMonad/Util/WorkspaceCompare.hs
This generalizes the `namedScratchpadFilterOutWorkspace` and `namedScratchpadFilterOutWorkspacePP` functions from `X.U.NamedScratchpad`, by allowing the user to specify a list of workspace tags themselves.  The resulting functions are `X.U.WorkspaceCompare.filterOutWs` and `X.H.DynamicLog.filterOutWsPP`.
The respective functions in `X.U.NamedScratchpad` have been deprecated accordingly.
=> Add filterOutWs[PP]

CHANGES.md, XMonad/Config/Xfce.hs
When using xmonad with XFCE the “open terminal” key binding doesn't work, because it tries to start the app which doesn't exist in the system. This PR changes the `terminal` setting to use the default XFCE terminal — `xfce4-terminal`.
=> Use the default XFCE terminal with `XMonad.Config.Xfce`

CHANGES.md, XMonad/Actions/DynamicProjects.hs
Useful for modifying projects using non-prompt mechanisms.
=> Export modifyProject in XMonad.Actions.DynamicProjects

CHANGES.md, XMonad/Hooks/DynamicLog.hs
Stop recommending pipes as the best/first thing to do and instead recommend
property based logging for all bars that support it.  Also strongly recommend
users to use the already pre-made functions that do all of the plumbing.
Using pipes is very error-prone (see e.g. #400), so this seems like a logical
step.  
Unfortunately, how we go about spawning the status bar in this case is not quite
clear.  We can't use `spawn`, nor `safeSpawn`, because that would spawn the
status bar again (without killing the other one first) when restarting xmonad
via `M-q`.  `spawnOnce` is also unsuited (and only used here as a placeholder)
because users expect changes to their bar configurations to take effect when
they `M-q` restart xmonad.  On IRC, we've discussed saving the PIDs somewhere
and killing them …
=> X.H.DynamicLog: Start recommending poperty-based logging

XMonad/Hooks/FadeWindows.hs
(Probably) fixes #419 (still waiting for confirmation of the person on
IRC for that)
So far, the documentation for X.H.FadeWindows had, as an example, the
following `logHook`:
``` haskell
logHook = fadeWindowsLogHook myFadeHook
myFadeHook = composeAll [ isUnfocused --> transparency 0.2
,                 opaque
]
```
The problem is that `composeAll = mconcat` and `mappend` for `FadeHook`
simply throws away the left argument if there's a right one, hence
everything gets marked opaque and `_NET_WM_WINDOW_OPACITY` is never set.
Switching things around solves this problem:
``` haskell
myFadeHook = composeAll [                 opaque
, isUnfocused --> transparency 0.2
]
```
=> Fix Documentation in X.H.FadeWindows

CHANGES.md, XMonad/Config/LXQt.hs, XMonad/Doc/Extending.hs
This module provides a config suitable for use with the LXQt desktop environment.
=> XMonad.Config.LXQt

CHANGES.md, XMonad/Hooks/DynamicLog.hs
After discussing in the IRC channel and in #433 on how we should go about restarting status bars, I tried to add the proposed solution to `XMonad.Hooks.DynamicLog`. This needs to be merged after #408, since I rebased my branch on top of it (this is why the diff looks like a mess and why there are a lot of commits)
Big thanks to @liskin  and @slotThe for the tips and the discussion!
=> Restarting status bars on restart 

XMonad/Hooks/DynamicLog.hs
In #434, `cleanupStatusBars` isn't added to the `startupHook`. Thanks @slotThe for finding the issue
=> Added cleanupStatusBars to the startup-hook

CHANGES.md, XMonad/Prompt.hs
Fixes #164.
It's not clear to me why these functions take in XPState as a param only
to then produce some XP () values. It seems like they could just as well
call `get`.
When tab-completing in alwaysHighlight mode, rather than setting the entire command string, just delete the last word and insert the completion in its place.
Since the entire command is no longer set simply to a completion, dispatch on the last word of the command instead.
Motivated by https://github.com/xmonad/xmonad-contrib/issues/164.
=> Only modify the last word during tab completion

CHANGES.md, XMonad/Hooks/DynamicLog.hs
Add the `ppTitleUnfocused` field to the `PP` record, in order to show
unfocused windows (on the current workspace) in a status bar.
It's sort of unfortunate we have to do this, instead of having a more
strongly-typed `ppTitle` that, instead of a `String`, takes something
like
``` haskell
data WindowPP = WindowPP
{ win       :: !Window
, name      :: !String
, isUrgent  :: !Bool
, isFocused :: !Bool
}
```
But that would require changing the signature of `ppTitle` and thus
probably breaking every config in existence that uses this module...
=> X.H.DynamicLog: Add ppTitleUnfocused

CHANGES.md, XMonad/Prompt.hs
So far, when `alwaysHighlight` was enabled and the user selected an item
while not having completely written it out in the prompt, the raw input
string and not the eventual completion string would be entered into the
prompt history, which is obviously not the desired behaviour.  This can
cause the history to clutter up with all these abbreviations, making
subsequent invocations of the prompt tedious to work with.
For example, an input of "xm" would narrow to both "xmonad" and
"xmobar", but thanks to `alwaysHighlight` "xmobar" was selected.  If the
user now pressed enter, the prompt would correctly return "xmobar" as
the string to act upon, but "xm" would be entered into the prompt
history!
=> X.Prompt: Correctly Update History with alwaysHighlight

XMonad/Hooks/DebugEvents.hs, XMonad/Prompt.hs, XMonad/Prompt/AppendFile.hs, XMonad/Prompt/Man.hs, XMonad/Util/DebugWindow.hs, XMonad/Util/NamedWindows.hs, XMonad/Util/XSelection.hs, xmonad-contrib.cabal
According to its documentation[1], this module simply re-exports
Control.Exception on recent GHC versions.  As we only support recent
versions, this import is unnecessary.
[1] http://hackage.haskell.org/package/extensible-exceptions-0.1.1.4/docs/Control-Exception-Extensible.html
This should probably be merged in conjunction with xmonad/xmonad/pull/263
Not needed, we've already dropped support for compilers this old.
=> Control.Exception.Extensible -> Control.Exception

CHANGES.md, XMonad/Hooks/ManageDocks.hs
This makes docksStartupHook unnecessary. That is desirable because we
didn't add a changelog entry about it being necessary, and 4 years after
its introduction we still have users grabbing old configs and reporting
(https://github.com/xmonad/xmonad/issues/21#issuecomment-596161669) that
ManageDocks doesn't work properly.
I would love to finally settle this.
Full story follows:
xmonad-contrib 0.12 introduced (00be056a1bad, merged in April 2013)
caching to ManageDocks to avoid queryTree calls on every runLayout,
which brought in several bugs. Attempts to fix these bugs in
xmonad-contrib 0.13 introduced (28e9f8bce781, merged in February 2016) a
breaking change in ManageDocks that required users to add
docksStartupHook (or docks, after e38fb3bdb8bb got merged in November
2016) to their …
=> X.H.ManageDocks: Init strut cache on demand if necessary

CHANGES.md, XMonad/Actions/TreeSelect.hs, XMonad/Prompt.hs
Closes #445 
Closes xmonad/xmonad/issues/116
I don't know how "proper" this fix is and I don't have the X11 knowledge to know if there's something more elegant to be done, but simply grabbing the pointer as well causes both the prompt and the tree select window to behave normally when one wants to focus another window.
Config to reproduce the bug and check if the fix actually works:
``` haskell
import Data.Tree (Forest, Tree (Node))
import XMonad
import XMonad.Actions.TreeSelect (toWorkspaces, treeselectWorkspace)
import XMonad.Prompt (XPConfig (font))
import XMonad.Prompt.Shell (shellPrompt)
import XMonad.Util.EZConfig (additionalKeysP)
import qualified XMonad.StackSet as W
main :: IO ()
main = xmonad $ def{ clickJustFocuses = False
, workspaces       = toWorkspaces myWorkspaces
} …
```
=> Grab the Pointer in X.Prompt and X.A.TreeSelect

XMonad/Actions/GridSelect.hs, XMonad/Layout/LimitWindows.hs, tests/Main.hs, tests/SwapWorkspaces.hs, xmonad-contrib.cabal
Preparation for adding unit tests for #407, #430, #440.
* silence warnings about unlisted modules
* remove xmonad-contrib dependency to make it unambiguous that modules
are recompiled with -DTESTING, not taken from the library
* sort build-depends
My main motivation here is that I'd like to add some unit tests (as
opposed to testing everything using QuickCheck properties), but there
are other benefits: it's now easier to run a subset of tests -- the
command-line interface is more powerful.
Also, rename the test-suite to "tests" as it's no longer limited to
properties.
Without this, any change to tests triggers a recompile of GridSelect
when invoking "stack test", adding a couple seconds. This seems to help.
- n/a I tested my changes with …
=> tests: Use hspec as test driver (prep for #407 #430 #440 unit tests); speed up

CHANGES.md, XMonad/Layout/NoBorders.hs, tests/Main.hs, tests/NoBorders.hs, xmonad-contrib.cabal
Before c6cdb77e3b3d6a3842b914a0cf64357f03fcf0c1, handling of floats was trivial (too trivial, and thus inefficient and flickery): any float whose rectangle covered (RationalRect 0 0 1 1), regardless of what screen or workspace it belonged to, got its borders hidden.
Then c6cdb77e3b3d6a3842b914a0cf64357f03fcf0c1 added some nuance (OnlyLayoutFloatBelow, OnlyLayoutFloat, OnlyScreenFloat) which requires looking at floats in the context of individual screens. Unfortunately the implementation only worked in singlehead setups, as it always used only the active screen/workspace regardless of which screen/workspace was currently being layouted. This resulted in the new functionality not working correctly on inactive screens and also regressed the handling of fullscreen floats on inactive screens. …
=> X.L.NoBorders: Fix float handling on multihead setups

XMonad/Actions/Prefix.hs, XMonad/Actions/TreeSelect.hs, XMonad/Hooks/UrgencyHook.hs, XMonad/Hooks/WallpaperSetter.hs, XMonad/Layout/Fullscreen.hs, XMonad/Util/SpawnNamedPipe.hs
1. Remove mentions of `defaultConfig`, as this was removed in favour of `def` a while ago.
2. Deprecate `X.A.TreeSelect.tsDefaultConfig` in favour of `def`, as this was apparently forgotten.
This didn't happen with other `Data.Default` deprecations, so I don't think it's necessary in this case either.
=> Remove last occurences of non Data.Default defaults

CHANGES.md, XMonad/Util/PureX.hs
This can be used to reduce flicker in noop focus actions.
As an example, see #371 (which can't be merged as is due to conflicts with #192 but I'll get that sorted out after dealing with #396; but it's good enough to show motivation).
=> X.U.PureX: Add focusWindow and focusNth

XMonad/Layout/StateFull.hs, XMonad/Layout/TrackFloating.hs, XMonad/Util/Stack.hs
https://github.com/xmonad/xmonad-contrib/pull/253 added a similar module using a somewhat simpler implementation. Borrow some ideas and share some code, so that we can possibly deprecate one in favor of the other.
=> X.L.TrackFloating: Clean up and simplify

CHANGES.md, XMonad/Util/Loggers.hs
I added some more loggers:
- For multi-monitor setups:
- `logWhenActive` to have loggers active only when a certain screen is active.
- `logTitleOnScreen`, `logLayoutOnScreen` and `logCurrentOnScreen` as screen-specific versions of `logTitle`, `logLayout` and `logCurrent`
- A "combinator": `logMaybe` which works like `maybe` (and an infix version for it `(.|) `
- `logConst` to log a constant `String` (I find that it feels better than writing `return . Just` repeatedly, but I didn't change it in the file... maybe see first what people feel about it?)
- Minor cleanups (documentation fix, one `hlint` suggestion)
=> More loggers: A `maybe`-like combinator, and screen-specific loggers

CHANGES.md
`CHANGES.md` is kind of a mess—lot's of modules are mentioned twice and the format is pretty inconsistent.  This aims to change this for the unreleased `0.17`, removing duplicated modules and unifying the style that changelog entries are made.
~~- [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~~
:)
=> Clean up and unify CHANGES.md

XMonad/Actions/WorkspaceNames.hs, XMonad/Layout/IndependentScreens.hs, XMonad/Util/ClickableWorkspaces.hs
Having these work together isn't entirely trivial (see my confusion in
https://github.com/xmonad/xmonad-contrib/pull/390) so let's provide the
integrations.
Also, switch from unmaintained wmctrl to xdotool (rationale in commit
msg).
(I didn't, I think the entry for X.U.ClickableWorkspaces itself it sufficient.)
(I didn't, I think the entry for X.U.ClickableWorkspaces itself it sufficient.)
=> X.U.ClickableWorkspaces: Integrations with X.L.IndependentScreens and X.A.WorkspaceNames

CHANGES.md, XMonad/Util/Hacks.hs
Fixes Java applications that don't work well with xmonad, by setting `_JAVA_AWT_WM_NONREPARENTING=1`
I saw something similar in @geekosaur's config, and I think it's a pretty common solution. Having this in the `X.U.Hacks` can be convenient for some users.
=> Added javaHack

CHANGES.md, XMonad/Hooks/DynamicLog.hs
This was kinda a big one: 
- I added the datatype `StatusBarConfig` which serves as an abstraction over status bar: 
- how to start a status bar, 
- how to log to the status bar,
- what to do with the status bar on restart,
- which key to toggle the struts
- how to toggle the struts
With that, users could have more flexibility on the status bars without having to do the plumbing from scratch. I also made sure the public API does not change. It may be interesting to refactor `X.H.DynamicBars` to also use that abstraction since it offers a nice set of features but I don't recall seeing it used anywhere.
- Added support for multiple status bars, which can be implemented quite naturally given the abstraction provided.
Let me know what you think or if anything needs a second thought! I tried …
=> Refactor X.H.DynamicLog and multiple loggers support

CHANGES.md, XMonad/Config/Mate.hs
Refactor logout and provide an option to display the system shutdown dialog.
=> Mate logout option

CHANGES.md, XMonad/Hooks/ManageHelpers.hs
This branch adds several functions to XMonad.Hooks.ManageHelpers that allows windows to be shifted to the workspace of the leader window. This leader will either be the original window that spawned that window, or another window that the original window spawned. It identifies the leader using the WM_CLIENT_LEADER property.
This is meant to have a similar purpose as the transience hook. However, very few applications set the transience property (in fact, none that I have examined on my system). On the other hand, the WM_CLIENT_LEADER property is set more frequently (in firefox, for example).
The following discussion is relevant: https://xmonad.haskell.narkive.com/xZPtl1AH/managehook-and-child-windows
- n/a I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing) …
=> Added leader functions

CHANGES.md, XMonad/Hooks/ManageHelpers.hs, XMonad/Hooks/UrgencyHook.hs
The note doesn't apply since 9a7dcbbabb21 ("Adjustments to use the new
event hook feature instead of Hooks.EventHook").
The EWMH support added in 7e9c986217cf only added handling of
_NET_WM_STATE_DEMANDS_ATTENTION to handleEvent and cleanupUrgents, but
manual urgency clearing via clearUrgents or automatic urgency clearing
via filterUrgencyHook was left without EWMH support. This commit adds
the missing pieces.
Fixes: 7e9c986217cf ("Add EWMH DEMANDS_ATTENTION support to UrgencyHook.")
This makes it possible to clear urgency of selected windows only, which
may be useful to some users (like me).
If a manually crafted ClientMessageEvent with invalid (nonexistent)
ev_window is sent to xmonad (by sending it to the root window), the
nonexistent window is added to Urgents and stays there forever. …
=> X.H.UrgencyHook: EWMH fix; clearing of selected windows; doc fix

CHANGES.md, XMonad/Layout/TrackFloating.hs
When focus changes¹ on an inactive workspace (not `current`, but
`visible`), TrackFloating and UseTransientFor would think they should
use the remembered focus point as they look at the wrong (`current`)
workspace instead of the workspace they're supposed to layout, and so
focus seems to be out of their set of windows, when actually it is not.
Fix this by looking at the correct workspace.
¹) This isn't entirely straightforward, as there are normally no
keybindings or StackSet operations for this, but it's perfectly legal
to `W.view` the inactive workspace, change focus, and `W.view` back
in a single `windows` action.
=> X.L.TrackFloating: Fix changing focus on inactive workspaces

CHANGES.md, XMonad/Prompt.hs
Closes #455
526336e introduced a bug where tab-completion has an issue when a
completion contains spaces; it only deletes the last word of that
completion, causing the next TAB to again select the current selection
and add it to the command.  In this way, the prompt can get "stuck" on
an item, endlessly adding all but the first word to the command every
time TAB is pressed.
This is fixed in a (hopefully) acceptable way @sam-barr can you confirm?
1. Also changes the indexing inside `highlightedItem` to a safe index;
this way one is able to cycle through the suggestions for the prompt
(before, the prompt would close due to an exception from `(!!)`).
3. Applies most of the (sane) hlint suggestions to `XMonad.Prompt`,
because they bothered me when working on this.
~~- [ ] I updated the …
=> X.Prompt: Correct tab completion handling

CHANGES.md, XMonad/Layout/Fullscreen.hs
Add fullscreenSupport' which uses smartBorders to remove the window borders when a window goes fullscreen.
=> Add fullscreenSupportBorder

CHANGES.md, XMonad/Config/Mate.hs
Use mod+d to open the Mate Main Menu.
It is now possible to open Mate Main Menu using a keybinding (default mod+d).
This feature was missing from Mate.hs config.
=> Add Main Menu keybinding to Mate.hs

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Hooks/DynamicIcons.hs, xmonad-contrib.cabal
behind them.
I have added a Dynamic Icons system based on what windows are inside a workspace. This allows easy tracking of where specific applications are due to the fact that they are clearly visible in your PP bar or however it is displayed. All this does is append the existing PP .
UPDATE
I have now made it a separate module
---
=> Add Dynamic Icons based on the Windows inside a workspace 

CHANGES.md, XMonad/Prompt.hs
This allows limiting the number of columns in the completion window. The window width is divided equally between the columns.
=> X.Prompt: Add maxComplColumns field to XPConfig

stack.yaml
This allows someone using NixOS to easily download and build the xmonad-contrib git repo with stack. I'm honestly not sure whether this is how it's _supposed_ to be done, but it does work (for me).
=> Add nix packages to stack.yaml.

CHANGES.md, XMonad/Hooks/DynamicLog.hs, XMonad/Util/Run.hs
This makes it easier to see the differences between these functions,
makes it less likely someone will change one and not the others, etc.
More importantly, the documentation doesn't contain circular references
any more. :-)
Also, let's just use hSetEncoding. The concern of this being stateful
and theoretically having something written in the wrong encoding is
pointless: nobody has the handle until we return it from `spawnPipe'`.
(This also means that spawnPipeWithNoEncoding is now a text handle that
possibly does newline translation, just with char8 encoding. There
should be no difference in practice.)
Fixes: 8b2bd3ae5cd1 ("Add new variants of spawnPipe functions with encoding support")
For many (10+) years, we had a cascade of ugly workarounds:
* X.U.Run.spawnPipe returned a binary …
=> Fix encoding issues in spawnPipe/dynamicLogString/xmonadPropLog

XMonad/Actions/ConstrainedResize.hs, XMonad/Actions/FlexibleManipulate.hs, XMonad/Actions/FlexibleResize.hs, XMonad/Actions/FloatKeys.hs, XMonad/Actions/FloatSnap.hs
This applies fixes from
https://github.com/xmonad/xmonad/commit/4565e2c90ef522d23d3afc2cf95b9f0b423d8de4
and
https://github.com/xmonad/xmonad/commit/b9ce5b034ba389b95b663e9f56bbc18a227f8695.
tl;dr:
When dragging, refloat and refresh to fix https://github.com/xmonad/xmonad/issues/63.
When starting dragging, raising the window is then unnecessary, and
removing it fixes https://github.com/xmonad/xmonad/issues/208.
Also remove unnecessary raises for keyboard moving/resizing which always
refloated the window.
Fixes: https://github.com/xmonad/xmonad/issues/63
Fixes: https://github.com/xmonad/xmonad/issues/208
=> Apply two xmonad core fixes to float moving/resizing in various contrib modules

CHANGES.md, XMonad/Actions/TopicSpace.hs, XMonad/Hooks/WorkspaceHistory.hs
#405 was a first step in cleaning up `TopicSpace`.  It, however, didn't go far enough with regards to the history.  With a few simple tweaks we are able to properly deprecate the internal history handling and defer to modules specifically build for it, i.e. `X.H.WorkspaceHistory`.  It also gets rid of the now unneeded `getLastFocusedTopicsByScreen` and `switchTopicWith` (these are not present in `0.16`) and deprecates everything else for backwards compatability. 
=> X.A.TopicSpace: Deprecate internal history 

CHANGES.md, XMonad/Hooks/ManageDocks.hs, XMonad/Util/ExtensibleState.hs
We only requested PropertyChange events from docks in the `manageDocks` manageHook, but that only gets called for normal windows, not override_redirect ones. Therefore, xmobar in its default configuration wouldn't get its struts refreshed on changes. This resulted in gaps not updating after xmobar repositions itself on xrandr changes.
If one wanted to handle that repositioning in xmonad, it was possible to configure xmobar with `overrideRedirect = False`, which is meant for window managers with [proper EWMH stacking order support][1], so in xmonad it resulted in xmobar covering fullscreen windows. That can be worked around by adding `checkDock --> doLower` to manageHook, but it starts to smell of too many workarounds.
[1]: https://specifications.freedesktop.org/wm-spec/wm-spec-1.5.html#STA …
=> X.H.ManageDocks: React to strut updates of override_redirect docks

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Util/Hacks.hs
Placing `trayer` on top of `xmobar` is somewhat tricky:
- they both should be lowered to the bottom of the stacking order to avoid overlapping fullscreen windows
- the tray needs to be stacked on top of the panel regardless of which happens to start first
`trayerAboveXmobarEventHook` (and the more generic `trayAbovePanelEventHook`) is an event hook that ensures the latter: whenever the tray lowers itself to the bottom of the stack, it checks whether there are any panels above it and lowers these again.
=> X.U.Hacks: Add "Stacking trays (trayer) above panels (xmobar)"

CHANGES.md, XMonad/Actions/ShowText.hs, XMonad/Layout/Decoration.hs, XMonad/Layout/ShowWName.hs, XMonad/Prompt.hs
Layout broken if font is not found with `user error (createFontSet)`
Pango 1.44 dropped support for FreeType in favor of HarfBuzz thus losing support for traditional BDF/PCF bitmap fonts. There would be no `xorg-fonts-misc` on future installations.
Fixes https://github.com/xmonad/xmonad-contrib/issues/348
Change default `fontName` to accept any font.  Previous default expects XOrg misc font (PCF) which is not supported in pango 1.44 anymore and would not be present in future installations.
Font not found causes silent `user error (createFontSet)` and breaks Layout.
I've tested with latest `git` versions of `xmonad` and `xmonad-contrib`
=> Permissive font pattern by default (fix broken layout)

CHANGES.md, XMonad/Layout/Magnifier.hs
Closes #168
Add the `magnifierczOff` and `magnifierczOff'` functions for custom-size magnification, with it being off by default.  This seems preferrable to exporting the internal constructor, so we can change that if necessary.  
There is also a bit of cleanup in there, like strictifying the `Magnifier` type and implementing functions in terms of each other for easier maitnenance, that I didn't think were worth their own pr. 
=> X.L.Magnifier: Add `magnifierczOff` and `magnifierczOff'`

CHANGES.md, XMonad/Layout/Magnifier.hs
Add the ability to only start magnifying when a certain number of windows is reached.  As a byproduct, cleans up the rather embarassing mistake made in bb205e92051de531c6c8b7eb1d692779969b6710 to not just transform everything into a record.
Also add a more general `magnify` function that subsumes (almost) all previously known combinators.  This needs exporting of some previously internal (but not crucial to the implementation) types, but the internals are still changeable easily enough. 
=> X.L.Magnifier: Add `magnify` combinator, magnification at `n` windows

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Prompt/OrgMode.hs, xmonad-contrib.cabal
A new prompt for interacting with [org-mode](https://orgmode.org/).
It can be used to quickly save TODOs, NOTEs, and the like with the
additional capability to schedule/deadline a task, or use the
primary selection as the contents of the note.
Right now `orgPromptPrimary` still relies on `X.U.XSelection.getSelection`, but the long-term plan would be to also rewrite that module to be less insane.  I do, however, think that the module in its current form is very benefitial already so I'm releasing it like this for now.
=> New Module: XMonad.Prompt.OrgMode

XMonad/Hooks/DynamicLog.hs, XMonad/Hooks/StatusBar.hs
This is a follow-up on the IRC [discussion](https://ircbrowse.tomsmeding.com/browse/xmonad?id=28392#trid28392)
This applies for `withSB` and `withEasySB`, as well as `statusBarProp` and
`statusBarPropTo`, making composability better. `statusBarPipe` is more
awkward to use now, but that's fine
=> `X.H.StatusBar`: Removed unnecessary IO

CHANGES.md, XMonad/Layout/Renamed.hs
Add `KeepWordsLeft` and `KeepWordsRight` as stated in https://github.com/xmonad/xmonad-contrib/issues/482
I think these are only minor changes.
@TheMC47 I am not sure if I have done it right.
The only problem I encountered is that the layout information shown in xmobar does not change over restart. So I have to exit and start xmonad multiple times for testing.
=> add KeepWordsLeft and KeepWordsRight for X.L.Renamed

XMonad/Prompt.hs
Fixes a bug introduced in f2cfaa33980061f4fb39b689403701d36babe33f.
The changes there allowed the prompt to cycle through its input; it now
becomes necessary to single out the case of only having a single
suggestion that's also highlighted.  Otherwise, `hlComplete` (condition:
`alwaysHighlight` is enabled) will loop forever.  This case can't be
handled from within hlComplete, as we are giving it incomplete
information to start with (by only calling it with the last word of the
current completion in `handleCompletion`), which is necessary for things
like completing arguments.
Sigh.
I don't think this is really necessary.
=> X.Prompt: Special handling of one highlighted item

XMonad/Doc/Extending.hs, XMonad/Hooks/DynamicIcons.hs
Followup to https://github.com/xmonad/xmonad-contrib/pull/450 and https://github.com/xmonad/xmonad-contrib/pull/481.
Make it possible to keep workspace id in the output (iconsFmtAppend) and to wrap icons even if there's just one, or zero.
Also, change the default to use curly brackets to avoid confict with brackets/parentheses used by default PPs in DynamicLog.
Related: https://github.com/xmonad/xmonad-contrib/pull/450
Rename to dynamicIconsPP and change the type to something similar to workspaceNamesPP and marshallPP.
Related: https://github.com/xmonad/xmonad-contrib/pull/450
Move all the workspaces and icon generation logic into getWorkspaceIcons and drop the Maybe which is no longer necessary since we made the formatting logic configurable.
Related: …
=> X.H.DynamicIcons: Cleanups, docs improvements, composability with other *PPs

XMonad/Prompt.hs, XMonad/Util/NamedActions.hs
This adds a `MINIMAL` pragma to the classes that should have one, i.e. the classes that have at least one function with a default implementation and at least one without. 
=> Add `MINIMAL` pragmas to `HasName` and `XPrompt`

XMonad/Prompt.hs
When `alwaysHighlight` is enabled and one immediately presses (by
default) Return after opening the prompt (because the highlighted
completion is what one wants) then the selection will not enter the
prompt history.  Instead, an empty string will be entered because there
hasn't been any input yet and hence the `highlightedCompl` field has not
yet been filled in.
The fix is simply checking whether `alwaysHighlight` is set during
startup and, if yes, already setting the highlighted completion to the
first suggestion.
The relevant entry of 
>    - Made the history respect words that were "completed" by `alwaysHighlight`
>      upon confirmation of the selection by the user.
already covers this.
~~- [ ] I updated the `XMonad.Doc.Extending` file (if …
=> X.Prompt: fix selection not entering history

XMonad/Util/ClickableWorkspaces.hs
To solve https://github.com/xmonad/xmonad-contrib/issues/510, I add a `getWsIndex` in it. `getWsIndex` will call `getSortByIndex`.
The reason are as follows: 
1. Using X.A.DynamicWorkspaces, by adding and deleting workspaces, the total number of workspaces varies.
2. I have tried to use a more general form, that is, use `[Windowspace]->[Windowspace]` and let ClickablePP receive a `X WorkspaceSort'`. However, I discovered that when using `getSortByTag`, the order of workspaces in `xdotool` is still similar to `getSortByIndex`. In other words, `getSortByTag` is useless here or we need to modify the workspace order received by `xdotool`. I don't know how to solve it.
Solution to address problem from `reason 2`: 
User use `withNthworkspaces` and `getSortByTag`. Which means user needs to …
=> ClickableWorkspace Improvement for X.A.DynamicWorkspaces

CHANGES.md, XMonad/Layout/WorkspaceDir.hs, XMonad/Prompt.hs, XMonad/Prompt/Directory.hs, XMonad/Prompt/Shell.hs
This is my first time submitting a pull request of any kind, so please tell me if I've done anything incorrectly.
This PR is an implementation of the suggestion in issue #509, with all relevant functions changed so as to expect the rewritten datatype. 
- [✔️] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
- [✔️] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)
- [✔️] I updated the `CHANGES.md` file
- [✔️] I updated the `XMonad.Doc.Extending` file (if appropriate)
=> Redefined `ComplCaseSensitivity` as a proper sum type. (#509)

XMonad/Util/Hacks.hs
Add a resized gif for `X.U.Hacks`
For https://github.com/xmonad/xmonad-contrib/issues/488
=> add link to resized gifs

CHANGES.md, XMonad/Hooks/WallpaperSetter.hs
As discussed in https://github.com/xmonad/xmonad-contrib/issues/518
I just clean a bit of the syntax and have tested the module. It is painfully slow with noticeable lagging. As I don't know how to implement a cache for the images, I can not improve the performance. The `todo` by previous author(s) also mentioned about caching.
Use `feh` without `convert` will see an small boost in performance. But that is up to the users to decide.
=> add support for multiple formats for X.H.Wallpapersetter

CHANGES.md, XMonad/Prompt/Shell.hs
A new prompt that works like `safePrompt`, but is optimized for the
use-case of a program that needs a file as an argument.
This is necessarily a new function and can't just be achieved by using
the old `safePrompt`, as `getShellCompl'` does not at all filter the
files (compgen already does that based on the input), but only the
available commands.  If we start the prompt with a single command then
the chosen `searchPredicate` becomes quite useless and we can't take
advantage of fuzzy matching for file finding.  This, however, is quite
useful when having a program that explicitly expects a file as one of
its arguments, e.g. dragon [1].
What we have to do instead of to generate all available files with
compgen and _then_ filter this down to what we want via a given
function.  In order to …
=> X.P.Shell: add `safeDirPrompt`

XMonad/Util/EZConfig.hs
This is a small one, but everything that brings down our global LOC is good, I guess :)
We're not parsing anything (as opposed to the respective `P` functions)
and so there's no need to create a dummy map with units as values and
then take the difference; we can simply remove the relevant keys from
the map.
=> X.U.EZConfig: Simplify removeKeys, removeMouseBindings

XMonad/Actions/EasyMotion.hs
This is a cleanup pr for the recently merged `X.A.EasyMotion`.  This doesn't introduce any significant changes to the module; it consists of mostly doc fixes and minimal (or superficial) simplifications.  
The perhaps most drastic change is 78f3ad26ed7f1ad2fa70a42f24203fa4e140c9ce where we strictify all of the data types define by the module (because there's absolutely no reason not to), but this should not impact functionality.
Cc @partiallyordered 
=> X.A.EasyMotion: Cleanup, doc improvement

CHANGES.md, XMonad/Hooks/StatusBar/PP.hs, XMonad/Util/Loggers.hs
This replaces `ppTitleUnfocused` from commit
a3e0668 with a more extensible version,
containing more information about the window and being able to operate
on the focused window as well.
The functionality provided is a strict superset of `ppTitle`, though
that function is kept for backwards compatibility.
This plays nicely with #463 for lazy people like me who want their bars to read from the same property, as showing windows only if they're on the current screen is now easily possible (see the example). 
=> Move `ppTitleUnfocused` to X.U.Loggers

XMonad/Actions/TreeSelect.hs
The issue was fixed upstream in 0.3.3:
https://github.com/clefru/X11-xft/commit/24f6275791f2212215047f7af898750b7846810e
https://github.com/clefru/X11-xft/commit/24f6275791f2212215047f7af898750b7846810e^
(it is yet to be uploaded to Hackage, Clemens lost his Hackage credentials :-))
Related: https://github.com/xmonad/xmonad-contrib/pull/486
Related: 46f24bb27ec4 ("X.A.TreeSelect: Fix swapped green/blue in foreground when using Xft")
I tested it manually in ghci.
- n/a I updated the `CHANGES.md` file
=> X.A.TreeSelect: Only swap green/blue for X11-xft < 0.3.3

XMonad/Hooks/StatusBar.hs, XMonad/Hooks/StatusBar/PP.hs
The example in `X.H.StatusBar.PP` wasn't updated when we removed the `X` from `statusBarProp`, and #535 shows that the loggers weren't really discoverable.
@slotThe do you think this is better?
~- [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~
~- [ ] I updated the `CHANGES.md` file~
~- [ ] I updated the `XMonad.Doc.Extending` file (if appropriate)~
=> Documentation tweaks for `X.H.StatusBar(.PP)`

CHANGES.md, XMonad/Actions/DynamicWorkspaceGroups.hs
This adds `viewTopicGroup` and a corresponding prompt. This is similar
to `viewWSGroup`, but it calls `switchTopic` instead of `W.greedyView`,
in order to run the topic action on the workspace.
manually, ...) and concluded: it works
=> `X.A.DynamicWorkspaceGroups`: TopicSpace support

CHANGES.md, XMonad/Actions/TopicSpace.hs
1. Add a new type 'TopicItem', as well as several helpers.  This is so users don't have to specify things in two places and then use some extra function to check if they've not made any mistakes.
2. Update the `Usage` documentation of TopicSpace; fix some inconsistencies and tell users that there is an alternative way.
Concerning the second part, I wonder if we should just drop "the old way" and tell users that going through 'TopicItem' is just how one should configure the module.  Personally, I think it's a straight upgrade over having to manually specify everything.  Opinions?
Cc: @byorgey because I originally took the definition of `TopicItem` out of [your configuration](https://github.com/byorgey/dotfiles/blob/master/xmonad.hs#L170).  
manually, ...) and concluded: most of this is …
=> X.A.TopicSpace: Add 'TopicItem'

.github/FUNDING.yml
These past months I've spent a lot of time working on xmonad and I feel like I've done a lot. This is, however, not sustainable long term. :-(
I'd like to try making my GitHub Sponsors profile a bit more visible, hoping that would allow me to continue dedicating time to xmonad.
I know that the correct approach probably is for the xmonad project to find a fiscal sponsor like the Software Freedom Conservancy or Open Collective or something and accept donations as a project, and then redistribute that to people, but I don't think the project has enough momentum to do something as complicated as that. :-/
---
@xmonad/core @slotThe @TheMC47 Are you folks okay with me doing this? Can I put that on https://github.com/xmonad/xmonad as well? Would you like to add your profile as well (I checked …
=> Add Sponsor button to GitHub

CHANGES.md, XMonad/Hooks/StatusBar/PP.hs
xmobar allows you to define a list of additional fonts (`additionalFonts`) and to use the fn tag to choose between them (by passing in the index of the font to use). `xmobarFont` is essentially the same as the existing `xmobarColor` function, but for fonts.
Specifically, I use this to use an icon font for my workspaces, but I imagine this can be useful for other situations as well.
=> Add xmobarFont

XMonad/Hooks/EwmhDesktops.hs
This prevents an unnecessary refresh.
That refresh would normally be harmless but it does reset the input focus, which happens to upset some non-conforming clients such as https://github.com/flameshot-org/flameshot. Flameshot is an interactive screenshot tool that creates an override-redirect fullscreen window to let the user select a rectangle to capture and then allows drawing and adding text and so on, but it unfortunately doesn't follow ICCCM recommendations:
> If it is necessary for a client to receive keystrokes on an override-redirect window, either the client must grab the keyboard, or the client must have another top-level window that is not override-redirect and that has selected the Locally Active or Globally Active focus model.
Instead, it just takes input focus and hopes for …
=> X.H.EwmhDesktops: Ignore _NET_WM_STATE_FULLSCREEN from unmanaged windows

XMonad/Hooks/StatusBar.hs
This provides dynamic status bars, that react to screen configuration changes. This needs the new interface from #443 and the splitting from #465, so I'm marking the PR as a draft till that's resolved.
Heavily inspired by "XMonad.Hooks.DynamicBars"
=> Dynamic Status Bars support for XMonad.Hooks.StatusBar

XMonad/Hooks/ManageDocks.hs
Decoration windows are created using XMonad.Util.XUtils.createNewWindow
which happens to set _NET_WM_WINDOW_TYPE to _NET_WM_WINDOW_TYPE_DESKTOP,
and ManageDocks considers such windows candidates for struts and
therefore requests property events, thus overriding the original event
mask requested by decorations.
The fix is to first obtain the current event mask, set the required bits
in it only then reset the mask.
Fixes: https://github.com/xmonad/xmonad-contrib/issues/517
Fixes: ec146171238b ("X.H.ManageDocks: React to strut updates of override_redirect docks")
Related: https://github.com/xmonad/X11/pull/77
I tested this manually and I've verified that dragging works now and
that https://github.com/xmonad/xmonad-contrib/pull/492 isn't
regressed either. We do …
=> X.H.ManageDocks: Fix button events on decoration windows

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Util/ExtensibleConf.hs, tests/ExtensibleConf.hs, tests/Main.hs, xmonad-contrib.cabal
It's often difficult to make contrib modules work together. When one depends on a functionality of another, it is often necessary to expose lots of low-level functions and hooks and have the user combine these into a complex configuration that works. This is error-prone, and arguably a bad UX in general.
This commit presents a simple solution to that problem inspired by "extensible state": extensible config. It allows contrib modules to store custom configuration values inside XConfig. This lets them create custom hooks, ensure they hook into xmonad core only once, and possibly other use cases I haven't thought of yet.
This requires changes to xmonad core: https://github.com/xmonad/xmonad/pull/294
A couple examples of what this gives us:
* …
=> X.U.ExtensibleConf: New helper module for extensible config

CHANGES.md, XMonad/Actions/CycleRecentWS.hs, tests/CycleRecentWS.hs, tests/Main.hs, xmonad-contrib.cabal
Fixes #504.  The patch got a little bit more complicated; see below.
The way that workspace cycling is implemented right now—by generating
new windowsets where the things we want happen to be true and then
replacing the old windowsets—is not safe, as workspaces and layouts may
carry state with them.  That state will get lost in translation when
windowsets are simply replaced.
As an example, a conflict occurs when using `X.L.ShowWName.showWName` in
one's layoutHook.  When cycling through workspaces via, e.g.,
`cycleRecentWS` the flashed workspace tag will not disappear, as the
necessary state to control this isn't present in the new windowset.
Instead, what we want to do is to keep the "current" windowset alive and
actually switch to the requested workspaces.  This mostly works without …
=> X.A.CycleRecentWS: Cycle workspaces, not windowsets

CHANGES.md, XMonad/Actions/TreeSelect.hs, XMonad/Layout/Decoration.hs, XMonad/Prompt.hs
Fixes:
- https://github.com/xmonad/xmonad-contrib/issues/526
- https://github.com/xmonad/xmonad-contrib/issues/369
Set the WM_CLASS property for long-living windows that need it.  This
helps users to properly match on these windows for certain tasks.
This needs a new X11 release, hence it's a draft for now.  I also didn't change the bounds in the cabal file, as #545 has already done this and I expect this will get merged sooner. 
I was a bit conservative with what to set properties for.  Things like X.U.EZConfig also create windows that may very well have such a property, but I didn't think they were long-lived enough to warrant it really.  Feel free to point me to more modules that need it and I'll add them.
manually, ...) and concluded: 
I tested this by hand and it works.  I don't …
=> Set `WM_CLASS` for some windows

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Hooks/Rescreen.hs, XMonad/Hooks/StatusBar.hs, XMonad/Util/ExtensibleConf.hs, tests/ExtensibleConf.hs, xmonad-contrib.cabal
Inspired by
https://github.com/fis/dot-xmonad/blob/a8c8e804873f8657fc1f1a0d93ee3f58f7a56e22/zem/src/Zem/AutoRandr.hs
and my own
https://github.com/liskin/dotfiles/blob/43999573d006311292a9fadde02f3b234140d999/.xmonad/xmonad.hs#L308-L339,
this adds a generic hook module that allows attaching a custom hook to
rescreen and randr screen change notify event, hiding the complexity of
suppressing duplicate events (debouncing) and distinguishing actual
xrandr configuration changes from output connects/disconnects.
Don't assume ewmh/docks are the only xmonad config combinator out there.
Now that randrChangeHook is only invoked for changes that don't result
in rescreen, it can actually be used for autorandr.
=> X.H.RescreenHook: New module (custom rescreen and randr event hooks)

XMonad/Hooks/StatusBar.hs
`statusBarGeneric`: A generic `StatusBarConfig` that launches a status bar but takes a generic `X ()` logging function instead of a `PP`. This has several uses:
* With `xmonadPropLog` or `xmonadPropLog'` in the logging function, a custom non-`PP`-based logger can be used for logging into an `xmobar`.
* With `mempty` as the logging function, it's possible to manage a status bar that reads information from EWMH properties like `taffybar`.
* With `mempty` as the logging function, any other dock like `trayer` or `stalonetray` can be managed by this module.
Related: https://github.com/xmonad/xmonad-contrib/pull/463
It'd be lovely if someone tried this because I haven't. :-)
But then, what could possibly break here?
(Still didn't manage to rebase my stuff on top of …
=> X.H.StatusBar: Add statusBarGeneric for taffybar/trayer/stalonetray

CHANGES.md, XMonad/Actions/BluetileCommands.hs, XMonad/Actions/CycleSelectedLayouts.hs, XMonad/Config/Arossato.hs, XMonad/Config/Bluetile.hs, XMonad/Config/Droundy.hs, XMonad/Layout/Groups/Examples.hs, XMonad/Layout/Groups/Wmii.hs, XMonad/Layout/LayoutCombinators.hs, XMonad/Layout/MessageControl.hs, XMonad/Prompt/Layout.hs
This is the contrib part of xmonad/xmonad@0077ed7c60a61e30a8ae7f78d3bd028f5ce4a9b3, essentially cleaning up `X.L.LayoutCombinators`.
Build failures are to be expected, as xmonad/xmonad@0077ed7c60a61e30a8ae7f78d3bd028f5ce4a9b3 is not merged yet.
=> Move X.L.LayoutCombinators.(|||) to XMonad.Layout

XMonad/Prompt.hs
`X.Prompt` is big.  And ugly.  I'd really like to revamp some of the internals (thankfully none of the `XPState` stuff is exported) but quite frankly I just don't understand some of the code in its current state.  This is a first effort to document some of the internal functions, so they may be more greatly simplified in the future.  I focused mostly on the X-specific part of the completion window implementation but this is still pretty long, sorry about that.
There are already a few simplifications in here that I couldn't resist making straight away:
* [X.Prompt: Make ComplWindowDim a proper type](https://github.com/xmonad/xmonad-contrib/commit/728e933848a317a5b2a31fadb37f65c8748d07a3)
This gets rid of the horrible tuple implementation
``` haskell
type ComplWindowDim = …
```
=> X.Prompt: Document, simplify completion window implementation

CHANGES.md, XMonad/Actions/CopyWindow.hs, XMonad/Config/Dmwit.hs, XMonad/Layout/IndependentScreens.hs
So basically I add:
1. `withNthWorkspaceScreen` to make it work with dynamicWorkspces
2. `copyWindowTo` to make it work with CopyWindow
3. `marshallSort'` (minor changes) to let it work properly with getSortByIndex
4. `wsContainingCopies` to let it detect copied windows properly (with CopyWindow)
5. `withScreen` (minor changes) to allow for different workspace names for each monitor
I am not sure if some function should be put in XMonad.Layout.IndependentScreens or other places.
=> Fix bug #420, add some functions to IndependentScreens

XMonad/Prompt/OrgMode.hs
If we have a URL in the clipboard and we use `orgPromptPrimary`, it
would be nice if
message +s 11 jan 2013
would result in
* TODO [[_URL_][message]]
SCHEDULED: <2013-01-11 Fri>
instead of the current
* TODO message
SCHEDULED: <2013-01-11 Fri>
_URL_
This has the advantage that if one shows scheduled or deadlines items in
the org-agenda, it is possible to immediately follow this link with
`C-c C-o` or similar functionality.
The URL detection is very rudimentary right now.  One use `parseURI`
from `network-uri`, but that would be an additional dependency that I
didn't think was worth it.
As a bonus (because it annoyed me while testing) there is also
- Prune extra whitespace
This implements whitespace pruning at the end of a sheduled item or
deadline.  If we have a message like
This is a …
=> X.P.OrgMode: Linkify URLs with `orgPromptPrimary`

CHANGES.md, XMonad/Actions/CycleWS.hs, XMonad/Actions/SwapWorkspaces.hs, XMonad/Actions/WorkspaceNames.hs, XMonad/Config/Droundy.hs
By deprecating everything except `WSIs` and adding constructors to
logically combine `WSType` values, we can have a more flexible interface.
Adding anything to the old interface would mean going through `WSIs`, and
all old constructors can be implemented in terms of `WSIs`.
`ignoringWSs` is useful in combination with `X.U.NamedScratchpad` to
skip a list of tags
I went the extreme way of deprecating the constructors, but if you don't
think this is an improvement we could drop that commit and re-write
`ignoringWSs` as `WSType -> [WorkspaceId] -> WSType`. I don't see
the usefulness of the old constructors though.
=> `X.A.CycleWS`: deprecate `WSType` constructors, add `ignoringWSs` predicate

XMonad/Prompt/OrgMode.hs, tests/Main.hs, tests/OrgMode.hs, xmonad-contrib.cabal
Adds property tests for the parser in X.P.OrgMode by constructing a
pretty printer that is a proper inverse of the parser (modulo the fact
that `Maybe A ≅ A`).
This also gave me the opportunity to specify some corner cases that
users are unlikely to run into, but of course quick-check happily
notices :)
- X.P.OrgMode: Only parse actual words
Instead of trying to find a prefix and then killing the rest of the
word, actually see whether it at least fits the pattern.  This means
that
message +s saturated
will no longer parse as a scheduled item for saturday, while
message +s satur
still will.
- X.P.OrgMode: Parse empty message
Empty messages seem quite useless, but it's an easy fix for the parser
to be able to deal with them, so do it.
- X.P.OrgMode: Start counting years at 25
This is for …
=> X.P.OrgMode: Add property tests

CHANGES.md, XMonad/Util/PureX.hs
Added the function `shiftWin` to `Xmonad.Util.PureX` as a refresh-tracking version of `W.shiftWin`.
This was a gap in the currently privded interface that I needed. 
This PR only adds the function `shiftWin`, so unit tests on this function would suffice. For example, if the target tag or target window don't exist, then it should return `Any False`, if the window is already on the target tag, it should return `Any False`, in all other cases it should return `Any True`.
=> added function shiftWin to PureX

CHANGES.md, XMonad/Hooks/RefocusLast.hs, XMonad/Util/NamedScratchpad.hs
Adds a new logHook, nsHideOnFocusLoss, that hides the given
scratchpads when they lose focus.  This is akin to the functionality
provided by a lot of dropdown terminals.
Relevant commits:
- X.H.RefocusLast: Export withRecentsIn
This exports the `withRecentsIn` function, as it's quite useful when
using X.H.RefocusLast in other modules as a library.
It is already possible (RecentsMap is fully exported) to completely
define this function outside of the module, so we are not exposing any
more internals than we were before.
- X.U.NamedScratchpad: Add nsHideOnFocusLoss 
manually, ...) and concluded: I don't think we have any proper setup for testing logHooks do we?  As far as I can tell, this is only using the reader/state part of `X`, so it should theoretically be possible...  
- [n/a] I …
=> X.U.NamedScratchpad: Add logHook to auto-hide named scratchpads on focus loss

CHANGES.md, XMonad/Actions/DynamicWorkspaceOrder.hs
The `swapWithCurrent` and `swapOrder` actions have been added to the list of exported names by the `X.A.DynamicWorkspaceOrder` module. They're very convenient for quickly changing the workspace order in ways that would normally take multiple calls to `swapWith`.
manually, ...) and concluded: tested manually.
=> X.A.DynamicWorkspaceOrder: Export swapOrder and swapWithCurrent

CHANGES.md, XMonad/Actions/GridSelect.hs, tests/GridSelect.hs, tests/Main.hs, xmonad-contrib.cabal
Due to differences between random-1.1 and random-1.2, on newer systems stringToRatio returns numbers outside [0, 1] range, which breaks colorRangeFromClassName colorizers.
This commit fixes the issue by using randomR to directly generate the random number.
Also this fixes the compilation warning (genRange and next are deprecated in random-1.2).
Instead of using sum of charactes I've elected use a simple hash - this will result in a bit less collisions (simple sums of characters collide quite often).
=> rewrite GridSelect.stringToRatio to use randomR (fixes #572)

XMonad/Hooks/DynamicLog.hs, XMonad/Hooks/StatusBar.hs
`(0,0)` typically comes from using `def` as the keybinding function,
which is resolved as `const (0,0)` via the function and tuple instances
for `def`.
In older versions of xmonad, this would bind every unbound key to
toggle struts. This has been fixed, but we should still try to
honor the user's intent in using `def` there.
A user who intends no keybinding function should use `withSB`
instead, especially if xmonad doesn't have aforementioned fix yet.
manually, ...) and concluded: this involves xmonad core and the X
server, so probably manually
=> trap `(0,0)` keybinding function and use default binding

XMonad/Hooks/DynamicLog.hs, XMonad/Hooks/StatusBar.hs
Would this also work?
Fixes: 58e2b803a478 ("fix: handle `const (0,0)` from passing `def` as keybinding action")
=> X.H.StatusBar: Simplify the fix for `def` as `k`

CHANGES.md, XMonad/Layout/NoBorders.hs, tests/Instances.hs, tests/NoBorders.hs
This adds an `OnlyFloat` data constructor to `Ambiguity`; I've found this curiously missing with the current setup of things. 
manually, ...) and concluded: A property test is included; we sadly can't test for arbitrary `WindowSet`s because there's no arbitrary instance for this.  However, the hand-crafted dual-head setup seems decent enough for this purpose.
- [n/a] I updated the `XMonad.Doc.Extending` file (if appropriate)
=> X.L.NoBorders: Add OnlyFloat

CHANGES.md, XMonad/Doc/Extending.hs, XMonad/Hooks/TaffybarPagerHints.hs, xmonad-contrib.cabal
This code currently lives in the taffybar repository, but it is actually quite annoying to force the xmonad binary build to depend on the taffybar library, since all that is needed is this tiny module which has more to do with what is going on in xmonad anyway.
=> X.U.TaffybarPagerHints: init

CHANGES.md, XMonad/Actions/Submap.hs, XMonad/Util/Ungrab.hs
When `runProcessWithInput` is invoked immediately after `ungrabPointer`/`ungrabKeyboard`, we don't actually ungrab at all because `runProcessWithInput` blocks and the ungrab requests wait in Xlib's queue for a request that needs a queue flush.
Common uses of `unGrab` (before `spawn`) aren't followed by a blocking action, so the ungrab requests are flushed by xmonad's main loop, and this is merely a timing issue—fork/exec takes a while and xmonad probably manages to get back to its main loop in time. Uses of `runProcessWithInput` in ordinary non-submap key bindings happen to work because key bindings are passive grabs—the grab is released by the user's fingers releasing the key itself, even if xmonad's ungrab requests are stuck in a blocked queue. Submap key bindings, however, take an …
=> X.A.Submap, X.U.Ungrab: Sync after ungrab (fixes issues with runProcessWithInput)

CHANGES.md, XMonad/Actions/UpdateFocus.hs, XMonad/Actions/UpdatePointer.hs
Some people like their mouse pointer to move when changing focus with the keyboard, other people like their pointer to stay and focus to follow. xmonad(-contrib) supports both preferences, but imperfectly: The former requires using the XMonad.Actions.UpdatePointer contrib module, the latter (focusFollowsMouse) only reacts to CrossingEvent; the focus isn't updated after changing workspaces or layouts.
This adds an inverse of XMonad.Actions.UpdatePointer.updatePointer that immediately updates the focus instead.
Fixes: https://github.com/xmonad/xmonad/issues/108
I tested this a bit with a minimal config file and I hope the reporter and commenters of https://github.com/xmonad/xmonad/issues/108 will test it some more. I do not intend to use this myself.
- n/a I …
=> X.A.UpdateFocus: Add focusUnderPointer

XMonad/Prompt/OrgMode.hs, tests/OrgMode.hs
It's funny to notice this so late; I guess non-deterministic tests do have their drawback :)
So far, while parsing strings like "<ptn><more-letters>", the `getLast`
function immediately stopped on strings of the form "<ptn><whitespace>".
This may be a bit confusing given the functions name.  Strings of
the—perhaps artificial—form
"a +d f 1 +d f 2"
would be cut short and parsed as
Deadline "a" (Time { date = Next Friday, tod = Just 01:00 })
instead of the more intuitive
Deadline "a +d f 1" (Time { date = Next Friday, tod = Just 02:00 }).
This is readily fixed by applying the `go` parser as often as possible,
only returning the longest list, and then pruning eventual leftovers at
the end of the string.  Since we were already invoking `dropWhileEnd` to
trim whitespace before, the added …
=> X.P.OrgMode: Fix behaviour of getLast

CHANGES.md, XMonad/Layout/MultiToggle.hs
I'm entirely aware that the approach I have taken here is pretty hideous, and as such will probably never be accepted into xmonad-contrib. The thing is that no matter how hard I tried I could not figure out another way to provide this functionality. I'm putting this here in the hopes that someone can come up with a better way, or perhaps to get confirmation that there is no real way around the gross hack that I've added here.
=> X.L.MultiToggle: Add function to query toggle state

CHANGES.md, XMonad/Actions/WindowBringer.hs
A new field `windowFilter` was added to the config, which allows the user to provide a function which will decide whether each window should be included in the window bringer menu.
manually, ...) and concluded: I've been using this in my config for a couple of years with no issues. No testing was done with xmonad-testing, but I don't think it is necessary.
=> X.A.WindowBringer: Add a filter function to config

CHANGES.md, XMonad/Util/Loggers.hs
This works like `logTitles`, but gets an explicit screen to log the window
titles on.  This may be useful when having status bars for each screen
that show all windows on their respective visible workspaces.
manually, ...) and concluded: It's a trivial extension of `logTitles` and I've confirmed manually that this work for me.  It might be conceivable to property test this, as we are only accessing internal state, but I did not deem this necessary in this case.
- [n/a] I updated the `XMonad.Doc.Extending` file (if appropriate)
=> X.U.Loggers: Add `logTitlesOnScreen`

XMonad/Layout/Spacing.hs
These should be undeprecated because:
- The suggestion to use `spacingRaw` is pretty ridiculous; the interface to spacingRaw is very general and flexible, which is great, but I think that most people probably do not need all of that flexibility, and one of these convenience functions may suit their needs better.
- There is precendent for having convenience functions like these
=> Undeprecate spacing convenience functions

CHANGES.md, XMonad/Layout/Spacing.hs
Update the X.L.Spacing docs, as a lot of people seem to have trouble
using that module.
- X.L.Spacing: Remove link to backwards compatibility section
This has been removed already, so remove the link and move the
undeprecated functions out of there.
- CHANGES.md: Mention X.L.Spacing undeprecations
- X.L.Spacing: Reorder export list
- X.L.Spacing: Extend documentation
Users are having trouble with this module all the time.  Now that
certain helper functions are undeprecated, we should tell users how they
may use them.  It is also worth explaining the scary-looking
`spacingRaw` command a bit further.
Related: https://github.com/xmonad/xmonad-contrib/pull/597 (cadb178819fa70b7fc83c69399c11030491de8b9)
manually, ...) and concluded: Doc changes; nothing necessary
- [n/a] I updated the …
=> Update X.L.Spacing documentation

CHANGES.md, XMonad/Prompt/XMonad.hs
Currently when creating an XMonad Prompt you are stuck with `XMonad:` as the title for the prompt.  Its nice to be able to create a prompt with custom commands that has a particular title. adds the `xmonadPromptCT` function which allows you to do this.
manually, ...) and concluded The `XMonad.Prompt.XMonad` currently has no unit or property tests. If you have any suggestions for strategies to add test coverage I would be happy to implement something.
=> add custom title to xmonad prompts

CHANGES.md, XMonad/Actions/WithAll.hs, XMonad/Doc/Extending.hs
Resolves https://github.com/xmonad/xmonad-contrib/issues/527
Adds `killOthers` function to `XMonad.Actions.WithAll`. Depends on https://github.com/xmonad/xmonad/pull/327
=> Adds killOthers function to Xmonad.Actions.WithAll

CHANGES.md, XMonad/Actions/Search.hs
This is mostly a cosmetic change. Removed search engines point to sites that do not exist anymore or their functionality has changed. 
=> Remove codesearch, isount and openstreetmap engines

CHANGES.md, XMonad/Layout/CenteredIfSingle.hs, xmonad-contrib.cabal
XMonad.Layout.CenteredIfSingle centers windows on screen as long as there is only a single window.
As soon as there are more than one windows, the modified layout is used as normal.
Small demonstration:
https://user-images.githubusercontent.com/5300871/139041003-a2ceb6ae-07d1-405d-9056-4001d14e8538.mp4
manually, ...) and concluded: Manual testing is sufficient, I've been using this for months
=> Add XMonad.Layout.CenteredIfSingle

CHANGES.md, XMonad/Prompt.hs
This is an analogue to Emacs's `transpose-chars` function (expect that
it does not take a universal argument), bound to its default keybinding.
manually, ...) and concluded: Manually, for now.  The transposing logic isn't that complicated, but the whole prompt machinery makes this kind of hard to unit/property test.
=> X.Prompt: Add transposeChars

CHANGES.md, XMonad/Hooks/WindowSwallowing.hs
ConfigureEvents may occur after a window has been deleted, an UnmapEvent
has already been sent (and thus xmonad already unmanaged the window),
but before a DestroyWindowEvent is caught by the eventHook.  For
example, this is the case when one uses smartBorders with a single
window (such that smartBorders is "active").  The ConfigureEvents
sensibly already have an empty stack (because the UnmapEvent has already
been received), which we then copy to the history.
Whenever a parent window has been found, the sensible thing to do is to
always restore it.  The fact that oldStack is Nothing simply encodes an
empty workspace and is thus something we definitely need to handle as
well.
Fixes: https://github.com/xmonad/xmonad-contrib/issues/638
manually, ...) and concluded: I've tested them manually …
=> X.H.WindowSwallowing: Fix single window getting lost

XMonad/Doc/Extending.hs
We've discussed this a bit on IRC, but here it goes again: since we have the tutorial, both X.D.Configuring and X.D.Extending lose a bit of their relevance.  In my opinion, the former is completely redundant now (and should perhaps be removed some other time) while the latter could now be used for more "advanced" configuration that still isn't quite writing ones own module.  This is an attempt to kickstart this.
The configurations on the wiki are quite old and mostly non-functional at this point.  Instead, we have a shiny new tutorial we can refer to. It contains links to actual maintainers configurations (complex they may be, at least they compile).
Since the tutorial is really the better place to start learning how to use xmonad, X.D.Extending can be the place for more "advanced" usage …
=> Start modernising X.D.Extending

CHANGES.md, XMonad/Util/EZConfig.hs
Adding missing `KeySym`s to `additionalKeysP` so it will work with modifier-only keybindings (e.g. `Shift-Alt`).
`additionalKeys` already works with those so I see no reason not to have the codes available.
manually, ...) and concluded: As the fix does not change and existing behavior I will check this manually after the updated version is available in Arch Repo
fixes #648
=> X.U.EZConfig: Add modifier keys' KeySyms

CHANGES.md, XMonad/Actions/WindowNavigation.hs
Update left and right navigation to behave correctly even if the currently saved position is directly on the edge of the focused
window.
This makes the L/R behavior consistent with U/D navigation.
How to reproduce the issue:
- configure Grid layout;
- open 4 terminals;
- navigate to the top-right terminal;
- open another terminal;
- immediately close it;
- try navigating left from the currently focused top-right terminal;
- observe navigation being "stuck".
Minimized configuration to test the issue:
```hs
{-# OPTIONS_GHC -fno-warn-type-defaults #-}
import XMonad
import XMonad.Config.Xfce
import XMonad.Hooks.SetWMName
import XMonad.Layout.Grid
import XMonad.Actions.WindowNavigation
main :: IO ()
main = do
myConfig <- withWindowNavigation (xK_k, xK_h, xK_j, xK_l) $
xfceConfig
{ terminal = …
```
=> X.A.WindowNavigation: fix navigation being "stuck" in certain situations

XMonad/Actions/GroupNavigation.hs, XMonad/Hooks/WorkspaceHistory.hs, XMonad/Util/ExtensibleState.hs, xmonad-contrib.cabal
Both of these hooks leaked memory on long running sessions.
To fix it I had to force the thunks stored on the hooks as the compiler wouldn't be able to see where they would be demanded as they depended on the user interaction. Now the graph looks like this.
The most polemic change on this PR is the inclusion of the `parallel` library as a dependency. I needed for the `Control.Seq` module which gave me combinators to force just enough of the `Data.Seq` and `[]` data types.
- [🗸] I've read [CONTRIBUTING.md](https://github.com/xmonad/xmonad/blob/master/CONTRIBUTING.md)
- [🗸] I've considered how to best test these changes (property, unit,
manually, ...) and concluded: It shows the memory improvements!
- [🗸] I updated the `CHANGES.md` file (None)
=> Fix memory leaks on `historyHook` and `workspaceHistoryHook`

CHANGES.md, XMonad/Layout/MagicFocus.hs
Instead of searching for the currently focused window across workspaces,
make it so there is never any window above focus on the Stack that is
given to the modified layout.
Closes #657.
=> X.L.MagicFocus: always use focused as master

XMonad/Actions/ConstrainedResize.hs, XMonad/Actions/EasyMotion.hs, XMonad/Actions/FlexibleManipulate.hs, XMonad/Actions/FlexibleResize.hs, XMonad/Actions/FloatKeys.hs, XMonad/Actions/FloatSnap.hs, XMonad/Actions/Navigation2D.hs, XMonad/Actions/NoBorders.hs, XMonad/Actions/TiledWindowDragging.hs, XMonad/Actions/UpdatePointer.hs, XMonad/Actions/Warp.hs, XMonad/Actions/WindowMenu.hs, XMonad/Hooks/ManageDocks.hs, XMonad/Hooks/PositionStoreHooks.hs, XMonad/Hooks/WorkspaceByPos.hs, XMonad/Layout/FixedColumn.hs, XMonad/Layout/LayoutHints.hs, XMonad/Layout/LayoutScreens.hs, XMonad/Prelude.hs, XMonad/Util/DebugWindow.hs
Since X11 is unlikely to get safe bindings anytime soon, I figured this was better than nothing.
Move the function from X.U.DebugWindow, where it was defined already.
This is a safe version of getWindowAttributes, returning a Maybe instead
of throwing an exception, in case the window attributes could not be
retrieved.
Whenever possible, prefer the safe wrappers withWindowAttributes or
safeGetWindowAttributes to getWindowAttributes.
Places where these are not applicable are limited to layouts, where
there is not good "default value" to give back in case these calls fail.
In these cases, we let the exception handling of the layout mechanism
handle it and fall back to the Full layout.
Fixes: https://github.com/xmonad/xmonad-contrib/issues/146
manually, ...) and concluded: it compiles...!
I'm …
=> Prefer safe alternatives to getWindowAttributes

CHANGES.md, XMonad/Hooks/BorderPerWindow.hs, XMonad/Util/ActionQueue.hs, XMonad/Util/ExtensibleConf.hs, xmonad-contrib.cabal
Here's a functionality that no existing extension covers: default border width is 4; a user wants `firefox` and `chromium` to have 0 border and `feh` to have border width 16. The border width is permanent and no need to change when switching between layouts. And the user wants to avoid any unnecessary visual effects, e.g., [window jumping](https://github.com/xmonad/xmonad-contrib/issues/316).
12 years ago, users first discussed this need [here](https://xmonad.haskell.narkive.com/130DKJDZ/how-to-make-a-window-floating-above-all-the-other-windows-and-border-less). Unfortunately, no working solution was provided. At the end of the discussion, _Magicloud_ said "the toggleBorder part does not work".
Recently I developed the same need, and asked the question in stackoverflow [Config No Border …
=> Add X.U.ActionQueue And X.H.BorderPerWindow

CHANGES.md, XMonad/Actions/TreeSelect.hs, XMonad/Util/Font.hs
Related to #208. Moving [MinXft](https://github.com/jaor/xmobar/blob/master/src/Xmobar/X11/MinXft.hsc) library and [xmobar's fallback fonts logic](https://github.com/jaor/xmobar/blob/master/src/Xmobar/X11/Text.hs) to XMonad prompts, tabs labels, etc. So now, for example, prompts are able to display text and emoji. You can specify fonts to use through comma-separated list.  It also requires manual bindings from the Xft library, because https://hackage.haskell.org/package/X11-xft doesn't have binding for vital `XftCharExists` function.
=> Fallback fonts

CHANGES.md, XMonad/Prompt/OrgMode.hs, XMonad/Util/EZConfig.hs, XMonad/Util/Parser.hs, XMonad/Util/Paste.hs, tests/EZConfig.hs, tests/Main.hs, xmonad-contrib.cabal
Inspired in part by the first draft of https://github.com/xmonad/xmonad-contrib/pull/651 (where the need for it arose again, which was not helped by `ReadP`s lack of discoverability), this is a parser combinator module for xmonad; based on `ReadP`, but hopefully a bit more intuitive to use.  This is especially with regards to how other combinator libraries work, as well as the interplay with normal `Control.Applicative` functions.  Plus, `Semigroup` and `Monoid` instances :)
This module provides a parser combinator library based on base's ReadP,
which aims to function more like other popular combinator libraries like
attoparsec and megaparsec.
In particular, the Alternative and Monoid instances are left-biased now,
so combinators like `many` and `optional` from Control.Applicative work
in …
=> New Module: XMonad.Util.Parser

XMonad/Hooks/ManageDocks.hs, XMonad/Layout/Gaps.hs, XMonad/Layout/Spacing.hs
Document the interaction between `avoidStruts` and layout modifiers that affect the screen rectangle. Fixes https://github.com/xmonad/xmonad-contrib/issues/665.
manually, ...) and concluded: no testing, documentation only
=> Document interaction of `avoidStruts` with the screen rectangle

XMonad/Util/SpawnOnce.hs
Document that most of the functions in `XMonad.Util.SpawnOnce` rely on `XMonad.Actions.SpawnOn.manageSpawn`. Also, reexport that function for convenience. Closes #663.
manually, ...) and concluded: documentation change
=> document need for `manageSpawn` in `SpawnOnce`

CHANGES.md, XMonad/Actions/DynamicWorkspaces.hs
`withWorkspace` prompt should use fuzzy matching if XPConfig includes `searchPredicate =
fuzzyMatch`. See details in https://mail.haskell.org/pipermail/xmonad/2021-December/015491.html
Fuzzy match did not work with the `withWorkspace` prompt. With the proposed change it does.
manually, ...) and concluded:  the change works with my xmonad.hs. (I confess complete Haskell ignorance).
=> withWorkspace honor fuzzyMatch

CHANGES.md, XMonad/Prompt/OrgMode.hs, XMonad/Util/Parser.hs, tests/OrgMode.hs
This patch fixes the date parsing issue currently when an entry like
`todo +d 22 01 2022` is used. I have added tests too which demonstrate
the current issue so that we can prevent future regression.
manually, ...) and concluded that my fixes work.
=> Fix date parsing issue for org mode plugin

CHANGES.md, XMonad/Hooks/ManageHelpers.hs, XMonad/Layout/BinarySpacePartition.hs
Hidden windows are now ignored by the layout so that hidden windows in the stack don't offset position calculations in the layout.
Also in X.H.ManageHelpers: added `isMinimized`
manually, ...) and concluded: I use the BSP layout with hidden windows present a lot and this patch is essential to me. At least one other person on the mailing list is also happy with it: https://mail.haskell.org/pipermail/xmonad/2021-May/015432.html
=> X.L.BinarySpacePartition: Ignore minimized windows

CHANGES.md, XMonad/Actions/FloatKeys.hs
keysMoveWindow takes a (Dimension, Dimension) which is a word32, which doesnt take negative numbers.
At the moment it works to just put a negative number in there, but the compiler shows warnings.
So this change should get rid of compiler warnings when doing `keysMoveWindow (0,-20)` for example.
=> keysMoveWindow: change signature type D to ChangeDim in XMonad.Actions.FloatKeys

CHANGES.md, XMonad/Config/Arossato.hs, XMonad/Config/Bluetile.hs, XMonad/Config/Dmwit.hs, XMonad/Config/Droundy.hs, XMonad/Config/Monad.hs, XMonad/Config/Prime.hs, XMonad/Config/Saegesser.hs, XMonad/Config/Sjanssen.hs, XMonad/Layout/IndependentScreens.hs
NOTE: I'm bad at writing things like this, so feel free to suggest improvements.
Now that the user configs are on the website, it is time to deprecate them.  At the same time deprecated X.C.Monad, which hasn't been updated since 2008 and X.C.Prime, which has confused users quite recently, thinking it to be a better starting place.
Fixes: https://github.com/xmonad/xmonad-contrib/issues/677
Fixes: https://github.com/xmonad/xmonad-contrib/issues/595
Related: https://github.com/xmonad/xmonad-web/pull/49
manually, ...) and concluded: Deprecation warnings work as expected.
=> Deprecate user and abandoned modules

flake.nix
Was no longer compiling, attribute `gitIgnoreSource` didn't exist, it was moved to `lib.gitignoreSource`.
manually, ...) and concluded: It works!
Not sure that last checkbox is relevant here.
=> Fix nix flake compilation.

CHANGES.md, XMonad/Util/Hacks.hs
Add a hook intended to be used with xmobar to auto reserve a space for trayer.
=> add to hacks: rough draft trayer resize event hook

CHANGES.md, XMonad/Layout/VoidBorders.hs
Added a new layout modifier `normalBorders` which resets the borders back to their normal values (read from borderWidth) so that it is possible to restore borders after using `voidBorders`, such as when the window is moved to a different workspace or the layout is changed.
=> X.L.VoidBorders: Add ability to reset borders for certain layouts

CHANGES.md, XMonad/Util/Hacks.hs
(these are the cleanups I mentioned in https://github.com/xmonad/xmonad-contrib/pull/643#issuecomment-1013843609)
Un-export trivial/useless definitions and adapt the generic versions of trayerPaddingXmobarEventHook to be more generally useful.
Related: https://github.com/xmonad/xmonad-contrib/pull/643#issuecomment-962661655
=> X.U.Hacks: Clean up tray padding hooks a bit

CHANGES.md, XMonad/Actions/Submap.hs, XMonad/Hooks/DebugEvents.hs, XMonad/Prelude.hs, XMonad/Util/NamedActions.hs, XMonad/Util/XUtils.hs
tl;dr: [screenshot] of the new behaviour.
I'm not quite happy with this, but the reason I'm posting it anyways is that I'm interested in feedback.  We could make this use X.U.NamedActions, which may be conceptually nicer and could make the specification of descriptions a bit cleaner.  This would, however, introduce a regression with regards to `submapNamed`—it could not be in X.U.NamedActions anymore, as we would need to import that module from X.A.Submap.  It may also not be clear which submap implementation is chosen when one specifies named actions via EZConfig (which is something that I haven't touched on at all here).
This technically introduces a regression with regards to the way that modifier masks are printed in X.U.NamedActions and X.H.DebugEvents. However, since this way of …
=> X.A.Submap: Add `visualSubmap`

XMonad/Hooks/ManageDocks.hs, XMonad/Layout/SubLayouts.hs
This started as an investigation of the root cause of https://github.com/xmonad/xmonad-contrib/issues/565, which was addressed by https://github.com/xmonad/xmonad-contrib/pull/621 without having a full understanding of why xmonad ends up in a busy loop.
What was going on:
* X.L.SubLayouts group update algorithm assumes no duplicities in the Stack, and results in multiplying those duplicities otherwise. Note that this is a reasonable assumption—duplicities in a Stack have no defined behaviour in xmonad (X11 can't place a window on a screen twice), so "fixing" this algorithm is a waste of time.
* X.L.Decoration creates windows which X.H.ManageDocks treats as possible docks, resulting in extra refresh whenever they appear.
* The extra refresh causes X.L.SubLayouts to multiply the …
=> X.H.ManageDocks: Avoid unnecessary refresh (loop) for decorations

CHANGES.md, XMonad/Actions/EasyMotion.hs, XMonad/Actions/Navigation2D.hs, XMonad/Hooks/StatusBar/WorkspaceScreen.hs, XMonad/Layout/IndependentScreens.hs, XMonad/Prelude.hs, XMonad/Util/Loggers.hs, XMonad/Util/PureX.hs, xmonad-contrib.cabal
`WindowScreen` is a type synonym for the specialized `Screen` type, that
results from the `WindowSet` definition in XMonad.Core. Having this type
defined and exported in a central module saves extension developers from
trying to reconstruct it, whenever the general `Screen i l a sid sd` is
not suitable.
Note: this should be moved to `XMonad.Core` in the next core release.
In a multi-head setup, it might be useful to have screen information of the
visible workspaces combined with the workspace name, for example in a status
bar. This module provides utility functions to do just that.
Closes #681
=> Export `WindowScreen` type and add a new module: `X.H.WorkspaceScreen`

CHANGES.md, XMonad/Hooks/ShowWName.hs, xmonad-contrib.cabal
This was mostly a test-drive for the simpleWindow part of  https://github.com/xmonad/xmonad-contrib/pull/685, but I figured that—since the code is already there—it wouldn't hurt to submit it as well.
Maybe the docs are a bit lacking, I don't know, but I didn't really know what else to write.
This is a reimplementation of X.L.ShowWName as a logHook, using the new
simpleWindow interface from 86b816ec5046ec09b911d48df282b7039a201dfc.
Fixes: https://github.com/xmonad/xmonad-contrib/issues/612
manually, ...) and concluded: it seems to work (:
=> Add XMonad.Hooks.ShowWName

.gitignore, NIX.md, flake.nix, xmonad-contrib.cabal
This allows users to use a file develop.nix to customize the devShell provided by the flake. This is useful if e.g. the user wants to have the haskell-language-server or other developer tools in the shell properly configured (correct ghc versions etc).
Here is an example develop.nix for haskell-language-server:
```
pkgs: devInputs: devInputs // {
nativeBuildInputs = with pkgs.haskellPackages;
[ cabal-install hlint ghcid ormolu implicit-hie haskell-language-server ];
}
```
=> Provide a mechanism by which users can customize the nix devShell

XMonad/Hooks/Rescreen.hs
=> Fix typo on the 'XMonad.Hooks.Rescreen' doc

XMonad/Util/SpawnOnce.hs
Just a simple doc change, but should make `X.U.SessionStart` more discoverable.
Closes #696.
manually, ...) and concluded: doc change
=> Have `X.U.SpawnOnce` point to `X.U.SessionStart`

CHANGES.md, XMonad/Util/DynamicScratchpads.hs, XMonad/Util/NamedScratchpad.hs
Supersedes/Closes: https://github.com/xmonad/xmonad-contrib/pull/662
This is a first stab at making X.U.NamedScratchpads a little bit more general (while trying as hard as possible to retain backwards compatibility :/).
Instead of using the scratchpads that the user specifies (as this will realistically just be "all of them"), create some extensible state for the scratchpads to reside in.
To ensure that this is done in a backwards compatible way, function signatures did not change and they instead just ignore the list of scratchpads given to them and the initialisation is done in the manageHook, which users already have to use anyways.
With the extensible state machinery in place[1], we are now able to seamlessly integrate dynamic scratchpad functionality into X.U.NamedScratchpad.  This …
=> X.U.NamedScratchpads: Add dynamic scratchpad capabilities

.github/workflows/haskell-ci-hackage.patch, .github/workflows/haskell-ci-hlint.patch, .github/workflows/haskell-ci.yml, .github/workflows/stack.yml, cabal.haskell-ci, xmonad-contrib.cabal
NOTE: I will prepare the same thing for the `xmonad` repo, but don't want to create too much noise with PRs.  After this is rubber-stamped I will just push it directly.
+ Prefer GHC 8.10.7 to 8.10.4, as versions seem to have stabilised now.
+ Add support for Stackage LTS 19, which ships with GHC 9.0.2.
+ Since a new version of 9.2 has been released, prefer 9.2.2 over 9.2.1.
Also, explicitly pass -XCPP to hlint; see [1].
[1]: https://github.com/ndmitchell/hlint/issues/1360
manually, ...) and concluded: CI passes
=> ci: Update supported GHC versions

CHANGES.md, XMonad/Actions/PerLayoutKeys.hs, xmonad-contrib.cabal
This adds a new module `PerLayoutKeys` based on `XMonad.Actions.PerWorkspaceKeys`, which allows conditionalizing keybindings based on the current layout. This was requested by someone in IRC.
manually, ...) and concluded: has to be manual
=> new module XMonad.Actions.PerLayoutKeys

xmonad-contrib.cabal
Removes a repeating word in a package synopsis.
I noticed this while walking through the project's Hackage page.
The typo appeared after #630.
=> Fix synopsis typo

XMonad/Actions/DynamicProjects.hs
Trivial fix for missing default argument.
manually, ...) and concluded: trivial docs fix, no tests required
=> Fix missing prompt configuration in DynamicProjects example

CHANGES.md, XMonad/Actions/RepeatAction.hs, xmonad-contrib.cabal
repeat last action
Implementation of a feature described in [issue 489](https://github.com/xmonad/xmonad-contrib/issues/489).
Adds an ability to remember and repeat the last performed action.
=> added Actions.RepeatAction 

CHANGES.md, scripts/build/build-with-cabal.sh, scripts/build/build-with-stack.sh
The testing repo was not a good location for them, and is now
deprecated. They are now in `scripts/build`, and will be documented
in the main repo's `INSTALL.md`.
=> migrate build scripts from xmonad-testing

NIX.md, flake.nix
See xmonad/xmonad#392.
This is the contrib half. Note that the nix build is expected to fail until the core half is merged.
=> Apply Patch in Nix Flake; Enable Configuration (Contrib Edition)

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs
My implementation of _NET_DESKTOP_VIEWPORT. I don't know how spaghetti it may be since I am not a seasoned haskeller. Part of what makes this so much bigger than the other functions is the sorting part since I don't know how to use the sort' that is already on the log hook of EwmhDesktops since it works with workspace sorting and I needed to sort tuples with workspaces. 
Also the sorting that I put in does not follow the X WorkspaceSort that is provided by the user since you'd have to now ask for instead of a workspace sort, a more general X WorkspaceCompare, which then gets ran though the mkWsSort and mkViewPortSort to both use the same comparison. But that is a question I'd rather ask first. Generally this is more code than what the other ewmh stuff takes to add.
Test this out with …
=> X.H.EwmhDesktops: Add `_NET_DESKTOP_VIEWPORT` support

CHANGES.md, XMonad/Prelude.hs, XMonad/Prompt/OrgMode.hs, XMonad/Util/Run.hs
This extends X.U.Run with an EDSL for spawning (external) processes.  I will let an example from the documentation speak for itself:
``` haskell
do url <- getSelection  -- from XMonad.Util.XSelection
proc $ inEmacs
>-> withEmacsLibs [ElpaLib "dash", ElpaLib "s", OwnFile "arXiv-citation"]
>-> asBatch
>-> eval (elispFun $ "arXiv-citation" <> asString url)
```
is essentially equivalent to (line breaks mine)
``` shell
/usr/bin/sh -c "emacs -L /home/slot/.config/emacs/elpa/dash-20220417.2250
-L /home/slot/.config/emacs/elpa/s-20210616.619
-l /home/slot/.config/emacs/lisp/arXiv-citation.el
--batch
--eval '(arXiv-citation \"<url-in-the-primary-selection>\")'"
```
See above.
This adds documentation for the new EDSL, as well as small fixes to existing docs.
Importantly, I've added myself as a …
=> Extend X.U.Run with an EDSL for spawning processes

XMonad/Hooks/EwmhDesktops.hs
#708 is incomplete because it doesn't add `_NET_DESKTOP_VIEWPORT` to `_NET_SUPPORTED`. This update makes that addition, which should make polybar happy. Closes #708.
manually, ...) and concluded: needs to be manual
=> Complete #708 by updating _NET_SUPPORTED.

XMonad/Layout/CenteredIfSingle.hs
Modified CenteredIfSingle to accept a second ratio, so that centered windows can be scaled in both directions.
=> CenteredIfSingle allow resizing in both dimensions

CHANGES.md, XMonad/Hooks/Modal.hs, XMonad/Util/Grab.hs, xmonad-contrib.cabal
An alternative to #213 based on L. S. Leary's work (https://gist.github.com/LSLeary/6741b0572d62db3f0cea8e6618141b2f). I didn't change much (_yet_) from the original draft, I just played around with the code and took it out for a spin. Now that I have some opinions on the code, I figured opening a PR would be better to concretely discuss how to best go forward with this. 
Here are the things I changed:
- I made the modes included use the keybindings from the given config, not from the default config. This seemed form me as a better UX. 
- I dropped `insertMode` and renamed `normalMode` to `noModMode` ( I don't particularly see the utility).
- I added loggers and made `setTo` run `refresh`, so the loggers are updated
Here are things that are still open:
> I'm running into problems with …
=> Add Modal Keybindings

XMonad/Hooks/Modal.hs
I had a little bit of time on my hands today (yay, food poisoning), so I figured I'd try my hands at hacking EZConfig support into X.H.Modal, as discussed in https://github.com/xmonad/xmonad-contrib/pull/703.  Worked out pretty well, I think.
Mostly small things, like making imports line up with the provided comments.  Also:
+ Rename mode' -> modeWithExit.  This seems like a better name for discoverability reasons.
+ Make the fields of Mode strict, because they have no reason not to, really.
Add support for EZConfig-style bindings while also maintaining some guarantees as to which type of representation we will store in the extensible state.  This means that parsing of the keys will happen no later than the call to `modal`.
Users can choose to use `mkKeysEz` or `mkKeysFun` to create a new …
=> X.H.Modal: Add EZConfig support

CHANGES.md, XMonad/Hooks/UrgencyHook.hs
As the XMonad config is commonly customized by saying
def { startupHook = ...
, manageHook = ...
, ...
}
It seems consistent to allow the same for an individual hook config:
let urgencyHook = def { suppressWhen = ...
, remindWhen = ...
}
behind them.
manually, ...) and concluded: this is configuration only change, if it compiles, it is good.
=> X.H.UrgencyHook: Default for DzenUrgencyHook and UrgencyConfig

XMonad/Util/Font.hs
I had copied it in from `WindowNavigation`, but it already got the import from `XMonad.Prelude`.
manually, ...) and concluded: not needed
=> silence warning about extraneous Data.Bits import

CHANGES.md, XMonad/Layout/SideBorderDecoration.hs, xmonad-contrib.cabal
New module that allows for having a configurable border position around
windows.  Originally found in a comment by L. S. Leary in [1].  Enough
people have requested this on IRC in recent memory to warrant a proper
module.
[1]: https://github.com/xmonad/xmonad/issues/152#issuecomment-362716434
-------
manually, ...) and concluded: Tested this manually; seems to work on every side.
=> New module: XMonad.Layout.SideBorderDecoration

CHANGES.md, XMonad/Prelude.hs, XMonad/Prompt/AppendFile.hs
Enhance `mkAbsolutePath` to support environment variables, then use it in XMonad.Prompt.AppendFile's `doAppend` so filespecs like `~/NOTES` and `$HOME/file.txt` are supported.
manually, ...) and concluded: manually tested in ghci
=> Use `mkAbsolutePath` in `doAppend` (XMonad.Prompt.AppendFile)

CHANGES.md, XMonad/Prompt/Pass.hs
As requested by @Maeda1 on IRC. The new functions, per standard Haskell convention, have a prime appended to their names.
manually, ...) and concluded: `Maeda` is testing them, but they should be by construction correct
=> Allow users to specify custom prompts

CHANGES.md, XMonad/Util/Loggers.hs
This is a small addition which enables to add logging for urgent windows. There might be a lot of room for improvement since those added variants looks almost exactly like `logTitles` and `logTitlesOnScreen`.
manually, ...) and concluded: Tested this manually, urgent windows are logged properly.
=> X.U.Loggers: Add variants of logTitle with urgent windows support

CHANGES.md, XMonad/Prompt/OrgMode.hs, tests/OrgMode.hs
Well, I started using this feature lately, so why not support it? :)
Add the ability to specify alphabetic (`#A`, `#B`, and `#C`) org-mode priorities[1] at the end of the input note.
[1]: https://orgmode.org/manual/Priorities.html
Add the trivial Arbitrary instance for Priority, extend the Arbitrary instance of OrgMsg, as well as some plumbing.  Also work in some unit tests for regression testing.
manually, ...) and concluded: I've both tested it manually, as well as extended the test suite to cover all new cases.
=> X.P.OrgMode: Add ability to specify priorities

CHANGES.md, XMonad/Prompt/Unicode.hs
This PR changes `X.P.Unicode` string type from `ByteString` to `String` to support Unicode
in descriptions. Closes #733.
`X.P.Unicode` allows you to work with Emoji in Unicode, but does not allow you to use
non-Latin characters in the description of these Emojis. `X.P.Unicode` works fine, but
cannot display such characters correctly.
See how to reproduce in #733.
Chose `String` instead of `Text` because I thought it was possible to do without an extra
dependency for `xmonad-contrib`. The branch is editable if you know how to add support
without dropping the `ByteString`.
=> `X.P.Unicode`: `BS` -> `String` to support Unicode descriptions

XMonad/Layout/WindowNavigation.hs
`configurableNavigation` in XMonad.Layout.WindowNavigation uses an opaque type `WNConfig` and provides three undocumented functions to create `WNConfig` values. Provide some documentation for them, so it at least makes some kind of sense.
Closes #748.
manually, ...) and concluded: doc change
=> Document `WNConfig`

.gitignore, NIX.md, flake.nix
Sister PR to: xmonad/xmonad#420
Makes corresponding changes to `flake.nix` and `NIX.md`, as well as some general improvements.
- N/A
=> Fixes and Workarounds in flake.nix, Documentation in NIX.md

XMonad/Doc/Extending.hs
Closes: https://github.com/xmonad/xmonad-contrib/issues/645
The second round of updates to X.D.Extending, so it's not so old and crufty anymore.  Still not completely done with the module, but getting there!
This is more ergonomic to use than the old-style headings; plus, the
generated Haddock is easier to read than just stating
"XMonad.Doc.Extending".
+ Refer to X.H.StatusBar whenever possible at the start.
+ Fix some small typos throughout the module.
Nowadays, removing keys is mostly done via removeKeys and removeKeysP,
so the documentation should reflect that fact.  This part is less
step-by-step instructive than the section about adding keys, but read in
succession it presents a way to deepen the newly acquired knowledge.
+ $keyAddDel can just be a side note in $keyDel, it does not …
=> X.D.Extending: Round Two

CHANGES.md, XMonad/Layout/BorderResize.hs
Until now it is not possible to change how many pixels near a border is considered "near enough", so that the window can be resized by dragging this border. This is especially frustrating on a touchscreen, where I would wish to have more than just 2 pixels to tap on for resizing windows.
This shoudl allow exactly that. Until now, you were stuck with 2 pixel wide borders for resizing. But now this value is not a global variable but instead a parameter for the borderResize layout modifier
=> made borderresize take a parameter

CHANGES.md, XMonad/Util/Scratchpad.hs
This is i) broken and ii) just the functionality of X.U.NamedScratchpad
rewrapped (and not necessarily improved upon) at this point.
With recent changes to the way named scratchpads work[1], we would have
to export internals of X.U.NamedScratchpad in order to restore
X.U.Scratchpad to its full functionality.  This does not seem worth it,
as the latter does not bring anything substantially new to the table.
Closes: https://github.com/xmonad/xmonad-contrib/issues/756
Related: https://github.com/xmonad/xmonad-contrib/issues/591
[1]: 3fc830aa09368dca04df24bf7ec4ac817f2de479
manually, ...) and concluded: Haddock and GHC say it's deprecated.
=> X.U.Scratchpad: Deprecate

XMonad/Layout/MouseResizableTile.hs
Very small and straightforward change, see the following post for context: https://www.reddit.com/r/xmonad/comments/xpzeg9/normalize_the_fraction_between_master_and_slave/
I've also included the SetSlaveFraction messages, because they could be used in a similar (albeit more complicated, as there are multiple slaves) fashion to create a function that normalizes all of the sizes (instead of just the fraction between master and slave).
=> expose more messages in MouseResizableTile layout

CHANGES.md, XMonad/Prompt/OrgMode.hs, XMonad/Util/Parser.hs
While not many of these more exotic combinators are used right now, it's still nice to have feature parity (i.e., everything that one could want from a basic parser) such that people don't have to add their own combinators, in case they want to use one that's not already implemented.
Most of these definitions are probably small enough to be inlined on their own, but tell GHC to try really hard regardless.  This is commonly done by other parser libraries as well; e.g., [1], so it shouldn't cause any issues either way.
[1]: https://hackage.haskell.org/package/parsers-0.12.11
Use the more aptly named `option` instead.
manually, ...) and concluded: Pretty much all definitions are small and just what other parsing libraries do.
=> X.U.Parser: Achieve feature parity with ReadP

XMonad/Util/SpawnOnce.hs
Sorry for the tiny doc change, but it annoyed me. :)
tl;dr: haddock module links need `"` not `'`.
<hr/>
This fixes the broken link on the [doc page for XMonad.Util.SpawnOnce](https://hackage.haskell.org/package/xmonad-contrib-0.17.1/docs/XMonad-Util-SpawnOnce.html) to SessionStart.
Haddock interprets 'XMonad.Util.SessionStart' as a (non-existent) function in "XMonad.Util", rather than as a module, and hence it links to:
https://hackage.haskell.org/package/xmonad-contrib-0.17.1/docs/XMonad-Util.html#v:SessionStart
which doesn't exist, rather than to:
https://hackage.haskell.org/package/xmonad-contrib-0.17.1/docs/XMonad-Util-SessionStart.html
Apparently, module links need " instead of '. (See:
https://haskell-haddock.readthedocs.io/en/latest/markup.html#linking-to-modules
)
manually, ...) …
=> Fix broken link in doc for XMonad.Util.SpawnOnce

CHANGES.md, XMonad/Hooks/DynamicProperty.hs, XMonad/Hooks/OnPropertyChange.hs, xmonad-contrib.cabal
I'm not married to either of these names; suggestions welcome.
This is the same module as X.H.DynamicProperty, just with (hopefully)
more discoverable names.
Closes: https://github.com/xmonad/xmonad-contrib/issues/588
manually, ...) and concluded: The deprecations show up correctly.
=> New module: XMonad.Hooks.OnPropertyChange

.github/workflows/haskell-ci-hackage.patch, .github/workflows/haskell-ci.yml, .github/workflows/nix.yml, .github/workflows/packdeps.yml, .github/workflows/stack.yml, XMonad/Layout/Groups/Examples.hs, XMonad/Util/Parser.hs, cabal.haskell-ci, xmonad-contrib.cabal
* https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ related changes
* drop usage of HVR's unmaintained apt repo
* test with GHC 9.4
=> CI maintenance (GHA deprecations, GHC 9.4)

CHANGES.md, XMonad/Prompt/OrgMode.hs, XMonad/Util/Run.hs
~~This is still a bit WIP in the sense that documentation and other fluff is missing, but it at least seems complete feature-wise.~~ This should now be ready to review.  Since someone asked me whether I could implement this, I figured it was best to open this to "public testing" as soon as possible.
This is already taken care of by execute and eval, so forcing it in progn only hampers composability.
This ensures that we always immediately expand the file path upon constructing an `OrgMode` record.  We thus do not have to do this in `mkOrgPrompt` anymore.
More formally, return whether the user cancelled the prompt or not. This is useful in case we want to do things only after a "successful" input.
Add orgPromptRefile and orgPromptRefileTo in order to refile entries after insertion. …
=> X.P.OrgMode: Add orgPromptRefile[To]

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs
Order workspaces based on the visibility, before collecting windows. `_NET_CLIENT_LIST_STACKING` is supposed to be in the focus order.
A fix for https://github.com/xmonad/xmonad-contrib/issues/771.  Issue contains a description of the problem.
=> EwmhDesktops: _NET_CLIENT_LIST_STACKING: In focus order

CHANGES.md, XMonad/Actions/TagWindows.hs, XMonad/Layout/IM.hs, XMonad/Prelude.hs, XMonad/Util/ExclusiveScratchpads.hs, XMonad/Util/NamedScratchpad.hs
Getting rid of another scratchpad module by introducing its functionality into NamedScratchpad.
It _works_, but sadly the implementation isn't quite as smooth as one would like it to be, so I'm posting it here as a draft while I think of more sensible ways to do this.
TODOs:
manually, ...) and concluded: Tested them manually for now—seems to work.  I don't know anyone who actually uses ExclusiveScratchpads though, so not sure this is enough.
=> X.U.NamedScratchpad: Add exclusive scratchpad capabilities

CHANGES.md, XMonad/Actions/Search.hs
I added the search engines for the AUR, Flora, nCatLab, ProtonDB, RosettaCode, Sourcehut, Steam, and the Void Linux Packages. I also reorganized the list alphabetically and added the entry for `wiktionary` which wasn't mentioned.
Those changes were motivated by
* The accessibility of diverse search engines, not only limited to standard one (as it was already the case with IMDb being on the list), and with a bias toward mathematics, coding and games.
* The appearance of other packages databases (here, the Arch and Void ones).
* The mention of the undocumented `wiktionary` function.
manually, ...) and concluded: it builds, it passes the tests and it works.
=> XMonad.Actions.Search: Added search engines

.github/workflows/haskell-ci.yml, .github/workflows/stack.yml, CHANGES.md, XMonad/Hooks/Focus.hs, XMonad/Hooks/WorkspaceHistory.hs, XMonad/Layout/Mosaic.hs, XMonad/Prompt/OrgMode.hs, XMonad/Util/PureX.hs, stack.yaml, xmonad-contrib.cabal
Now that Debian has 8.6, it's time to drop 8.4.
Contrib version of https://github.com/xmonad/xmonad/pull/430
+ A new stackage LTS is out with GHC 9.2.5, so test for this.
+ Update the haskell-ci jobs accordingly from 9.2.4.
Many instance declarations can now be derived either by DerivingVia or
GeneralizedNewtypeDeriving.
Debian stable is not on 8.6, which was always our guide as to which GHC
versions we want to support.
manually, ...) and concluded: compiles :)
=> Drop GHC 8.4

XMonad/Hooks/OnPropertyChange.hs
that's from my private config and has no referent here
fixes: #786 
manually, ...) and concluded: doc change
=> remove references to `baseConfig`

XMonad/Util/DebugWindow.hs
I have no idea what I was thinking when I wrote that code. While at it, just reused the code for ICCCM title which already assumes the client may have broken the rules (I think we have seen a case of `WM_NAME` being `UTF8_STRING`).
Rewrite `_NET_WM_NAME` handling to correctly process it as a `UTF8_STRING` property.
manually, ...) and concluded: must be done manually
=> fix EWMH titles

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs
This information is picked up by polybar's xworkspaces module and used
to re-group the workspaces by monitor. I (and others) find this super
confusing, but polybar doesn't not seem open to addressing it.
https://github.com/polybar/polybar/issues/2603
Opting in to the old behavior of not managing this property is one way
to work around it instead.
=> Add EWMH configuration to not set _NET_DESKTOP_VIEWPORT

CHANGES.md, XMonad/Actions/CycleRecentWS.hs, XMonad/Actions/CycleWindows.hs, XMonad/Actions/CycleWorkspaceByScreen.hs, XMonad/Actions/MostRecentlyUsed.hs, XMonad/Actions/Repeatable.hs, XMonad/Util/History.hs, xmonad-contrib.cabal
Note that I haven't tested these changes beyond seeing that they compile without warnings on GHC 8.8.4 and 9.2.4. I intend to do so, but I'll put it up here so others can also test or review it in the meantime, if they so wish. Commits follow:
These modules were duplicating a substantial amount of low-level code.
`X.A.CycleWorkspaceByScreen` had already separated most of the implementation details from the logic with `repeatableAction`; all that was left was to generalise it a little further, put it in a suitable place and express the other modules through it.
(for the below)
Alt+Tab style window switching. It can be pretty handy, and people are used to having it.
Given the existence of the other repeatable actions, it's quite a glaring omission.
=> Factor X.A.Cycle* modules; Write Alt+Tab style window switching

CHANGES.md, XMonad/Util/EZConfig.hs
This was discussed on IRC, and I thought it'd be a neat addition.
The obvious caveat (also mentioned in the documentation) is that this does not work for submap keys, as these are not transparently bound.  One could provide something like
``` haskell
additionalRemapKeysP :: [(String, String)] -> [(String, X ())] -> XConfig l -> XConfig l
```
which could sort of slurp some keys from the second argument, but this seems a bit patchworky to me, so I've left it at `remapKeysP` for now.
manually, ...) and concluded: manually tested this; don't think we can easily write property test for this.
=> X.U.EZConfig: Add remapKeysP

CHANGES.md, XMonad/Util/NamedActions.hs
Discarding keybindings may yield unintended behaviour when keybindings are added via combinators, instead of the `keys` field.  This makes the
combinators noncommutative, which is very counterintuitive.
Related: https://old.reddit.com/r/xmonad/comments/10g1v1r/deftogglestrutskey_not_working/
---
This is a PR because I don't use NamedActions and, though I've verified that this doesn't immediately break things with the simplest config, someone else should look at ti
---
manually, ...) and concluded: tested manually; seems to do the trick.
=> X.U.NamedActions: Do not discard all keybindings in addDescrKeys

CHANGES.md, XMonad/Util/EZConfig.hs
Per a discussion we had last November, this PR changes the fixity of `additionalKeys` and friends from the default (`infixl 9`) to `infixl 4`. This makes it possible to use `(++)` to concatenate lists within them without requiring extra parentheses, since `(++)` is `infixl 5`.
This should not affect existing configs.
manually, ...) and concluded: tested locally
=> Config modifiers `infixl 4` so you can use `(++)`

CHANGES.md, XMonad/Layout/FocusTracking.hs, XMonad/Layout/StateFull.hs, XMonad/Layout/TrackFloating.hs, xmonad-contrib.cabal
> `X.L.StateFull`'s `FocusTracking` and the eponymous `TrackFloating` were redundant, hence the former was slated for deprecation. However, the latter and its host module are somewhat poorly named; the layout modifier has little relation to floats. As such, it's renamed and rehosted, becoming the eponymous `FocusTracking`.
> 
> The redundant offerings in the original modules are redefined in terms of the new module where possible, and deprecated.
> 
> See: #418; comments on #253, #783.
The situation is a bit of a mess. This seemed like the best way to resolve it, but I'm open to other options.
=> Extract redundant layouts into new module: X.L.FocusTracking

CHANGES.md, XMonad/Util/Loggers.hs
This PR adds loggers to expose the X window classname of the current window. It adds the following, which each have an existing counterpart for logging window titles:
- `logClassname`
- `logClassnames`
- `logClassnames'`
- `logClassnameOnScreen`
- `logClassnamesOnScreen`
- `logClassnamesOnScreen'`
- `ClassnamesFormat(..)`
This is motivated by wanting to create statusbar output which provides the classname of the current window. `XMonad.Util.NamedWindows` provides both:
- `getName`, which provides the title of a window (e.g., "Home - BBC News"), and
- `getNameWMClass`, which provides the classname of the window (e.g., "chromium").
There are currently methods for fetching the former, but not the latter. The implementation here is identical to the existing code for the window title.
Note: …
=> Add loggers for window classname

CHANGES.md, XMonad/Hooks/StatusBar/PP.hs
Originally, `dynamicLogString` could have a bottom hidden in it and thereby crash the `logHook`. Under some circumstances (see #801) this could cause xmonad to get stuck. We now force the result, and `dynamicLogString` catches the exception and substitutes a message (currently `"_|_"`). Use `dynamicLogString'` for the old behavior.
Closes: #801 
manually, ...) and concluded: tested manually
=> `dynamicLogString` forces its result and recovers

CHANGES.md, XMonad/Actions/ToggleFullFloat.hs, XMonad/Hooks/EwmhDesktops.hs, xmonad-contrib.cabal
Fairly straightforward, just add two hooks for (un)fullscreening. There are multiple motivations for this:
* Users are calling for unfullscreened windows to revert back to their original location if they were floating.
* XMonad.Layout.Fullscreen uses some deprecated exports from XMonad.Hooks.EwmhDesktops and reimplements fullscreenEventHook.
This commit only adds the hooks. Neither of the motivations are dealt with yet, so the docs are a bit terse still.
---
Related: https://github.com/xmonad/xmonad-contrib/issues/456
Related: https://github.com/xmonad/xmonad-contrib/issues/394
Related: https://github.com/xmonad/xmonad-contrib/pull/626
---
The second motivation is still TODO: X.L.Fullscreen should be refactored to use this (probably in a separate PR because there's some legacy code I …
=> Add (un)fullscreen hooks and float-restoring toggleFullFloat action

XMonad/Layout/Decoration.hs
It turns out qutebrowser will place an entire `data:` URL in `_NET_WM_NAME`, up to at least 389K characters including newlines and possibly binary characters.
Clamping window titles to the first line, and to 2K chars because `defaultShrinker` is quadratic in the title length.
Closes #809 
manually, ...) and concluded: tested in my harness
=> Put a cap on window names

CHANGES.md, XMonad/Layout/CenterMainFluid.hs, xmonad-contrib.cabal
This is similar to 'ThreeColumns' layout but there is reserved spaces for left and right column. This layout is described in #803. 
manually, ...) and concluded: that can be manually tested.
=> Add CenterMainFluid layout

XMonad/Hooks/EwmhDesktops.hs
For docks that don't support `_NET_WM_STRUT` any more,
notably `xfce4-panel`.
Closes #808
=> add `_NET_WM_STRUT_PARTIAL` to `_NET_SUPPORTED`

XMonad/Util/DebugWindow.hs
At some point `peekCString` became locale aware. This is a double bug, since (a) `decodeString` was being applied to the result and (b) the locale might not be UTF-8, but the string being decoded always is.
The fix is to use `peekCAString` which bypasses the locale decode, then continuing to do UTF-8 decode.
manually, ...) and concluded: tested locally
=> fix double decode in `debugWindow`

CHANGES.md, XMonad/Layout/Magnifier.hs
behind them.
I've added another general combinator to XMonad.Layout.Magnifier, that allows setting up custom size both horizontally and vertically. `magnifyxy` is the new combinator, and the new implementations of magnifiers are `magnifierxy`, `magnifierxy'`, `magnifierxyOff`, and `magnifierxyOff'`.
Not sure if I am 100% on the names of the combinators.
This was mostly done to make it possible to make a `maximizeVertical` that defaults to `On`.
```hs
magnifierxy 1 1000 (Tall 1 (3/100) (1/2))
```
manually, ...) and concluded: The combinators work, and the MagnifyMore+MagnifyLess keybinds still work with magnifierxy.
=> Add magnifiyxy combinator to XMonad.Layout.Magnifier

XMonad/Prelude.hs
Will ship with GHC 9.8.
Fixes: https://github.com/xmonad/xmonad-contrib/issues/826
@geekosaur: Could you send me the warnings that are generated due to `-Wx-partial`? I'd like to fix at least *some* of them.
manually, ...) and concluded: That's what this PR is for :)
=> X.Prelude: Compatibility with base-4.18.0.0

CHANGES.md, XMonad/Actions/Search.hs
- feat(search): add nixos as searchEngine
- feat(search): add homeManager as searchEngine
(I've only skimmed contributing and docs, and haven't tested this, which I will ofc do before changing from draft)
behind them.
manually, ...) and concluded: not necessary here, e.g. some other individual search engine entries don't seem to get tested.
=> XMonad.actions.search: Add NixOS and home-manager searchEngines

CHANGES.md, XMonad/Prompt.hs
Fixes: https://github.com/xmonad/xmonad-contrib/issues/831
+ Add a new `prevCompletionKey` to `XPConfig`, in order to cycle backwards.
Bound to `S-<Tab>` by default.
+ Already handle null keystrings (times when only a modifier was
pressed) in `handleMain`, such that completions aren't cleared
prematurely.
+ Augment `nextComplIndex` (now `computeComplIndex`) with the ability to go
in an arbitrary 1-dimensional direction. As a result, that function,
as well as `handleCompletion` and `handleCompletionMain` now take an
additional `Direction1D` argument.
Based on: https://github.com/solomon-b/xmonad-contrib/tree/feature/scrolling-prompt-completions
Co-authored-by: Solomon Bothwell <ssbothwell@gmail.com>
manually, ...) and concluded: manually confirmed for this to work, but @l29ah should double …
=> X.Prompt: Allow for backwards cycling of completions

CHANGES.md, XMonad/Layout/Cross.hs
The module has badly bitrotted, and is in such a state that it's
unlikely anyone is using it currently. Better alternatives exist, so
just deprecating seems appropriate here.
Closes: https://github.com/xmonad/xmonad-contrib/issues/793
manually, ...) and concluded: Correctly shows me deprecation warnings
=> X.L.Cross: Deprecate

CHANGES.md, XMonad/Util/NamedScratchpad.hs
I added a logHook that ensures that only the most recent scratchpad is active on the workspace at any given time. When opening a new scratchpad, the previous scratchpad is moved to the corresponding scratchpad workspace.
Motivation: I use floating scratchpad to open terminals, notes, etc. quickly. Since `nsHideOnFocusLoss` hides scratchpad more often, then i intended to, the scratchpads can pile up very fast, which leads to the fact that I have to "dismantle" the stack of scratchpads manually. To prevent this, I now use this logHook. I thought I'd share it in case anyone has a similar workflow and is also interested.
I am a Haskell beginner, so please bear with me. I would be glad about feedback.
manually, ...) and concluded:  manually tested
=> introduce single active scratchpad hook

CHANGES.md, XMonad/Actions/GridSelect.hs, XMonad/Actions/Navigation2D.hs, XMonad/Actions/Prefix.hs, XMonad/Actions/ShowText.hs, XMonad/Actions/SwapPromote.hs, XMonad/Actions/WindowGo.hs, XMonad/Actions/Workscreen.hs, XMonad/Actions/WorkspaceCursors.hs, XMonad/Hooks/Minimize.hs, XMonad/Hooks/Place.hs, XMonad/Hooks/ServerMode.hs, XMonad/Hooks/StatusBar/PP.hs, XMonad/Layout/Combo.hs, XMonad/Layout/MultiColumns.hs, XMonad/Layout/OneBig.hs, XMonad/Layout/TallMastersCombo.hs, XMonad/Prelude.hs, XMonad/Prompt.hs, XMonad/Prompt/OrgMode.hs, XMonad/Util/EZConfig.hs, XMonad/Util/ExclusiveScratchpads.hs, XMonad/Util/Image.hs, XMonad/Util/Timer.hs
Fixes (hopefully): https://github.com/xmonad/xmonad-contrib/issues/830
It also makes way for #838 (with which we can even check if we got everything!)
(N.b.: so many good uses for non-empty lists that can't be changed due to backwards compatibility :/)
Fixes: https://github.com/xmonad/xmonad-contrib/issues/830
Related: https://github.com/xmonad/xmonad-contrib/pull/836
Where appropriate
=> Address all remaining `Wx-partial` warnings

XMonad/Prompt/Unicode.hs
This PR adds some additional context regarding the required UnicodeData.txt file needed for the `XMonad.Prompt.Unicode` module.
Closes #840 
manually, ...) and concluded: there are only documentation changes; no testing required
=> Add documentation for unicode prompt

CHANGES.md, XMonad/Config/Mate.hs, XMonad/Util/Ungrab.hs
Deprecate `XMonad.Util.Ungrab` as it is going to be moved to `XMonad.Operations` in https://github.com/xmonad/xmonad/pull/479
manually, ...) and concluded: Tested manually with a config that uses unGrab and removed the XMonad.Util.Ungrab import.
=> deprecate `XMonad.Util.Ungrab`

XMonad/Prompt.hs
It might be that the keypress does not have a valid stroke associated to it, but is still bound to an action (e.g., xK_Left an friends). In this case, we still want to execute it.
Closes: https://github.com/xmonad/xmonad-contrib/issues/845
manually, ...) and concluded: quick manual test
=> X.Prompt: Execute keypress when it has an action associated to it

CHANGES.md, XMonad/Layout/Named.hs, XMonad/Layout/Renamed.hs
I believe this common use-case for the deprecated X.L.Named should still be provided somewhere, rather than telling everybody to let-define this themselves.
The other one – `nameTail` – only has about 6 uses in publicly available configs (https://github.com/search?q=nameTail+path%3Axmonad&type=code), so I'm not adding that one but I'm happy to be convinced to add it too.
Related: 3bf9d80c40b9 ("XMonad.Layout.Named: Deprecate")
tested manually locally
=> X.L.Renamed: Provide "named" convenience alias

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs, XMonad/Hooks/ManageHelpers.hs
Useful for restoring browser windows to where they were before restart (which is something one should do several times a week as security updates get released).
been running this code for a few days (limited to the browser, as otherwise many apps would jump to the workspace they were last on)
=> X.H.{EwmhDesktops,ManageHelpers}: Add _NET_WM_DESKTOP-handling ManageHook

CHANGES.md, XMonad/Prompt.hs
Avoiding RAGE when one can't just use Return key in the normal mode like in vim.
=> X.Prompt: handle Return key in vim normal mode

CHANGES.md, XMonad/Layout/Circle.hs, XMonad/Layout/CircleEx.hs, XMonad/Layout/DecorationMadness.hs, XMonad/Layout/SubLayouts.hs, xmonad-contrib.cabal
X.L.Circle layout is somewhat nice, but it does not provide much possibilities for customization. This adds a new module, X.L.CircleEx, which is similar to X.L.Circle, but has some new features:
* Number of "master" windows can be adjusted. For example, with 0 master windows, all windows go in a circle, nothing in the center.
* It's possible to configure sizes of master window and slave window (as a portion of screen size).
* Size of each next slave window is slightly less than size of previous (configurable)
* It's possible to rotate whole setup clockwise / counterclockwise. For example, by default first slave window opens near right edge of the screen, but I like it to open near left top corner.
=> Add new module: X.L.CircleEx: advanced version of Circle layout

XMonad/Layout/TwoPane.hs, XMonad/Layout/TwoPanePersistent.hs
I went to use the `TwoPane` layout while trying out `xmonad`, and immediately ran into the problem that `Shrink` and `Expand` were shrinking my windows into negative width, which broke `alacritty`.
To investigate the problem, I started reading the `Layout.hs` from `xmonad/xmonad`, and noticed that the `Tall` layout applies a `min` and `max` to the respective widths: 
- https://github.com/xmonad/xmonad/blob/master/src/XMonad/Layout.hs#L77-L78
Applying this same approach to `Shrink` and `Expand` in the `TwoPane` layouts (tested in my own `xmonad.hs`) resolves this problem for me, but I am a beginner to `xmonad` and may be misunderstanding something. :blue_heart: 
manually, ...) and concluded: writing tests is probably beyond my spare time for now
=> Fix minimum widths for Shrink and Expand

XMonad/Prompt/Input.hs
Something I noticed when reading the documentation, the `XPConfig` argument is missing from the usage example.
manually, ...) and concluded: N/A
=> Fix Xmonad.Prompt.Input usage example

XMonad/Prompt.hs
I am playing with using the key bindings to modify the input, and when trying to change the input to the next [or previous] completion in the currently available completions, I needed `getCurrentCompletions` and `selectedCompletion` to be available.  I have additionally added `setCurrentCompletions`, but if we don't want to export that, I'm happy to remove that from the PR.
I am new to Haskell, maybe I'm missing another way to do this.
manually, ...) and concluded: N/A
=> XMonad.Prompt: export getCurrentCompletions (and setCurrentCompletions)

XMonad/Hooks/EwmhDesktops.hs
`EwmhFullscreen` unconditionally sinks windows in response to a `_NET_WM_STATE` root window message removing `_NET_WM_STATE_FULLSCREEN`. Unfortunately, at least some versions of either the Gtk or GNOME libraries send this on startup while restoring a window's last known state, which means a `manageHook` `doFloat` will be undone.
This change ignores the remove if the window is not fullscreen.
A followup issue, #865, has been added for the follow-on problem that the floating state of a window is not restored on removal of the fullscreen state.
Closes: #820
manually, ...) and concluded: a user is already using this change successfully
=> only sink window if actually fullscreened

XMonad/Prompt.hs
While reading this documentation, I noticed a few of these typos.
manually, ...) and concluded: N/A
=> X.P: Fix some typos in comments

CHANGES.md, scripts/build/build-with-cabal.sh
The current script fails in case the project files are in `$XDG_CONFIG_HOME/xmonad/`, it tries to read them from `$XDG_CONFIG_HOME` directly.
=> Fix build-with-cabal.sh when XDG_CONFIG_HOME is defined

XMonad/Layout/AutoMaster.hs, XMonad/Layout/CenteredMaster.hs, XMonad/Layout/Column.hs, XMonad/Layout/IfMax.hs, XMonad/Layout/TabBarDecoration.hs, XMonad/Util/Rectangle.hs
This pull request fixes a few typos that I found while browsing the documentation on Hackage.
manually, ...) and concluded: N/A
=> X.*: Fix typos

CHANGES.md, XMonad/Util/EZConfig.hs
This reverts part of 42179b8625d83b2cd3c3a35da84de6f6c0dea6d6, which effectively changed the duplicate check from `>1` to `>=1`.
=> X.U.EZConfig: Fix checkKeymap warning that all keybindings are duplicate

CHANGES.md, XMonad/Actions/Profiles.hs, xmonad-contrib.cabal
This PR adds a new module used for grouping workspaces, thus expanding upon the "workspace per action" philosophy.  
Features of Profiles:
- filtering workspaces per Profile (both when navigating through workspaces and on a bar)
- adding keybindings per Profile
- adding workspaces from other Profiles to the current one
- a history hook that remembers workspaces per Profile
manually, ...) and concluded: tested it by using it extensively
for a year on my personal and work laptops
=> New module: X.A.Profiles

.github/workflows/haskell-ci-hackage.patch, .github/workflows/haskell-ci.yml, xmonad-contrib.cabal
(automatic PR by https://github.com/liskin/xmonad-maintenance)
=> ci: Regenerate haskell-ci

CHANGES.md, XMonad/Hooks/ManageHelpers.hs
Very similar to `isDialog`, `isNotification` checks for the `_NET_WM_WINDOW_TYPE_NOTIFICATION` value in the `_NET_WM_WINDOW_TYPE` property.
It is a rather trivial predicate.  I do not see any examples of how to test those.
`isDialog` has no tests either.
So no tests :(
=> X.H.ManageHelpers: `isNotification` predicate

CHANGES.md, XMonad/Hooks/StatusBar.hs
This change allows dynamic status bars to pull information out of the X monad, which can be really useful for status bars. For instance, you can now query the screen width in order to set the width of status bars appropriately.
Existing configurations may need to be updated in order to lift an `IO StatusBarConfig` to an `X StatusBarConfig`. This can be done using either the `io` function provided by `XMonad.Core`, or `liftIO` from `base` in `Control.Monad.IO.Class`
- https://hackage.haskell.org/package/xmonad-0.18.0/docs/XMonad-Core.html#v:io
- https://hackage.haskell.org/package/base-4.19.1.0/docs/Control-Monad-IO-Class.html#v:liftIO
manually, ...) and concluded: this is a minimal change to the types of some functions which does not break any existing tests. I have used these changes in …
=> Update StatusBar library to use the X monad instead of IO.

xmonad-contrib.cabal
Update bounds of `time` to allow the new 1.14 release.
manually, ...) and concluded: build with `--constraint='time == 1.14'` passed locally
=> update time to <1.15

CHANGES.md, XMonad/Prompt/OrgMode.hs, tests/OrgMode.hs
manually, ...) and concluded: Extended the unit and property tests for X.P.Orgmode; they all run through
=> X.P.OrgMode: Add time spans

CHANGES.md, XMonad/Actions/Search.hs, XMonad/Actions/WorkspaceNames.hs, XMonad/Prompt.hs
When using `XMonad.Prompt` for multiple (8+) different use cases in my configuration, I never once needed a command history.
The default of reading and writing a file for the command history opaque to the user is strange to me, and each prompt is sharing and replacing the same `prompt-history` file... but I digress.
My feature request is to stop that behavior, where `historySize = 0` didn't cut the mustard since `prompt-history` is still reading and writing on every prompt.
~This pull request adds `historyRead` and `historyWrite` configuration options to `XPConfig`, allowing users to write something like:~
```haskell
...
, historyRead = \cacheDir -> return empty
, historyWrite = \history cacheDir -> return ()
...
``` 
~This could open up functionality for using other state for a command …
=> X.P: Add escape hatch for preventing X.P IO

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs, XMonad/Hooks/FloatConfigureReq.hs, XMonad/Util/Hacks.hs, xmonad-contrib.cabal
A fix, a tool for workarounds, and a workaround:
More specifically, ignore `ClientMessageEvent`s for unmanaged windows. Steam likes to send `_NET_ACTIVE_WINDOW` requests for all its windows, including override-redirect ones, which used to result in an invocation of `windows` with a no-op Endo—equivalent to a call to `refresh`. But this refresh makes Steam close its menus immediately.
Fixes: https://github.com/ValveSoftware/steam-for-linux/issues/9376
Fixes: https://github.com/xmonad/xmonad/issues/451
Implements a replacement event handler for `ConfigureRequestEvent` to work around misbehaving client applications such as Steam, rxvt-unicode and others that try to restore their absolute window positions. Primarily motivated by the Steam client being almost completely unusable in xmonad …
=> Fixes/workarounds for Steam client menus/flickering

CHANGES.md, XMonad/Actions/Submap.hs
I did not see any way to display the submap bindings in a different order. I created a general function that takes a sorter for the descriptions (`visualSubmapSorted`).
The change from `zipWith` to `map . zip` showed no noticeable performance effects.
manually, ...) and concluded: Manually tested; have observed no issues.
=> Add a method to re-sort keys for visualSubmap

.github/workflows/haskell-ci.yml, xmonad-contrib.cabal
(automatic PR by https://github.com/liskin/xmonad-maintenance)
=> ci: Regenerate haskell-ci (add GHC 9.10)

CHANGES.md, XMonad/Layout/Columns.hs, xmonad-contrib.cabal
This layout organizes windows in columns and allows to move/resize them in every direction. This layout is showcased here: https://jeancharles.quillet.org/posts/2024-05-02-Columns-a-new-XMonad-layout.html
I was reluctant to send this layout in a PR because I'm not sure I'd have time to maintain it outside my main configuration. But I've been told that some people might be volunteers to maintain it :slightly_smiling_face:  So here it is.
Something that might be annoying is that the parameter to toggle between wide screen and small screen is currently hardcoded. As the layout lives in my config, this is not a problem for me but it might be for others. I can make it configurable if needed tho.
=> Add a new layout Columns

CHANGES.md, XMonad/Hooks/ScreenCorners.hs
In XMonad.Hooks.ScreenCorners, previously only corner is supported, now support for top and bottom edges is added. This is similar to Hot Edge shell extension in GNOME.
I could add support for SCLeft, SCRight too, if it's desired. I thought I'd ask for a review on this first.
I did manual test on this added feature.
SCTop and SCBottom works. They also with with corner specifier when the corner and edge overlap.
=> XMonad.Hooks.ScreenCorners: Add support for edges

CHANGES.md, XMonad/Actions/GridSelect.hs
In the original code, when a GridSelect is shown, user has to use a keyboard to cancel it (ESC key by default). With this field added, when it is set to True, mouse click on empty space can cancel the GridSelect.
When user trigger a GridSelect action using mouse, this change makes it easier to cancel the Grid, without reaching to the keyboard.
I have tested the code manually. The default setting preserves the original behavior. User has to opt-in to get the new feature, to reduce surprises.
To test the new behavior,
```haskell
import XMonad.Actions.GridSelect
myGoToSelected = goToSelected def { gs_cancelOnEmptyClick = True }
-- try it with a key binding
, ("M-<Space>", myGoToSelected)
```
=> XMonad.Actions.GridSelect: added gs_cancelOnEmptyClick field

CHANGES.md, XMonad/Actions/WindowBringer.hs, xmonad-contrib.cabal
A convenient way to copy a window to the current workspace.
=> X.A.WindowBringer: Add copyMenu

CHANGES.md, XMonad/Actions/WindowNavigation.hs, tests/Main.hs, tests/WindowNavigation.hs, xmonad-contrib.cabal
Previous version of WindowNavigation just got "stuck" on floating windows, switching back and forth between floating window and tiled window underneath. This was because "magic point" was left in the same position and thus next navigation commands selected the same windows over and over again. Now the "magic point" is moved around such that it doesn't overlap with the previously selected window, and there are more complicated rules to make navigation between floating and tiled windows more natural.
The original behavior of navigating between tiled windows is preserved almost precisely (the tree-like layouts - which should be overwhelmingly the most popular ones - will have exactly the same behavior, the only differences might be in some convoluted custom layouts).
Previous version of …
=> X.A.WindowNavigation: better handling of floating windows and Full layout

XMonad/Actions/UpKeys.hs, xmonad-contrib.cabal
I've known about [this stackoverflow](https://stackoverflow.com/a/11308086) post for a while, but seemingly the code has never made it to contrib. I think that it could come in handy once in a while, so why not add it?
manually, ...) and concluded: I tested the extended example and things seem to work nicely; no actual tests (yet‽)
TODO
=> X.A.UpKeys: Init

CHANGES.md, XMonad/Actions/DynamicProjects.hs
No longer autodelete projects when switching to another project from an empty workspace. This fixes #902 where static workspaces would be deleted when switching to a dynamic project. Moreover, it's a more intuitive behaviour, where the user can decide when to close a project.
I considered adding a function to delete projects, but upon further reflection, I realized it's unnecessary and could cause issues. In fact, the only projects stored in the state are those statically defined in `xmonad.hs` (the truly dynamic projects are just [dynamic workspaces](https://hackage.haskell.org/package/xmonad-contrib-0.18.1/docs/XMonad-Actions-DynamicWorkspaces.html)), and deleting them would render them unusable.
To close projects, the existing `removeWorkspace` function (and similar) from the …
=> X.A.DynamicProjects: No longer autodelete dynamic projects

XMonad/Layout/OnHost.hs
I hope I did this right.
Fixes: https://github.com/xmonad/xmonad-contrib/issues/899
**I have not tested this**, so I'd be very glad if other people could do that for me! :)
@cacharle
TBD/maybe not even necessary.
=> X.L.OnHost: Query gethostname if $HOST lookup fails

flake.nix
Nix url litterals are being depricated in flake inputs and fails to build on
never versions. I've just quoted them so it keeps building.
Signed-off-by: Christina Sørensen <christina@cafkafk.com>
=> fix: deprecated url literals

CHANGES.md, XMonad/Actions/PhysicalScreens.hs, XMonad/Hooks/Rescreen.hs
The changelog says it all:
> * `XMonad.Hooks.Rescreen`
>
>   - Allow overriding the `rescreen` operation itself. Additionally, the `XMonad.Actions.PhysicalScreens` module now provides an alternative implementation of `rescreen` that avoids reshuffling the workspaces if the number of screens doesn't change and only their locations do (which is especially common if one uses `xrandr --setmonitor` to split an ultra-wide display in two).
>
>   - Added an optional delay when waiting for events to settle. This may be used to avoid flicker and unnecessary workspace reshuffling if multiple `xrandr` commands are used to reconfigure the display layout.
Well, almost all. One commit message digs a bit deeper:
> X.A.PhysicalScreens: Add rescreen alternative to avoid ws reshuffle
>
> Probably a very …
=> X.H.Rescreen, X.A.PhysicalScreens: Add facilities to avoid (some) workspace reshuffling

CHANGES.md, XMonad/Layout/NoBorders.hs
Previously, it was necessary to use `borderEventHook` to make sure the `alwaysHidden`/`neverHidden` lists are garbage collected when a window is destroyed, but this was largely undocumented. Since xmonad v0.17.0, the DestroyWindowEvent is broadcast to layouts, so we can just use that instead and deprecate the event hook.
I'll be running with this for a while and see if everything's okay but it's pretty trivial, it should be okay.
=> X.L.NoBorders: Listen to DestroyWindowEvents and garbage collect

XMonad/Actions/OnScreen.hs, XMonad/Hooks/ScreenCorners.hs
Auto-format both my modules `OnScreen` and `ScreenCorners` with HLS. No other (functional) changes were done.
=> Auto-format `OnScreen` and `ScreenCorners` to HLS

.github/workflows/haskell-ci.yml, .github/workflows/stack.yml, CHANGES.md, XMonad/Hooks/DebugEvents.hs, XMonad/Prelude.hs, XMonad/Util/EZConfig.hs, xmonad-contrib.cabal
Add XF86WLAN to EZConfig.
Closes #27.
=> add XF86WLAN special key

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs, XMonad/Layout/IndependentScreens.hs
This adds a `setEwmhSwitchDesktopAction` function to customize how switching to the desired workspace is done when handling a _NET_CURRENT_DESKTOP request. The motivation for this was that commands using the EWMH fuctionality such as `wmctrl -s` pulled workspaces to the wrong screen in certain cases when using the `X.L.IndependentScreens` module, instead of making them active on the screen that they belong on, but the behavior seemed to be a sensible default since use of that module is not mandatory.
With the new function I changed the action to the following:
`action workspaceId = viewOnScreen (unmarshallS workspaceId) workspaceId`
This no longer pulls the workspace to the wrong screen when it is hidden, and it is on a screen that does not contain the current workspace, this is also used …
=> X.H.EwmhDesktops: Add customization for handling the _NET_CURRENT_DESKTOP requests

CHANGES.md, XMonad/Util/NamedScratchpad.hs
Fix unintended window hiding in `nsSingleScratchpadPerWorkspace`
The refactoring that introduced `nsHideOnCondition` caused a misbehavior in  
`nsSingleScratchpadPerWorkspace`, leading to unintended window hiding.  
Now, when opening a new scratchpad, only the previously active scratchpad  
is hidden.
=> fix unintended window hiding

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs, XMonad/Layout/IndependentScreens.hs
This PR adds a ManageHook version for `focusWindow'`. The example use case for this would be using it as an activate hook 
when using the *X.H.EwmhDesktops* module together with *X.L.IndependentScreens*.
manually, ...) and concluded: that manual testing is enough, and it functions as expected.
Building with the pedantic flag did not add new errors.
=> X.L.IndependentScreens: Add doFocus' ManageHook.

CHANGES.md, XMonad/Prelude.hs
I've been using Menu key to launch terminal for years; for some reason only now I realized it is not supported by X.U.EZConfig.
=> X.U.EZConfig: support "<Menu>" for xK_Menu key.

xmonad-contrib.cabal
Add support for containers-0.8, per packdeps.
manually, ...) and concluded: compiled locally, otherwise CI
=> support containers-0.8

CHANGES.md, XMonad/Hooks/EwmhDesktops.hs, XMonad/Layout/IndependentScreens.hs
The default assignment of hidden workspaces to the current screen is a good default, but it is not always desired.
An example for this would be a configuration that uses independent screens, because in that context workspaces
belong to certain screens which the *EWMH* module can't and won't consider when using the default behavior.
As far as I am able to tell the *EWMH* specification does not prescribe how hidden workspaces should be
assigned to screens, therefore I believe allowing customization is acceptable.
manually, ...) and concluded: That since the modification is nested in a function that returns `X ()` manual
testing is the only option. I am currently using this modification in my window manager and it works as expected.
=> X.H.EwmhDesktops: Add setEwmhHiddenWorkspaceToScreenMapping function.

CHANGES.md, XMonad/Util/XSelection.hs
I needed a function for querying the clipboard for the purpose of customizing my prompts and I thought it might be a good addition to `XSelection`.
This function allows querying the X clipboard, which is more commonly used than the primary selection.
The code for `getSelection` and `getClipboard` would be very similar and are factored into a `getSelectionNamed` internal function.
`getSecondarySelection` is also added to make the X selection support
more complete and to avoid exposing `getSelectionNamed`.
=> X.U.XSelection: Add 'getClipboard'

xmonad-contrib.cabal
`time-1.15` was recently released.
manually, ...) and concluded: tested locally with `--constraint=time==1.15 --allow-newer=time`
=> support time-1.15

CHANGES.md, XMonad/Actions/Search.hs
Added `multiChar`, `combineChar`, and `prefixAwareChar` as slightly generalised versions of `prefixAware` and `(!>)` that allow specifying the character that separates a search engine's prefix with the query when combining engines.
manually, ...) and concluded: Tested `multiChar` manually and made sure that I didn't accidentally destroy `(!>)` et al
=> X.A.Search: Add multiChar, combineChar, and prefixAwareChar
