xmonad/xmonad-contrib

- XMonad/Hooks/ScreenCorners.hs
It is needed because other windows can cover ours corner windows.
> Add layout hook for ScreenCorners.

- CHANGES.md
In order to get the behavior I had with `updatePointer (Relative 0.5 0.5)`, I have to use `updatePointer (0.5,0.5) (0,0)`.
> Fix updatePointer equivalence table.

- XMonad/Hooks/DynamicBars.hs
Hey! So some weeks ago I asked about adding some new functionality to the `DynamicBars` module, discussed here #43, and I ended not refactoring to the ideal goal but felt I would share the progress that I had. Let me know if I can improve this and possibly a roadmap to the ideal addition. Thanks!
tag: @mathstuf @aavogt
> DynamicBars: Add new multiPPFormat function

- CHANGES.md
- XMonad/Layout/SortedLayout.hs
- xmonad-contrib.cabal
A new LayoutModifier that sorts a given layout by a list of properties. The order of properties in the list determines the order of windows in the final layout. Any unmatched windows go to the end of the order.
> New SortedLayout module.

- XMonad/Config/Desktop.hs
- XMonad/Config/Gnome.hs
- XMonad/Config/Kde.hs
- XMonad/Config/Mate.hs
- XMonad/Config/Xfce.hs
> Update XMonad.Config.Desktop for 0.12 ManageDocks

- XMonad/Layout/Stoppable.hs
As discussed on the mailing list <CAF_c+NzToROErHadWRv7omtrh3SO6_W_PwcvUYW6B-Uz6-YN3Q@mail.gmail.com>
> Add note about when Stoppable does not work.

- XMonad/Config/Azerty.hs
Replace w by z to switch/move between screens.
> Switch/Move to physical/Xinerama screens 1, 2 or 3

- CHANGES.md
- XMonad/Prompt/Unicode.hs
- xmonad-contrib.cabal
I have been using this code locally for years now, and it turned out to
be quite useful in many cases, so I thought it is about time to submit
it to the repository.
> Add XMonad.Prompt.Unicode

- XMonad/Actions/WindowBringer.hs
@geekosaur @byorgey  This is just #98 under a different branch name
> X.A.WindowBringer: Add a config object with a X.C.Default implementation 

- XMonad/Actions/WorkspaceNames.hs
(a cleaner version of #103, possibly)
> X.A.WorkspaceNames: add get(Current)WorkspaceName

- CHANGES.md
- XMonad/Actions/UpdatePointer.hs
Sometimes cursor was stuck in one of the corners.
> UpdatePointer bugfix.

- XMonad/Prompt/Pass.hs
Trivial typo fix on X.P.Pass documentation
> X.P.Pass doc typo

- CHANGES.md
- XMonad/Hooks/FadeWindows.hs
- XMonad/Hooks/WallpaperSetter.hs
- XMonad/Layout/Mosaic.hs
- xmonad-contrib.cabal
Fixes #235 
Tested with multiple versions of GHC
> update to work with GHC 8.4.1

- CHANGES.md
- XMonad/Hooks/EwmhDesktops.hs
Fixes #216
See CHANGES.md and #216
> Remove gnome-panel hack from ewmh desktop code

- CHANGES.md
- XMonad/Layout/Grid.hs
closes #223 
I'll merge this in a week or so if nothing comes up.
See issue for full detail.
- Tested against current git xmonad as my system xmonad-contrib.
> Fix to X.L.Grid as per issue #223

- XMonad/Layout/MultiToggle.hs
Updated a doc that was missing some information that I would have found useful.
Minor doc change, so it doesn't update CHANGES.
> X.L.MultiToggle: Doc improvement

- XMonad/Actions/GroupNavigation.hs
> Actions.GroupNavigation: fix bad import

- CHANGES.md
- XMonad/Prompt/Pass.hs
> Make XMonad.Prompt.Pass traverse symlinks for its tab completion

- CHANGES.md
- XMonad/Prompt/Pass.hs
> Add XMonad.Prompt.Pass.passGenerateAndCopy

- XMonad/Layout/TallMastersCombo.hs
Each non-combinator sub-layout can contain one focused window, and this window will keep focused after switching to other sub-layouts. Two messages were added for switching between the focused windows across all sub-layouts.
> New Feature for TallMastersCombo: Switch between Focused Windows across All Sub-layouts

- XMonad/Actions/Search.hs
Add ebay function
Was looking over my xmonad.hs and found this. Been using for quite some time. 
Thought it could be useful to others.
Tested on my own environment.
If ok, ill update CHANGES file
Thank you for the continued support!
Thanks,
Dave
> Add Ebay Function to X.A.Search

- XMonad/Hooks/WindowSwallowing.hs
In rare cases, there was an issue where the WindowSwallowing module failed to store the window stack correctly. Because of this it could happen that after closing a window that swallowed another, a unrelated window was unmapped. This PR fixes that issue by checking if the stored stack is in the expected state, and falling back to a simpler way of restoring the window if not. In these cases, the window is not guaranteed to be positioned exactly where the old child-window was, but that issue seems unavoidable if we failed to store the position of said child window previously. In most cases, this PR does not affect the behaviour.
> Fix rare issues with windows wrongly dissapearing after windowswallowing

- XMonad/Config/Example.hs
I found a small mistake in the example and decided to fix it. I'm new, don't swear) Please, review my changes.
I tested this on my setup, which is now minimal, without any other manage hooks.
> Fix transients managing in X.C.Example

- CHANGES.md
- XMonad/Actions/Search.hs
- XMonad/Hooks/Script.hs
- XMonad/Prompt.hs
This is the contrib part of xmonad/xmonad/pull/258 and as such should be merged after that pr.   
> Revise XDG handling 

- XMonad/Hooks/DynamicLog.hs
I fixed the `hlint` warning, and I think no fix applied was "controversial"
Looking at all the warnings during my last PR was annoying, so maybe this will make other contributors avoid that!
> Cleanup: XMonad.Hooks.DynamicLog

- .github/workflows/tests.yml
A couple improvements/cleanups:
* split into buildenv deps and stack build
* make the deps list more git-friendly
* use stack from github environment (I've seen the curl fail intermittently)
* indent consistency
Consistency with haskell-ci (cabal) workflow. It's nice to see the
results before opening a PR so that one doesn't need to embarrass
themselves.
Consistency with the other workflow…
- n/a I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)
- n/a I updated the `CHANGES.md` file
> ci: Maintenance

- .github/ISSUE_TEMPLATE.md
Big bold words are probably the best source of motivation that one can have :)
~~- [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~~
> Add "Steps to Reproduce" to ISSUE_TEMPLATE.md

- CHANGES.md
- XMonad/Hooks/ManageHelpers.hs
I need this in my config and I've seen it being useful for others on
Reddit and IRC.
> X.H.ManageHelpers: Add doLower, doRaise

- XMonad/Layout/Magnifier.hs
Old screenshot 404'd.  I know github may not be the most reliable hoster, but there's at least precedence for using it in our haddocks. 
> X.L.Magnifier: Update screenshot

- XMonad/Prompt/Pass.hs
I may or may not have gone overboard with this, but here we are. 
> X.P.Pass: Update Documentation

- XMonad/Util/Paste.hs
The issue with the current implementation is that in order to paste a character, it's trying to convert a `Char` into a `KeySym` using `stringToKeysym`, which is not really designed for that, as it's supposed to take the name of the character ("colon" or "agrave") — a string. "Luckily", for ascii alphanumeric characters ("a", "1") the name of the character co-incides with the character itself, so the Char is converted into a String and fed to `stringToKeysym`. Unfortunately, this doesn't work even for ascii punctuation, so the output from `stringToKeysym` is fed as default value to `parseKey`. `parseKey` is slightly better, but it does not fare well with non-ascii characters or even with a space " ".
The method suggested in the patch exploits the fact that for Latin-1 characters (Unicode …
> Improve conversion of Char to KeySym in XMonad.Util.Paste

- CHANGES.md
- XMonad/Actions/GridSelect.hs
- XMonad/Layout/NoBorders.hs
> ghc-9.0.1 compatibility fixes

- CHANGES.md
- XMonad/Doc/Extending.hs
- XMonad/Hooks/DynamicLog.hs
- XMonad/Hooks/StatusBar.hs
- XMonad/Hooks/StatusBar/PP.hs
- XMonad/Util/ClickableWorkspaces.hs
- xmonad-contrib.cabal
- XMonad.Hooks.DynamicLog.PP: the pretty-printing abstraction, with the
corresponding utilities
- XMonad.Hooks.StatusBar: A new module to provide a better interface to
manage external status bars.
Still a WIP (mainly: I won't touch `CHANGES.md` till everything else is done); I created the PR so we can discuss more which functions go where and what should be added/deleted. Also, not sure if we let #463 open or close it and move the implementation here.
Reference: https://github.com/xmonad/xmonad-contrib/pull/443#issuecomment-777041434
> Split XMonad.Hooks.DynamicLog

- CHANGES.md
- XMonad/Actions/EasyMotion.hs
> Add 'proportional' to the export list of X.A.EasyMotion

- XMonad/Hooks/StatusBar.hs
As discussed in IRC, I add a bit to improve the example for multiple monitors.
> X.H.StatusBar: update example for multiple monitors

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Clarify that we would really like a full template and not just a snippet where we'll have to guess the context.
- Change the `xmonad-testing` checkbox to something more generic, so people are more inclined to actually fill it in. 
~~- [ ] I tested my changes with [xmonad-testing](https://github.com/xmonad/xmonad-testing)~~
> Update issue and pull-request templates

- CHANGES.md
- XMonad/Layout/BinarySpacePartition.hs
behind them.
manually, ...) and concluded: That it works.
> Add custom resize ratio to X.L.BinarySpacePartition

- XMonad/Hooks/StatusBar.hs
`statusBarPipe` abuses the interface of StatusBarConfig by starting the
status bar before the `startupHook`. This worked correctly before, but it
does not play well with `dynamicSBs`
This is basically a resubmission of #400, with the addition of closing
the handles.
Thank you @liskin for noticing this
> X.H.StatusBar.statusBarPipe: spawn in the startupHook

- CHANGES.md
- XMonad/Hooks/EwmhDesktops.hs
Fixes #567
manually, ...) and concluded: tested manually, have no idea how it can be covered with tests.
> Change EWMH windows ordering to be closer to the spec.

- CHANGES.md
- XMonad/Doc/Extending.hs
- XMonad/Hooks/WindowSwallowing.hs
behind them.
_Originally proposed by @liskin in https://github.com/xmonad/xmonad-contrib/issues/416#issuecomment-777400194_ and framed as a (small) project for ZuriHac 2021.
It is probably a good idea to rename the module to something else, as it does not only do *swallowing* in case of the added feature.
> Window sublayouting

- .github/workflows/nix.yml
- flake.nix
> Add a flake.nix file

- CHANGES.md
- XMonad/Doc/Extending.hs
- XMonad/Layout/FixedAspectRatio.hs
- XMonad/Layout/LayoutHints.hs
- xmonad-contrib.cabal
Layout modifier for user-provided per-window aspect ratios.
> New layout modifier: XMonad.Layout.FixedAspectRatio

- XMonad/Actions/TopicSpace.hs
- XMonad/Actions/TreeSelect.hs
- XMonad/Hooks/DynamicLog.hs
- XMonad/Hooks/StatusBar.hs
- XMonad/Util/EZConfig.hs
- XMonad/Util/NamedActions.hs
- xmonad-contrib.cabal
Related: https://github.com/xmonad/xmonad/pull/318
> Use xmessage from core

- XMonad/Actions/Prefix.hs
Adds a function to utilise EZConfig's Emacs style syntax for entering the prefix key.
The syntax has been well-established for use in configuration files; especially in this case it can be a bit awkward having to specify a function that takes a config just for a single keybinding.
Cc: @Fuco1 
- I tested it manually in my config and it works.  If anything, we should write some property tests for the EZConfig parser
- [n/a] I updated the `XMonad.Doc.Extending` file (if appropriate)
> X.A.Prefix: Add easyPrefixArgument

- XMonad/Hooks/BorderPerWindow.hs
> X.H.BorderPerWindow: Remove unused import

- XMonad/Prompt/OrgMode.hs
- tests/OrgMode.hs
There are a lot of times when we could already check for "valid" input during parsing instead of relaying possibly incorrect dates and times to `org-mode`.  This seems like a sensible thing to do—I don't think anyone would ever want to schedule anything for 35:90 :)
Ever since [1] we allow a second representation for the month (namely, the numerical one).  Since we lose this information during parsing, pretty printing is now not a proper postinverse of parsing (it still is a proper preinverse, however).
Thus, we can't simply check for an inverse anymore.  However, the operations still form an inverse semigroup [2], which is something that's easily checkable.  For simplicity, do this in both directions and completely forget about linearity for now.
[1]: …
> X.P.OrgMode: Update parser tests

- XMonad/Actions/Minimize.hs
behind them.
- n.a. (?) I updated the `CHANGES.md` file
> X.A.Minimize: fix formatting

- XMonad/Actions/FloatKeys.hs
behind them.
manually, ...) and concluded: that the type is not currently exported
> X.A.FloatKeys: Export Type ChangeDim

- XMonad/Hooks/ManageDebug.hs
`ManageDebug` was continuing to report in the `logHook` even after
the `manageHook` was done. In diagnosing this, I discovered that
the original code was using a tuple of `Bool`s and not even a
comment about which meant what.
The code now uses a proper pair type, and dedicated `data`s for
the two flags that make it clear what each means. This also fixed
the bug, so apparently I had the `Bool`s confused somewhere.
I also took the chance to clarify the documentation a little (a
misleading "persistent", since it doesn't use persistent XS) and
a few more cleanups. Also, it now logs all `manageHook` runs
before the `logHook` in case multiple windows are opened.
Fixes #706.
manually, ...) and concluded: tested manually
> buggy boolean blindness

- XMonad/Actions/PerLayoutKeys.hs
> Fix Typo on Line 3

- XMonad/Util/NamedScratchpad.hs
Fixes: https://github.com/xmonad/xmonad-contrib/issues/728
Since 3fc830aa09368dca04df24bf7ec4ac817f2de479, scratchpads are now added in namedScratchpadManageHook.  This, however, means that we need some kind of MapRequestEvent to happen before processing scratchpads, otherwise the manageHook didn't run yet and our extensible state is being left empty.  When trying to open a scratchpad right after starting xmonad—i.e., before having opened a window—this may not be the case.
Here is a small config to reproduce the problem.  When first starting up xmonad, pressing `M-m` does not do anything since we haven't opened a window yet.  After, e.g., spawning a terminal everything works.
``` haskell
import XMonad
import XMonad.StackSet
import XMonad.Util.EZConfig (additionalKeysP)
import …
```
> X.U.NamedScratchpad: Initialise if necessary

- XMonad/Util/Font.hs
- XMonad/Util/XUtils.hs
If pixels have an alpha channel, both `pixelToString` and
`averagePixels` fail and the result is `BadValue` errors and black
borders. Mask out the alpha channels so they work correctly.
Closes https://github.com/xmonad/xmonad/issues/395, https://github.com/xmonad/xmonad/issues/398
manually, ...) and concluded: tested manually
> Fix WindowNavigation borders vs. transparency

- XMonad/Hooks/Modal.hs
behind them.
manually, ...) and concluded: that the documentation now displays properly
> Remove keys type

- .github/workflows/haskell-ci-hackage.patch
- .github/workflows/haskell-ci.yml
- .github/workflows/hlint.yaml
- cabal.haskell-ci
Of course I have no idea what I'm doing, but I tried :)
Closes: https://github.com/xmonad/xmonad-contrib/issues/669
As we have a proper hlint action now, this is no longer needed.
There are some "Reducing duplication" suggestions (which are not warnings) that are still up; I left these in for now.
- [n/a] I've considered how to best test these changes (property, unit,
> Create HLint workflow

- XMonad/Hooks/DebugEvents.hs
Added support for several more properties, and fixed parsing of many others. Still doesn't handle `COMPOUND_TEXT`, and the code in DebugWindow is wrong. I have correct code in C++ but it will require some work to translate to Haskell so it can be used in both places.
manually, ...) and concluded: tested manually
> Fix many bugs and shortcomings in debugEventsHook

- .github/workflows/haskell-ci.yml
- .github/workflows/stack.yml
- xmonad-contrib.cabal
manually, ...) and concluded: CI passes
> Bump cabal/stack CI

- CHANGES.md
- XMonad/Prompt/Pass.hs
manually, ...) and concluded: Been using this for a little bit, and it works fine
> X.P.Pass: Add passOTPTypePrompt

- .github/workflows/haskell-ci.yml
- xmonad-contrib.cabal
(automatic PR by https://github.com/liskin/xmonad-maintenance)
> ci: Regenerate haskell-ci

- xmonad-contrib.cabal
As it says on the tin.
manually, ...) and concluded: tested locally
> time 1.14 update missed the test suite

- XMonad/Actions/OnScreen.hs
- XMonad/Hooks/ScreenCorners.hs
My contrib modules `OnScreen` and `ScreenCorners` contain outdated contact information.
> Update email and copyright for my modules

- .github/workflows/stack.yml
Not removed completely.
https://github.com/xmonad/xmonad-contrib/pull/921#discussion_r1921106271
manually, ...) and concluded: CI fix
> the `stack.yaml` build should have been updated

- xmonad-contrib.cabal
Missed the test suite.
manually, ...) and concluded: tested locally
> let's try that again, shall we? (time 1.15)

- XMonad/Hooks/DynamicIcons.hs
behind them.
i've changed my name, just wanna change it in this module
> X.H.DynamicIcons: change name in it
